import {BlockContent, DefinitionContent, PhrasingContent} from "mdast";
import {fromMarkdown} from "mdast-util-from-markdown";
import {gfmStrikethroughFromMarkdown} from "mdast-util-gfm-strikethrough";
import {gfmStrikethrough} from "micromark-extension-gfm-strikethrough";
import {Fragment, Node} from "prosemirror-model";
import {
    newLineRegExp,
    newLineRegExpWithoutRepetitionOrCapture,
} from "~/server/search/data/index/internal/chunk_search_content.js";
import {isContentCodeBlockLanguageId} from "~/shared/content/content_code_block_language_id.js";
import {HighlightColor} from "~/shared/design/core/highlight_color.js";
import {
    DocumentContent,
    DocumentContentProsemirrorSchema,
    DocumentWithoutTitleContent,
    DocumentWithoutTitleContentProsemirrorSchema,
} from "~/shared/documents/document_content_schema.js";
import {interleaveArray} from "~/shared/helpers/array/interleave_array.js";
import {assert} from "~/shared/helpers/control/assert.js";
import {assertExists} from "~/shared/helpers/control/assert_exists.js";
import {exhaustive} from "~/shared/helpers/control/exhaustive.js";
import {concatIterables} from "~/shared/helpers/iterable/concat_iterables.js";
import {flatMapIterable} from "~/shared/helpers/iterable/flat_map_iterable.js";
import {mapIterable} from "~/shared/helpers/iterable/map_iterable.js";
import {clamp} from "~/shared/helpers/number/clamp.js";

/**
 * Parse content generated by `chunkSearchContent()` back into a ProseMirror
 * node so we can then go and format the ProseMirror node.
 *
 * We should be able to exactly reproduce the node passed in to
 * `parseSearchContent()` with some acceptable lossiness. In other words:
 * `parseSearchContent(chunkSearchContent(node).getFullText()) ≡ node` (the `≡`
 * in math means is equivalent to, you can think of it like `isDeepEqual()`).
 *
 * Styles we lose when `chunkSearchContent()` is called are:
 *
 * - Links, comments, and highlights are discarded
 * - Mentions are formatted as text
 * - Check list items are converted to unordered list items
 *
 * Refer to the [CommonMark specification][1] when in doubt about how content
 * is parsed. We extend the CommonMark specification with
 * GitHub-flavored-markdown strike through (e.g. `~~strikethrough~~`).
 *
 * We've tried writing as many test cases as we can think of in
 * `chunk_search_content.test.ts`, but given the complexity of Markdown and how
 * we accept any user input in a document, it's possible there are edge cases
 * we haven't accounted for.
 *
 * [1]: https://spec.commonmark.org/0.30/#hard-line-breaks
 */
export function parseSearchContent(
    inputText: string,
    {
        shouldParseEmphasisHtmlTagAsHighlight = false,
    }: {
        /**
         * This `parseSearchContent()` function is primarily used with OpenSearch's
         * highlighting functionality. OpenSearch highlights our Markdown search
         * content with `<em>` tags surrounding highlighted content.
         *
         * If this flag is set to true then if we see `<em>` HTML tags then we will
         * apply the `highlight` document mark to content within. The `highlight`
         * document mark will only be used for highlighting `<em>` HTML tags when this
         * flag is true since our markdown format doesn't support `highlight`.
         */
        shouldParseEmphasisHtmlTagAsHighlight?: boolean;
    } = {},
): DocumentContent | DocumentWithoutTitleContent {
    const inputRootNode = fromMarkdown(inputText, "utf-8", {
        extensions: [gfmStrikethrough()],
        mdastExtensions: [gfmStrikethroughFromMarkdown()],
    });

    const firstInputRootChildNode = inputRootNode.children[0];

    const titleInputRootChildNode =
        firstInputRootChildNode?.type === "heading" && firstInputRootChildNode.depth === 1
            ? firstInputRootChildNode
            : undefined;

    const schema = titleInputRootChildNode
        ? DocumentContentProsemirrorSchema
        : DocumentWithoutTitleContentProsemirrorSchema;

    // Unwrap all block nodes `parseBlockNode()` returns to paragraphs.
    const unwrapParsedBlockNode = (outputNode: Node): Iterable<Node> => {
        if (outputNode.type === schema.nodes.quoteBlock) {
            return flatMapIterable(outputNode.content.content, outputChildNode =>
                unwrapParsedBlockNode(outputChildNode),
            );
        }

        if (outputNode.type === schema.nodes.heading || outputNode.type === schema.nodes.code) {
            return [schema.nodes.paragraph.create({}, outputNode.content)];
        }

        return [outputNode];
    };

    const parseBlockNode = (
        inputNode: BlockContent | DefinitionContent,
        indent: number,
    ): Iterable<Node> => {
        switch (inputNode.type) {
            case "paragraph": {
                return [
                    schema.nodes.paragraph.create(
                        {},
                        Array.from(parsePhrasingNodes(inputNode.children)),
                    ),
                ];
            }

            case "blockquote": {
                const outputChildNodes = Array.from(
                    flatMapIterable(inputNode.children, inputChildNode =>
                        flatMapIterable(parseBlockNode(inputChildNode, indent), outputChildNode =>
                            unwrapParsedBlockNode(outputChildNode),
                        ),
                    ),
                );

                return [
                    schema.nodes.quoteBlock.create(
                        {},
                        // If we didn't find any child nodes for the block quote, we need an empty
                        // paragraph.
                        outputChildNodes.length === 0
                            ? [schema.nodes.paragraph.create()]
                            : outputChildNodes,
                    ),
                ];
            }

            case "thematicBreak": {
                return [schema.nodes.divider.create()];
            }

            case "list": {
                return flatMapIterable(inputNode.children, inputChildNode => {
                    const nodeType = inputNode.ordered
                        ? schema.nodes.orderedListItem
                        : schema.nodes.unorderedListItem;

                    const outputNodes = flatMapIterable(
                        flatMapIterable(inputChildNode.children, inputChildChildNode =>
                            parseBlockNode(inputChildChildNode, indent + 1),
                        ),
                        outputNode => unwrapParsedBlockNode(outputNode),
                    );

                    let outputChildItemNodes: Array<Node> = [];
                    const outputOtherNodes: Array<Node> = [];

                    for (const outputNode of outputNodes) {
                        if (outputOtherNodes.length > 0) {
                            outputOtherNodes.push(outputNode);
                            continue;
                        }

                        const optimisticOutputChildItemNodes = [
                            ...outputChildItemNodes,
                            outputNode,
                        ];

                        if (nodeType.validContent(Fragment.from(optimisticOutputChildItemNodes))) {
                            outputChildItemNodes = optimisticOutputChildItemNodes;
                        } else {
                            outputOtherNodes.push(outputNode);
                        }
                    }

                    // If we didn't find any child nodes for the list item, we need an empty
                    // paragraph.
                    if (outputChildItemNodes.length === 0) {
                        outputChildItemNodes.push(schema.nodes.paragraph.create());
                    }

                    return concatIterables(
                        [nodeType.create({indent}, outputChildItemNodes)],
                        outputOtherNodes,
                    );
                });
            }

            case "heading": {
                return [
                    schema.nodes.heading.create(
                        {level: clamp(1, inputNode.depth - 1, 3)},
                        Array.from(parsePhrasingNodes(inputNode.children)),
                    ),
                ];
            }

            case "code": {
                let emphasisTagOpenCount = 0;

                return [
                    schema.nodes.codeBlock.create(
                        {
                            language:
                                typeof inputNode.lang === "string" &&
                                isContentCodeBlockLanguageId(inputNode.lang)
                                    ? inputNode.lang
                                    : "text",
                        },
                        inputNode.value.split(newLineRegExpWithoutRepetitionOrCapture).map(text => {
                            let startIndex = 0;
                            let length = 0;

                            const nodes: Array<Node> = [];
                            const parts = text.split(/(\\?<\/?em\s*>)/g);

                            const print = () => {
                                if (length === 0) return;

                                if (emphasisTagOpenCount === 0) {
                                    nodes.push(
                                        schema.text(text.slice(startIndex, startIndex + length)),
                                    );
                                } else {
                                    nodes.push(
                                        schema.text(text.slice(startIndex, startIndex + length), [
                                            schema.marks.highlight.create({
                                                color: HighlightColor.Orange,
                                            }),
                                        ]),
                                    );
                                }
                            };

                            // Manually implement support for `<em>` tags in inline code
                            for (let i = 0; i < parts.length; i++) {
                                const part = parts[i]!;

                                if (i % 2 === 0) {
                                    length += part.length;
                                    continue;
                                }

                                if (part.startsWith("\\")) {
                                    print();

                                    startIndex = startIndex + length + 1;
                                    length = part.length - 1;
                                    continue;
                                }

                                if (shouldParseEmphasisHtmlTagAsHighlight) {
                                    if (part.startsWith("<em")) {
                                        print();

                                        emphasisTagOpenCount += 1;
                                        startIndex = startIndex + length + part.length;
                                        length = 0;
                                        continue;
                                    }

                                    if (part.startsWith("</em")) {
                                        print();

                                        emphasisTagOpenCount = Math.max(
                                            0,
                                            emphasisTagOpenCount - 1,
                                        );
                                        startIndex = startIndex + length + part.length;
                                        length = 0;
                                        continue;
                                    }
                                }

                                length += part.length;
                            }

                            print();

                            return schema.nodes.codeBlockLine.create({}, nodes);
                        }),
                    ),
                ];
            }

            // `chunkSearchContent()` should not output definitions. In case user
            // content is not properly escaped, definitions are not visible.
            case "definition":
            case "footnoteDefinition": {
                return [];
            }

            // `chunkSearchContent()` should not output HTML. In case user
            // content is not properly escaped, include the raw HTML.
            case "html": {
                return [
                    schema.nodes.paragraph.create(
                        {},
                        inputNode.value.length > 0 ? [schema.text(inputNode.value)] : [],
                    ),
                ];
            }

            // `chunkSearchContent()` should not output these node types. In case user
            // content is not properly escaped, include the raw text.
            case "table": {
                if (!inputNode.position) return [];

                return [
                    schema.nodes.paragraph.create(
                        {},
                        interleaveArray(
                            inputText
                                .slice(
                                    assertExists(inputNode.position.start.offset),
                                    assertExists(inputNode.position.end.offset),
                                )
                                .split(newLineRegExp)
                                .map(text => (text.length > 0 ? [schema.text(text)] : [])),
                            () => [schema.nodes.break.create()],
                        ).flat(),
                    ),
                ];
            }

            default:
                throw exhaustive(inputNode);
        }
    };

    function* parsePhrasingNodes(inputNodes: Iterable<PhrasingContent>): IterableIterator<Node> {
        let isWithinEmphasisTagHighlight = false;

        for (const inputNode of inputNodes) {
            if (inputNode.type === "html" && shouldParseEmphasisHtmlTagAsHighlight) {
                if (/^<em\s*>$/.test(inputNode.value)) {
                    isWithinEmphasisTagHighlight = true;
                    continue;
                }

                if (/^<\/em\s*>$/.test(inputNode.value)) {
                    isWithinEmphasisTagHighlight = false;
                    continue;
                }
            }

            if (!isWithinEmphasisTagHighlight) {
                yield* actuallyParsePhrasingNode(inputNode);
            } else {
                yield* mapIterable(actuallyParsePhrasingNode(inputNode), outputNode =>
                    outputNode.mark(
                        schema.marks.highlight
                            .create({color: HighlightColor.Orange})
                            .addToSet(outputNode.marks),
                    ),
                );
            }
        }
    }

    function* actuallyParsePhrasingNode(inputNode: PhrasingContent): Iterable<Node> {
        switch (inputNode.type) {
            case "text": {
                if (inputNode.value.length > 0) {
                    yield schema.text(inputNode.value);
                }
                break;
            }

            case "emphasis": {
                yield* mapIterable(parsePhrasingNodes(inputNode.children), outputChildNode =>
                    outputChildNode.mark(
                        schema.marks.italic.create().addToSet(outputChildNode.marks),
                    ),
                );
                break;
            }

            case "strong": {
                yield* mapIterable(parsePhrasingNodes(inputNode.children), outputChildNode =>
                    outputChildNode.mark(
                        schema.marks.bold.create().addToSet(outputChildNode.marks),
                    ),
                );
                break;
            }

            case "delete": {
                yield* mapIterable(parsePhrasingNodes(inputNode.children), outputChildNode =>
                    outputChildNode.mark(
                        schema.marks.strike.create().addToSet(outputChildNode.marks),
                    ),
                );
                break;
            }

            case "inlineCode": {
                if (inputNode.value.length === 0) break;

                let emphasisTagOpenCount = 0;
                let startIndex = 0;
                let length = 0;

                const parts = inputNode.value.split(/(\\?<\/?em\s*>)/g);

                const print = () => {
                    if (length === 0) return [];

                    if (emphasisTagOpenCount === 0) {
                        return [
                            schema.text(inputNode.value.slice(startIndex, startIndex + length), [
                                schema.marks.code.create(),
                            ]),
                        ];
                    } else {
                        return [
                            schema.text(inputNode.value.slice(startIndex, startIndex + length), [
                                schema.marks.code.create(),
                                schema.marks.highlight.create({
                                    color: HighlightColor.Orange,
                                }),
                            ]),
                        ];
                    }
                };

                // Manually implement support for `<em>` tags in inline code
                for (let i = 0; i < parts.length; i++) {
                    const part = parts[i]!;

                    if (i % 2 === 0) {
                        length += part.length;
                        continue;
                    }

                    if (part.startsWith("\\")) {
                        yield* print();

                        startIndex = startIndex + length + 1;
                        length = part.length - 1;
                        continue;
                    }

                    if (shouldParseEmphasisHtmlTagAsHighlight) {
                        if (part.startsWith("<em")) {
                            yield* print();

                            emphasisTagOpenCount += 1;
                            startIndex = startIndex + length + part.length;
                            length = 0;
                            continue;
                        }

                        if (part.startsWith("</em")) {
                            yield* print();

                            emphasisTagOpenCount = Math.max(0, emphasisTagOpenCount - 1);
                            startIndex = startIndex + length + part.length;
                            length = 0;
                            continue;
                        }
                    }

                    length += part.length;
                }

                yield* print();
                break;
            }

            case "break": {
                yield schema.nodes.break.create();
                break;
            }

            // `chunkSearchContent()` should not output link nodes. In case user
            // content is not properly escaped, include the link's raw text.
            case "link":
            case "linkReference": {
                yield* parsePhrasingNodes(inputNode.children);
                break;
            }

            // Support some subset of HTML outputted by `chunkSearchContent()` or other
            // tools in our system.
            case "html": {
                // We use HTML break tags when we can't use a Markdown hard break.
                if (/^<br\s*\/?>$/.test(inputNode.value)) {
                    yield schema.nodes.break.create();
                    break;
                }

                if (inputNode.value.length > 0) {
                    yield schema.text(inputNode.value);
                }
                break;
            }

            // `chunkSearchContent()` should not output these node types. In case user
            // content is not properly escaped, include the raw text.
            case "footnoteReference":
            case "image":
            case "imageReference": {
                if (!inputNode.position) break;

                const text = inputText.slice(
                    assertExists(inputNode.position.start.offset),
                    assertExists(inputNode.position.end.offset),
                );

                if (text.length > 0) {
                    yield schema.text(text);
                }
                break;
            }

            default:
                throw exhaustive(inputNode);
        }
    }

    const outputNodes: Array<Node> = [];

    if (titleInputRootChildNode) {
        assert("title" in schema.nodes);

        outputNodes.push(
            schema.nodes.title.create(
                {},
                Array.from(
                    mapIterable(
                        parsePhrasingNodes(titleInputRootChildNode.children),
                        // Clear all marks. Marks are unsupported in titles.
                        outputChildNode => outputChildNode.mark([]),
                    ),
                ),
            ),
        );
    }

    for (let i = titleInputRootChildNode ? 1 : 0; i < inputRootNode.children.length; i++) {
        const inputChildNode = inputRootNode.children[i]!;
        const outputChildNodes = parseBlockNode(
            inputChildNode as BlockContent | DefinitionContent,
            0,
        );

        for (const outputChildNode of outputChildNodes) {
            outputNodes.push(outputChildNode);
        }
    }

    const outputRootNode = assertExists(schema.nodes.doc.createAndFill({}, outputNodes));

    // Make sure the content is correctly formatted.
    outputRootNode.check();

    return outputRootNode as DocumentContent | DocumentWithoutTitleContent;
}
