import {BlockContent, DefinitionContent, PhrasingContent} from "mdast";
import {fromMarkdown} from "mdast-util-from-markdown";
import {gfmStrikethroughFromMarkdown} from "mdast-util-gfm-strikethrough";
import {gfmStrikethrough} from "micromark-extension-gfm-strikethrough";
import {Fragment, Node} from "prosemirror-model";
import {
    newLineRegExp,
    newLineRegExpWithoutRepetitionOrCapture,
} from "~/server/search/data/index/internal/chunk_search_content.js";
import {isContentCodeBlockLanguageId} from "~/shared/content/content_code_block_language_id.js";
import {HighlightColor} from "~/shared/design/core/highlight_color.js";
import {
    DocumentContent,
    DocumentContentProsemirrorSchema,
    DocumentWithoutTitleContent,
    DocumentWithoutTitleContentProsemirrorSchema,
} from "~/shared/documents/document_content_schema.js";
import {InternalError} from "~/shared/error/error.open_source.js";
import {interleaveArray} from "~/shared/helpers/array/interleave_array.open_source.js";
import {assert} from "~/shared/helpers/control/assert.open_source.js";
import {assertExists} from "~/shared/helpers/control/assert_exists.open_source.js";
import {exhaustive} from "~/shared/helpers/control/exhaustive.open_source.js";
import {concatIterables} from "~/shared/helpers/iterable/concat_iterables.open_source.js";
import {flatMapIterable} from "~/shared/helpers/iterable/flat_map_iterable.open_source.js";
import {mapIterable} from "~/shared/helpers/iterable/map_iterable.open_source.js";
import {clamp} from "~/shared/helpers/number/clamp.open_source.js";

const searchContentTableOpenHtml = "<table><tbody><tr><td>";
const searchContentTableCellCloseAndOpenHtml = "</td><td>";
const searchContentTableRowCloseAndOpenHtml = "</td></tr><tr><td>";
const searchContentTableCloseHtml = "</td></tr></tbody></table>";

/**
 * Parse content generated by `chunkSearchContent()` back into a ProseMirror node
 * so we can then go and format the ProseMirror node.
 *
 * We should be able to exactly reproduce the node passed in to
 * `parseSearchContent()` with some acceptable lossiness. In other words:
 * `parseSearchContent(chunkSearchContent(node).getFullText()) ≡ node` (the `≡` in
 * math means is equivalent to, you can think of it like `isDeepEqual()`).
 *
 * Styles we lose when `chunkSearchContent()` is called are:
 *
 * - Links, comments, and highlights are discarded
 * - Mentions are formatted as text
 * - Check list items are converted to unordered list items
 *
 * Refer to the [CommonMark specification][1] when in doubt about how content is
 * parsed. We extend the CommonMark specification with GitHub-flavored-markdown
 * strike through (e.g. `~~strikethrough~~`).
 *
 * We've tried writing as many test cases as we can think of in
 * `chunk_search_content.test.ts`, but given the complexity of Markdown and how we
 * accept any user input in a document, it's possible there are edge cases we
 * haven't accounted for.
 *
 * [1]: https://spec.commonmark.org/0.30/#hard-line-breaks
 */
export function parseSearchContent(
    inputText: string,
    {
        shouldParseEmphasisHtmlTagAsHighlight = false,
    }: {
        /**
         * This `parseSearchContent()` function is primarily used with OpenSearch's
         * highlighting functionality. OpenSearch highlights our Markdown search content
         * with `<em>` tags surrounding highlighted content.
         *
         * If this flag is set to true then if we see `<em>` HTML tags then we will apply
         * the `highlight` document mark to content within. The `highlight` document mark
         * will only be used for highlighting `<em>` HTML tags when this flag is true since
         * our markdown format doesn't support `highlight`.
         */
        shouldParseEmphasisHtmlTagAsHighlight?: boolean;
    } = {},
): DocumentContent | DocumentWithoutTitleContent {
    // NOTE(ifitzsimmons, 2026-01-23): We saw a bug in prod [1] where the search result
    // string was being parsed as a code block due to 4+ spaces after a blockquote
    // marker. We don't allow code blocks within blockquotes in our content schema, so
    // search crashes when trying to redner the match snippet.
    //
    // This happened due to the way chunks are split and returned. Namely, the string
    // was split between a list item at indent 0 and a list item at indent 1 within a
    // blockquote. So the following block
    //
    // ```
    // > - list item 1
    // >     - list item 2
    // ```
    //
    // would be split into:
    //
    // ```
    // >  - list item 1       <----- normal list item
    // ```
    //
    // and
    //
    // ```
    // >     - list item 2    <----- code block
    // ```
    //
    // The second block is parsed as a code block due to the 4+ spaces after the
    // blockquote marker. To fix this, we escape the 4+ spaces after the blockquote
    // marker.
    //
    // [1]:
    //     https://alpine.inc/s/c2pwxmpv3z7b3db19tsn6y1qfg/posts/pb8zfdz708v774zxvbaxj9jd1c
    const preprocessedInputText = inputText.replaceAll(/^> ( +)/gm, "> &#x0020;");

    const inputRootNode = fromMarkdown(preprocessedInputText, "utf-8", {
        extensions: [gfmStrikethrough()],
        mdastExtensions: [gfmStrikethroughFromMarkdown()],
    });

    const firstInputNode = inputRootNode.children[0];

    const titleInputNode =
        firstInputNode?.type === "heading" && firstInputNode.depth === 1
            ? firstInputNode
            : undefined;

    const schema = titleInputNode
        ? DocumentContentProsemirrorSchema
        : DocumentWithoutTitleContentProsemirrorSchema;

    // Unwrap all block nodes `parseBlockNode()` returns to paragraphs.
    const unwrapParsedBlockNode = (outputNode: Node): Iterable<Node> => {
        if (outputNode.type === schema.nodes.quoteBlock) {
            return flatMapIterable(outputNode.content.content, outputChildNode =>
                unwrapParsedBlockNode(outputChildNode),
            );
        }

        if (outputNode.type === schema.nodes.heading || outputNode.type === schema.nodes.code) {
            return [schema.nodes.paragraph.create({}, outputNode.content)];
        }

        return [outputNode];
    };

    const parseBlockNode = (
        inputNode:
            | BlockContent
            | DefinitionContent
            // Make TypeScript happy. `math` is valid `BlockContent` when we run TypeScript on
            // the entire codebase since it's used in `parseApiContentFromMarkdown()` but it's
            // not available when we run TypeScript just on this Bazel package. Make the two
            // environments consistent by adding a stub type here.
            | {readonly type: "math"}
            | {readonly type: "mdxFlowExpression"}
            | {readonly type: "mdxJsxFlowElement"},
        indent: number,
    ): Iterable<Node> => {
        switch (inputNode.type) {
            case "paragraph": {
                return [
                    schema.nodes.paragraph.create(
                        {},
                        Array.from(parsePhrasingNodes(inputNode.children)),
                    ),
                ];
            }

            case "blockquote": {
                const outputChildNodes = Array.from(
                    flatMapIterable(inputNode.children, inputChildNode =>
                        flatMapIterable(parseBlockNode(inputChildNode, indent), outputChildNode =>
                            unwrapParsedBlockNode(outputChildNode),
                        ),
                    ),
                );

                return [
                    schema.nodes.quoteBlock.create(
                        {},
                        // If we didn't find any child nodes for the block quote, we need an empty
                        // paragraph.
                        outputChildNodes.length === 0
                            ? [schema.nodes.paragraph.create()]
                            : outputChildNodes,
                    ),
                ];
            }

            case "thematicBreak": {
                return [schema.nodes.divider.create()];
            }

            case "list": {
                return flatMapIterable(inputNode.children, inputChildNode => {
                    const nodeType = inputNode.ordered
                        ? schema.nodes.orderedListItem
                        : schema.nodes.unorderedListItem;

                    const outputNodes = flatMapIterable(
                        flatMapIterable(inputChildNode.children, inputChildChildNode =>
                            parseBlockNode(inputChildChildNode, indent + 1),
                        ),
                        outputNode => unwrapParsedBlockNode(outputNode),
                    );

                    let outputChildItemNodes: Array<Node> = [];
                    const outputOtherNodes: Array<Node> = [];

                    for (const outputNode of outputNodes) {
                        if (outputOtherNodes.length > 0) {
                            outputOtherNodes.push(outputNode);
                            continue;
                        }

                        const optimisticOutputChildItemNodes = [
                            ...outputChildItemNodes,
                            outputNode,
                        ];

                        if (nodeType.validContent(Fragment.from(optimisticOutputChildItemNodes))) {
                            outputChildItemNodes = optimisticOutputChildItemNodes;
                        } else {
                            outputOtherNodes.push(outputNode);
                        }
                    }

                    // If we didn't find any child nodes for the list item, we need an empty paragraph.
                    if (outputChildItemNodes.length === 0) {
                        outputChildItemNodes.push(schema.nodes.paragraph.create());
                    }

                    return concatIterables(
                        [nodeType.create({indent}, outputChildItemNodes)],
                        outputOtherNodes,
                    );
                });
            }

            case "heading": {
                return [
                    schema.nodes.heading.create(
                        {level: clamp(1, inputNode.depth - 1, 3)},
                        Array.from(parsePhrasingNodes(inputNode.children)),
                    ),
                ];
            }

            case "code": {
                let emphasisTagOpenCount = 0;

                return [
                    schema.nodes.codeBlock.create(
                        {
                            language:
                                typeof inputNode.lang === "string" &&
                                isContentCodeBlockLanguageId(inputNode.lang)
                                    ? inputNode.lang
                                    : "text",
                        },
                        inputNode.value.split(newLineRegExpWithoutRepetitionOrCapture).map(text => {
                            let startIndex = 0;
                            let length = 0;

                            const nodes: Array<Node> = [];
                            const parts = text.split(/(\\?<\/?em\s*>)/g);

                            const print = () => {
                                if (length === 0) return;

                                if (emphasisTagOpenCount === 0) {
                                    nodes.push(
                                        schema.text(text.slice(startIndex, startIndex + length)),
                                    );
                                } else {
                                    nodes.push(
                                        schema.text(text.slice(startIndex, startIndex + length), [
                                            schema.marks.highlight.create({
                                                color: HighlightColor.Orange,
                                            }),
                                        ]),
                                    );
                                }
                            };

                            // Manually implement support for `<em>` tags in inline code
                            for (let i = 0; i < parts.length; i++) {
                                const part = parts[i]!;

                                if (i % 2 === 0) {
                                    length += part.length;
                                    continue;
                                }

                                if (part.startsWith("\\")) {
                                    print();

                                    startIndex = startIndex + length + 1;
                                    length = part.length - 1;
                                    continue;
                                }

                                if (shouldParseEmphasisHtmlTagAsHighlight) {
                                    if (part.startsWith("<em")) {
                                        print();

                                        emphasisTagOpenCount += 1;
                                        startIndex = startIndex + length + part.length;
                                        length = 0;
                                        continue;
                                    }

                                    if (part.startsWith("</em")) {
                                        print();

                                        emphasisTagOpenCount = Math.max(
                                            0,
                                            emphasisTagOpenCount - 1,
                                        );
                                        startIndex = startIndex + length + part.length;
                                        length = 0;
                                        continue;
                                    }
                                }

                                length += part.length;
                            }

                            print();

                            return schema.nodes.codeBlockLine.create({}, nodes);
                        }),
                    ),
                ];
            }

            // `chunkSearchContent()` should not output definitions. In case user content is
            // not properly escaped, definitions are not visible.
            case "definition":
            case "footnoteDefinition": {
                return [];
            }

            // `chunkSearchContent()` only outputs HTML if it's used for formatting content.
            // For example `<table>`, `<br>`, and to some extend `<em>` which is added by the
            // OpenSearch highlighter.
            //
            // Don't include unknown HTML in parsed content.
            case "html": {
                return [];
            }

            // `chunkSearchContent()` should not output these node types. In case user content
            // is not properly escaped, include the raw text.
            case "table": {
                if (!inputNode.position) return [];

                return [
                    schema.nodes.paragraph.create(
                        {},
                        interleaveArray(
                            inputText
                                .slice(
                                    assertExists(inputNode.position.start.offset),
                                    assertExists(inputNode.position.end.offset),
                                )
                                .split(newLineRegExp)
                                .map(text => (text.length > 0 ? [schema.text(text)] : [])),
                            () => [schema.nodes.break.create()],
                        ).flat(),
                    ),
                ];
            }

            case "math": {
                throw new InternalError(
                    "Unreachable, search Markdown parser doesn\u2019t use math plugin",
                );
            }
            case "mdxFlowExpression":
            case "mdxJsxFlowElement": {
                throw new InternalError(
                    "Unreachable, search Markdown parser doesn\u2019t use MDX plugin",
                );
            }

            default:
                throw exhaustive(inputNode);
        }
    };

    function* parsePhrasingNodes(inputNodes: Iterable<PhrasingContent>): IterableIterator<Node> {
        let isWithinEmphasisTagHighlight = false;

        for (const inputNode of inputNodes) {
            if (inputNode.type === "html" && shouldParseEmphasisHtmlTagAsHighlight) {
                if (/^<em\s*>$/.test(inputNode.value)) {
                    isWithinEmphasisTagHighlight = true;
                    continue;
                }

                if (/^<\/em\s*>$/.test(inputNode.value)) {
                    isWithinEmphasisTagHighlight = false;
                    continue;
                }
            }

            if (!isWithinEmphasisTagHighlight) {
                yield* actuallyParsePhrasingNode(inputNode);
            } else {
                yield* mapIterable(actuallyParsePhrasingNode(inputNode), outputNode =>
                    outputNode.mark(
                        schema.marks.highlight
                            .create({color: HighlightColor.Orange})
                            .addToSet(outputNode.marks),
                    ),
                );
            }
        }
    }

    function* actuallyParsePhrasingNode(
        inputNode:
            | PhrasingContent
            // Make TypeScript happy. `inlineMath` is valid `PhrasingContent` when we run
            // TypeScript on the entire codebase since it's used in
            // `parseApiContentFromMarkdown()` but it's not available when we run TypeScript
            // just on this Bazel package. Make the two environments consistent by adding a
            // stub type here.
            | {type: "inlineMath"}
            | {type: "mdxTextExpression"}
            | {type: "mdxJsxTextElement"},
    ): Iterable<Node> {
        switch (inputNode.type) {
            case "text": {
                if (inputNode.value.length > 0) {
                    yield schema.text(inputNode.value);
                }
                break;
            }

            case "emphasis": {
                yield* mapIterable(parsePhrasingNodes(inputNode.children), outputChildNode =>
                    outputChildNode.mark(
                        schema.marks.italic.create().addToSet(outputChildNode.marks),
                    ),
                );
                break;
            }

            case "strong": {
                yield* mapIterable(parsePhrasingNodes(inputNode.children), outputChildNode =>
                    outputChildNode.mark(
                        schema.marks.bold.create().addToSet(outputChildNode.marks),
                    ),
                );
                break;
            }

            case "delete": {
                yield* mapIterable(parsePhrasingNodes(inputNode.children), outputChildNode =>
                    outputChildNode.mark(
                        schema.marks.strike.create().addToSet(outputChildNode.marks),
                    ),
                );
                break;
            }

            case "inlineCode": {
                if (inputNode.value.length === 0) break;

                let emphasisTagOpenCount = 0;
                let startIndex = 0;
                let length = 0;

                const parts = inputNode.value.split(/(\\?<\/?em\s*>)/g);

                const print = () => {
                    if (length === 0) return [];

                    if (emphasisTagOpenCount === 0) {
                        return [
                            schema.text(inputNode.value.slice(startIndex, startIndex + length), [
                                schema.marks.code.create(),
                            ]),
                        ];
                    } else {
                        return [
                            schema.text(inputNode.value.slice(startIndex, startIndex + length), [
                                schema.marks.code.create(),
                                schema.marks.highlight.create({
                                    color: HighlightColor.Orange,
                                }),
                            ]),
                        ];
                    }
                };

                // Manually implement support for `<em>` tags in inline code
                for (let i = 0; i < parts.length; i++) {
                    const part = parts[i]!;

                    if (i % 2 === 0) {
                        length += part.length;
                        continue;
                    }

                    if (part.startsWith("\\")) {
                        yield* print();

                        startIndex = startIndex + length + 1;
                        length = part.length - 1;
                        continue;
                    }

                    if (shouldParseEmphasisHtmlTagAsHighlight) {
                        if (part.startsWith("<em")) {
                            yield* print();

                            emphasisTagOpenCount += 1;
                            startIndex = startIndex + length + part.length;
                            length = 0;
                            continue;
                        }

                        if (part.startsWith("</em")) {
                            yield* print();

                            emphasisTagOpenCount = Math.max(0, emphasisTagOpenCount - 1);
                            startIndex = startIndex + length + part.length;
                            length = 0;
                            continue;
                        }
                    }

                    length += part.length;
                }

                yield* print();
                break;
            }

            case "break": {
                yield schema.nodes.break.create();
                break;
            }

            // `chunkSearchContent()` should not output link nodes. In case user content is not
            // properly escaped, include the link's raw text.
            case "link":
            case "linkReference": {
                yield* parsePhrasingNodes(inputNode.children);
                break;
            }

            // Support some subset of HTML outputted by `chunkSearchContent()` or other tools
            // in our system.
            case "html": {
                // We use HTML break tags when we can't use a Markdown hard break.
                if (/^<br\s*\/?>$/.test(inputNode.value)) {
                    yield schema.nodes.break.create();
                    break;
                }

                if (inputNode.value.length > 0) {
                    yield schema.text(inputNode.value);
                }
                break;
            }

            // `chunkSearchContent()` should not output these node types. In case user content
            // is not properly escaped, include the raw text.
            case "footnoteReference":
            case "image":
            case "imageReference": {
                if (!inputNode.position) break;

                const text = inputText.slice(
                    assertExists(inputNode.position.start.offset),
                    assertExists(inputNode.position.end.offset),
                );

                if (text.length > 0) {
                    yield schema.text(text);
                }
                break;
            }

            case "inlineMath": {
                throw new InternalError(
                    "Unreachable, search Markdown parser doesn\u2019t use math plugin",
                );
            }
            case "mdxTextExpression":
            case "mdxJsxTextElement": {
                throw new InternalError(
                    "Unreachable, search Markdown parser doesn\u2019t use MDX plugin",
                );
            }

            default:
                throw exhaustive(inputNode);
        }
    }

    const outputNodes: Array<Node> = [];

    if (titleInputNode) {
        assert("title" in schema.nodes);

        outputNodes.push(
            schema.nodes.title.create(
                {},
                Array.from(
                    parsePhrasingNodes(titleInputNode.children),
                    // Clear all marks. Marks are unsupported in titles.
                    outputNode => outputNode.mark([]),
                ),
            ),
        );
    }

    const processInputNode = (inputNode: BlockContent | DefinitionContent) => {
        for (const outputNode of parseBlockNode(inputNode, 0)) {
            outputNodes.push(outputNode);
        }
    };

    let inputNodeIndex = titleInputNode ? 1 : 0;

    while (inputNodeIndex < inputRootNode.children.length) {
        const inputNode = inputRootNode.children[inputNodeIndex]!;

        // If we see `<table>` HTML then run a special table parser to reconstruct a table
        // ProseMirror node.
        if (
            inputNode.type !== "html" ||
            (inputNode.value !== searchContentTableOpenHtml &&
                inputNode.value !== searchContentTableCellCloseAndOpenHtml &&
                inputNode.value !== searchContentTableRowCloseAndOpenHtml)
        ) {
            processInputNode(inputNode as BlockContent | DefinitionContent);
            inputNodeIndex++;
            continue;
        }

        inputNodeIndex++;

        const outputTableRows: Array<{cells: Array<{nodes: Array<Node>}>}> = [
            {cells: [{nodes: []}]},
        ];

        for (; inputNodeIndex < inputRootNode.children.length; inputNodeIndex++) {
            const inputTableNode = inputRootNode.children[inputNodeIndex]!;

            const finish = () => {
                let tableWidth = 2;

                for (const outputTableRow of outputTableRows) {
                    tableWidth = Math.max(outputTableRow.cells.length, tableWidth);
                }

                // If the start of the table was `</td><td>` that implies there are more columns in
                // the table that we don't know about. Add empty cells to the start of the first
                // row since previous cells were before the first parsed cell.
                if (
                    inputNode.value === searchContentTableCellCloseAndOpenHtml &&
                    outputTableRows.length > 0
                ) {
                    const firstOutputTableRow = outputTableRows[0]!;

                    while (firstOutputTableRow.cells.length < tableWidth) {
                        firstOutputTableRow.cells.unshift({nodes: []});
                    }
                }

                // Fill table rows to the table width with empty cells if we have rows width a
                // width less than our expected table width.
                for (const outputTableRow of outputTableRows) {
                    while (outputTableRow.cells.length < tableWidth) {
                        outputTableRow.cells.push({nodes: []});
                    }
                }

                outputNodes.push(
                    schema.nodes.table.create(
                        {},
                        outputTableRows.map(outputTableRow =>
                            assertExists(
                                schema.nodes.tableRow.createAndFill(
                                    {},
                                    outputTableRow.cells.map(outputTableCell =>
                                        assertExists(
                                            schema.nodes.tableCell.createAndFill(
                                                {},
                                                outputTableCell.nodes,
                                            ),
                                        ),
                                    ),
                                ),
                            ),
                        ),
                    ),
                );
            };

            if (inputTableNode.type === "html") {
                const html = inputTableNode.value;

                if (html === searchContentTableCellCloseAndOpenHtml) {
                    const outputTableRow = outputTableRows[outputTableRows.length - 1]!;
                    outputTableRow.cells.push({nodes: []});
                    continue;
                } else if (html === searchContentTableRowCloseAndOpenHtml) {
                    outputTableRows.push({cells: [{nodes: []}]});
                    continue;
                } else if (html === searchContentTableCloseHtml) {
                    finish();
                    inputNodeIndex++;
                    break;
                }
            }

            const outputTableRow = outputTableRows[outputTableRows.length - 1]!;
            const outputTableCell = outputTableRow.cells[outputTableRow.cells.length - 1]!;

            for (const outputTableNode of parseBlockNode(
                inputTableNode as BlockContent | DefinitionContent,
                0,
            )) {
                outputTableCell.nodes.push(outputTableNode);
            }

            // If we reach the end of our content and there were no closing HTML tags then
            // finish the table as is
            if (inputNodeIndex === inputRootNode.children.length - 1) {
                finish();
                inputNodeIndex++;
                break;
            }
        }
    }

    const outputRootNode = assertExists(schema.nodes.doc.createAndFill({}, outputNodes));

    // Make sure the content is correctly formatted.
    outputRootNode.check();

    return outputRootNode as DocumentContent | DocumentWithoutTitleContent;
}
