load("//admin/typescript:typescript.bzl", "ts_project")

ts_project(
    name = "core",
    deps = [
        ":index_data",
        "//shared/error",
        "//shared/helpers",
        "//shared/schema",
    ],
)
