import fs from "fs-extra";
import {parseArgs} from "util";
import {crawlDynamoTableSchemaIndexNames, crawlDynamoTableSchemas} from "~/admin/crawl/crawl.js";
import {runAllPromiseThunks} from "~/shared/helpers/async/run_all_promises.js";
import {assert} from "~/shared/helpers/control/assert.js";
import {concatIterables} from "~/shared/helpers/iterable/concat_iterables.js";
import {mapIterable} from "~/shared/helpers/iterable/map_iterable.js";
import {JsonValue} from "~/shared/helpers/types/json_value.js";
import {serializeSchemaDescriptionToJsonSafeValue} from "~/shared/schema/schema_description_json.js";

async function main() {
    const {
        values: {dynamoSchemaDescriptionPath, tracerEventDataDynamoPath},
    } = parseArgs({
        options: {
            dynamoSchemaDescriptionPath: {type: "string"},
            tracerEventDataDynamoPath: {type: "string"},
        },
    });

    assert(dynamoSchemaDescriptionPath);
    assert(tracerEventDataDynamoPath);

    const tableSchemas = await crawlDynamoTableSchemas();

    await runAllPromiseThunks(
        async () => {
            const tableByName: {[key: string]: JsonValue} = {};

            for (const tableSchema of tableSchemas) {
                const description = tableSchema.getDescription();
                tableByName[description.name] = description;
            }

            const description = {tableByName};
            const descriptionString = JSON.stringify(
                serializeSchemaDescriptionToJsonSafeValue(description),
                null,
                4,
            );

            /* eslint-disable cyberworlds/string-quotes */

            await fs.writeFile(
                dynamoSchemaDescriptionPath,
                `// @generated by //admin/dynamo:write_schema

/* eslint-disable cyberworlds/string-quotes */

import {DynamoTableSchemaTypes} from "~/server/dynamo/core/types/dynamo_table_schema_types.js";
import {deserializeSchemaDescriptionFromJsonSafeValue} from "~/shared/schema/schema_description_json.js";

// V8 suggests using \`JSON.parse()\` to speed up parsing time for objects of
// 10kb or larger.
// https://v8.dev/blog/cost-of-javascript-2019#json
// prettier-ignore
export const dynamoGeneratedSchemaDescription: {
    readonly tableByName: {
        readonly [name: string]: DynamoTableSchemaTypes.Description;
    };
} = deserializeSchemaDescriptionFromJsonSafeValue(JSON.parse(\`${descriptionString}\`)) as any;
`,
            );
        },
        async () => {
            await fs.writeFile(
                tracerEventDataDynamoPath,
                `// @generated by //admin/dynamo:write_schema

/**
 * A list of keys to replace \`*\` in the \`dynamodb.consumed_capacity.*\` event
 * attribute. It is generated by \`generate_dynamo_files_main.ts\`.
 *
 * We need a list of DynamoDB tables so we generate it from \`//server/dynamo\`
 * instead of importing \`//server/dynamo\` at runtime. That way code which doesn't
 * directly depend on DynamoDB doesn't need to pay the runtime cost of initializing
 * DynamoDB tables.
 *
 * We commit the file so there isn't a package dependency on \`//server/dynamo\`
 * either which our dev server would see and rebuild \`//server/tracer\` dependents
 * on \`//server/dynamo\` changes.
 */
export const tracerEventDataDynamoConsumedCapacityKeys = new Set([
${Array.from(
    concatIterables(
        mapIterable(tableSchemas, tableSchema => tableSchema.getName()),
        mapIterable(
            await crawlDynamoTableSchemaIndexNames(),
            ({tableName, indexName}) => `${tableName}_${indexName}`,
        ),
    ),
    key => `    ${JSON.stringify(key)},\n`,
).join("")}]);

/**
 * All the partition types for each table. We use these to build the tracer event
 * data schema for \`dynamodb.item\` which includes partition types and sort range
 * types in a nested format.
 *
 * We generate this map from \`//server/dynamo\` instead of importing
 * \`//server/dynamo\` at runtime. That way code which doesn't directly depend on
 * DynamoDB doesn't need to pay the runtime cost of initializing DynamoDB tables.
 *
 * We commit the file so there isn't a package dependency on \`//server/dynamo\`
 * either which our dev server would see and rebuild \`//server/tracer\` dependents
 * on \`//server/dynamo\` changes.
 */
// prettier-ignore
export const tracerEventDataDynamoPartitionTypesByTableName = new Map<string, ReadonlyArray<string>>([
${Array.from(
    tableSchemas,
    tableSchema =>
        `    [${JSON.stringify(tableSchema.getName())}, [${Object.keys(
            tableSchema.getDescription().partitionByType,
        )
            .map(partitionType => JSON.stringify(partitionType))
            .join(", ")}]],\n`,
).join("")}]);
`,
            );
        },
    );

    /* eslint-enable cyberworlds/string-quotes */
}

main().then(
    () => {
        process.exitCode = 0;
    },
    error => {
        // eslint-disable-next-line no-console
        console.error(error);
        process.exitCode = 1;
    },
);
