import {getAllDynamoTableSchemas} from "~/server/dynamo/get_all_dynamo_table_schemas";
import {JsonValue} from "~/shared/helpers/types/json_value";
import {serializeSchemaDescriptionToJsonSafeValue} from "~/shared/schema/schema_description_json";

async function main() {
    const tableByName: {[key: string]: JsonValue} = {};

    for (const tableSchema of getAllDynamoTableSchemas()) {
        const description = tableSchema.getDescription();
        tableByName[description.name] = description;
    }

    const description = {tableByName};
    const descriptionString = JSON.stringify(
        serializeSchemaDescriptionToJsonSafeValue(description),
        null,
        4,
    );

    // NOTE(calebmer): We wrap `dynamoGeneratedSchemaDescription` in a `Lazy`
    // object so we can remove it from initial module evaluation to keep ourselves
    // under the Cloudflare module evaluation limit.
    process.stdout.write(
        `// @generated by //server/dynamo:write_schema

import {DynamoTableSchemaTypes} from "~/server/dynamo/internal/types/dynamo_table_schema_types";
import {Lazy} from "~/shared/helpers/control/lazy";
import {deserializeSchemaDescriptionFromJsonSafeValue} from "~/shared/schema/schema_description_json";

// prettier-ignore
export const dynamoGeneratedSchemaDescription: Lazy<{
    readonly tableByName: {
        readonly [name: string]: DynamoTableSchemaTypes.Description;
    };
}> = new Lazy(() => deserializeSchemaDescriptionFromJsonSafeValue(${descriptionString} as any) as any);
`,
    );
}

main().then(
    () => {
        process.exitCode = 0;
    },
    error => {
        // eslint-disable-next-line no-console
        console.error(error);
        process.exitCode = 1;
    },
);
