import fs from "fs-extra";
import {parseArgs} from "util";
import {
    getAllDynamoTableSchemaIndexNames,
    getAllDynamoTableSchemas,
} from "~/admin/dynamo/get_all_dynamo_table_schemas.js";
import {runAllPromiseThunks} from "~/shared/helpers/async/run_all_promises.js";
import {assert} from "~/shared/helpers/control/assert.js";
import {JsonValue} from "~/shared/helpers/types/json_value.js";
import {serializeSchemaDescriptionToJsonSafeValue} from "~/shared/schema/schema_description_json.js";

async function main() {
    const {
        values: {dynamoSchemaDescriptionPath, tracerEventDataDynamoConsumedCapacityKeysPath},
    } = parseArgs({
        options: {
            dynamoSchemaDescriptionPath: {type: "string"},
            tracerEventDataDynamoConsumedCapacityKeysPath: {type: "string"},
        },
    });

    assert(dynamoSchemaDescriptionPath);
    assert(tracerEventDataDynamoConsumedCapacityKeysPath);

    await runAllPromiseThunks(
        async () => {
            const tableByName: {[key: string]: JsonValue} = {};

            for (const tableSchema of await getAllDynamoTableSchemas()) {
                const description = tableSchema.getDescription();
                tableByName[description.name] = description;
            }

            const description = {tableByName};
            const descriptionString = JSON.stringify(
                serializeSchemaDescriptionToJsonSafeValue(description),
                null,
                4,
            );

            await fs.writeFile(
                dynamoSchemaDescriptionPath,
                `// @generated by //admin/dynamo:write_schema

import {DynamoTableSchemaTypes} from "~/server/dynamo/core/internal/types/dynamo_table_schema_types.js";
import {deserializeSchemaDescriptionFromJsonSafeValue} from "~/shared/schema/schema_description_json.js";

// V8 suggests using \`JSON.parse()\` to speed up parsing time for objects of
// 10kb or larger.
// https://v8.dev/blog/cost-of-javascript-2019#json
// prettier-ignore
export const dynamoGeneratedSchemaDescription: {
    readonly tableByName: {
        readonly [name: string]: DynamoTableSchemaTypes.Description;
    };
} = deserializeSchemaDescriptionFromJsonSafeValue(JSON.parse(\`${descriptionString}\`)) as any;
`,
            );
        },
        async () => {
            await fs.writeFile(
                tracerEventDataDynamoConsumedCapacityKeysPath,
                `// @generated by //admin/dynamo:write_schema

/**
 * A list of keys to replace \`*\` in the \`dynamodb.consumed_capacity.*\` event
 * attribute. It is generated by
 * \`generate_tracer_event_data_dynamo_consumed_capacity_keys_main.ts\`.
 *
 * We need a list of DynamoDB tables so we generate it from \`//server/dynamo\`
 * instead of importing \`//server/dynamo\` at runtime. That way code which
 * doesn't directly depend on DynamoDB doesn't need to pay the runtime cost of
 * initializing DynamoDB tables.
 *
 * We commit the file so there isn't a package dependency on \`//server/dynamo\`
 * either which our dev server would see and rebuild \`//server/tracer\`
 * dependents on \`//server/dynamo\` changes.
 */
export const tracerEventDataDynamoConsumedCapacityKeys = [
        ${[
            ...(await getAllDynamoTableSchemas()).map(tableSchema => tableSchema.getName()),
            ...(
                await getAllDynamoTableSchemaIndexNames()
            ).map(({tableName, indexName}) => `${tableName}_${indexName}`),
        ]
            .map(key => `    ${JSON.stringify(key)},\n`)
            .join("")}];
`,
            );
        },
    );
}

main().then(
    () => {
        process.exitCode = 0;
    },
    error => {
        // eslint-disable-next-line no-console
        console.error(error);
        process.exitCode = 1;
    },
);
