import {getAllDynamoTableSchemas} from "~/server/dynamo/get_all_dynamo_table_schemas";

async function main() {
    const tableByName: {[key: string]: unknown} = {};

    for (const tableSchema of getAllDynamoTableSchemas()) {
        tableByName[tableSchema.description.name] = tableSchema.description;
    }

    const description = {tableByName};
    const descriptionString = JSON.stringify(description, null, 4);

    process.stdout.write(
        `\
// @generated by //server/dynamo:write_schema

import {DynamoTableSchemaTypes} from "~/server/dynamo/internal/types/dynamo_table_schema_types";

// prettier-ignore
export const dynamoGeneratedSchemaDescription: {
    readonly tableByName: {
        readonly [name: string]: DynamoTableSchemaTypes.Description;
    };
} = ${descriptionString} as any;
`,
    );
}

main().then(
    () => {
        process.exitCode = 0;
    },
    error => {
        // eslint-disable-next-line no-console
        console.error(error);
        process.exitCode = 1;
    },
);
