import {getAllDynamoTableSchemas} from "~/server/dynamo/get_all_dynamo_table_schemas.js";
import {JsonValue} from "~/shared/helpers/types/json_value.js";
import {serializeSchemaDescriptionToJsonSafeValue} from "~/shared/schema/schema_description_json.js";

async function main() {
    const tableByName: {[key: string]: JsonValue} = {};

    for (const tableSchema of getAllDynamoTableSchemas()) {
        const description = tableSchema.getDescription();
        tableByName[description.name] = description;
    }

    const description = {tableByName};
    const descriptionString = JSON.stringify(
        serializeSchemaDescriptionToJsonSafeValue(description),
        null,
        4,
    );

    process.stdout.write(
        `// @generated by //server/dynamo:write_schema

import {DynamoTableSchemaTypes} from "~/server/dynamo/internal/types/dynamo_table_schema_types.js";
import {deserializeSchemaDescriptionFromJsonSafeValue} from "~/shared/schema/schema_description_json.js";

// V8 suggests using \`JSON.parse()\` to speed up parsing time for objects of
// 10kb or larger.
// https://v8.dev/blog/cost-of-javascript-2019#json
// prettier-ignore
export const dynamoGeneratedSchemaDescription: {
    readonly tableByName: {
        readonly [name: string]: DynamoTableSchemaTypes.Description;
    };
} = deserializeSchemaDescriptionFromJsonSafeValue(JSON.parse(\`${descriptionString}\`)) as any;
`,
    );
}

main().then(
    () => {
        process.exitCode = 0;
    },
    error => {
        // eslint-disable-next-line no-console
        console.error(error);
        process.exitCode = 1;
    },
);
