load("//admin/typescript:typescript.bzl", "ts_project")

ts_project(
    name = "messaging",
    visibility = ["//server:__subpackages__"],
    deps = [
        "//shared/id",
        "//shared/messaging",
        "//shared/schema",
    ],
)
