load("//admin/typescript:typescript.bzl", "ts_project")

ts_project(
    name = "bots",
    visibility = ["//visibility:public"],
    deps = [
        "//shared/avatar",
        "//shared/bots/owners",
        "//shared/id",
        "//shared/schema",
        "//shared/spaces",
    ],
)
