import {xxh64} from "@node-rs/xxhash";
import fs from "fs-extra";
import {join as joinPath} from "path";
import {runfilesPath} from "~/server/helpers/node/runfiles_path.js";
import {runAllPromises} from "~/shared/helpers/async/run_all_promises.js";
import {Tuple} from "~/shared/helpers/types/tuple.js";

async function main() {
    const [commitMonoFontContents, interItalicFontContents, interFontContents] =
        await runAllPromises(
            [
                "cyberworlds/app/static/_fonts/commit-mono-patched.woff2",
                "cyberworlds/app/static/_fonts/inter-italic-patched.woff2",
                "cyberworlds/app/static/_fonts/inter-patched.woff2",
            ].map(path => fs.readFile(joinPath(runfilesPath, path))) as Tuple<Promise<Buffer>, 3>,
        );

    const commitMonoFontHash = xxh64(commitMonoFontContents).toString(16).padStart(16, "0");
    const interItalicFontHash = xxh64(interItalicFontContents).toString(16).padStart(16, "0");
    const interFontHash = xxh64(interFontContents).toString(16).padStart(16, "0");

    await runAllPromises([
        fs.writeFile(
            "_fonts/font_hashes.ts",
            `// @generated by //shared/design:write_font_metrics

export const commitMonoFontHash = ${JSON.stringify(commitMonoFontHash)};
export const interItalicFontHash = ${JSON.stringify(interItalicFontHash)};
export const interFontHash = ${JSON.stringify(interFontHash)};
`,
        ),
        fs.writeFile(`fonts/commit-mono-${commitMonoFontHash}.woff2`, commitMonoFontContents),
        fs.writeFile(`fonts/inter-italic-${interItalicFontHash}.woff2`, interItalicFontContents),
        fs.writeFile(`fonts/inter-${interFontHash}.woff2`, interFontContents),
    ]);
}

main().catch(error => {
    // eslint-disable-next-line no-console
    console.error(error);
    process.exitCode = 1;
});
