name: "Initialize Bazel cache"
description: "Sets up the Bazel repository cache and remote cache"

runs:
    using: "composite"
    steps:
        # We cache Bazel external repositories with [GitHub's cache action][1]. We
        # cache individual build rule results with [Bazel remote caching][2].
        #
        # The following restores the previously saved Bazel repository cache. The Bazel
        # repository's cache key includes a hash of all files that contribute to the
        # external repositories we download. All external repositories are defined in
        # `WORKSPACE` or a file referenced by `WORKSPACE` (e.g. `pnpm-lock.yaml` which
        # is used by the `npm_translate_lock()` call in `WORKSPACE`).
        #
        # We also include the Bazel binary installed by Bazelisk in this cache so we
        # include a hash of `.bazelversion`.
        #
        # [1]: https://github.com/actions/cache
        # [2]: https://bazel.build/remote/caching
        - id: cache
          name: Restore Bazel repositories cache
          uses: actions/cache/restore@v3
          with:
                path: |
                    ~/.cache/bazelisk
                    ~/.cache/bazel
                # IMPORTANT: Should have the same `hashFiles()` as `deploy.yaml`. We want to
                # share our cache between the two workflows.
                key: |
                    bazel-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('.bazelversion', 'WORKSPACE', 'pnpm-lock.yaml', 'requirements_lock.txt', 'admin/patches/bazel/*.patch', 'admin/bazel/third_party/*.bazel') }}
                restore-keys: |
                    bazel-${{ runner.os }}-${{ runner.arch }}-

        # If we don't have an exact cache entry match then we need to fetch
        # repositories we'll need for our build. We also build `//:node_modules` which
        # will make sure all `package.json` dependencies are extracted, their lifecycle
        # methods have run, and they're in the right place in `bazel-bin`.
        #
        # From the [`actions/cache` documentation][1]:
        #
        # > Note: `cache-hit` will be set to `true` only when cache hit occurs for the
        # > exact `key` match. For a partial key match via `restore-keys` or a cache
        # > miss, it will be set to `false`.
        #
        # [1]: https://github.com/actions/cache/blob/main/restore/README.md
        - if: steps.cache.outputs.cache-hit != 'true'
          name: Fetch Bazel repositories
          shell: bash
          run: |
                admin/bin/bazel --bazelrc=admin/bazel/aspect_bazelrc/ci.bazelrc fetch //... --config=github-runner --remote_cache= --build_tests_only --test_tag_filters=-macos
                admin/bin/bazel --bazelrc=admin/bazel/aspect_bazelrc/ci.bazelrc build //:node_modules --config=github-runner --remote_cache=

        # Save our repository cache after we finish fetching but before we run our
        # ci job! The ordering here is important since we don't want to include any
        # build artifacts in the cache. Only fetched external repositories.
        #
        # We only save new cache entries on the `main` branch. So if you're iterating
        # on a PR we don't save a bunch of cache entries that'll never be used again.
        - if: steps.cache.outputs.cache-hit != 'true' && github.ref == 'refs/heads/main'
          name: Save Bazel repositories cache
          uses: actions/cache/save@v3
          with:
                path: |
                    ~/.cache/bazelisk
                    ~/.cache/bazel
                key: ${{ steps.cache.outputs.cache-primary-key }}

        # This starts the Bazel remote cache proxy server. We store [Bazel remote
        # cache][1] files in AWS S3. The AWS S3 API is mostly compatible with what
        # Bazel remote caching expects (`PUT` request to write file, `GET` request to
        # read file) but Bazel can't sign requests for AWS S3.
        #
        # So we have a small Node.js proxy server that signs requests from Bazel with
        # the IAM role of our GitHub runner in AWS and forwards the request to S3.
        # Since the server runs before we can build anything with Bazel it uses the
        # Node.js version provided by the Ubuntu package manager
        # (`apt-get install nodejs`, which is Node.js v12) without any third party
        # dependencies from our `package.json`.
        #
        # ## Debugging cache misses
        #
        # If you're seeing tests re-execute across builds that you wouldn't expect
        # would need to re-execute based on the files that changed follow the guide
        # “[Debugging Remote Cache Hits for Remote Execution][2].”
        #
        # You can simulate a remote cache locally with the [`buchgr/bazel-remote`][3]
        # project to reproduce the cache miss.
        #
        # I (@calebmer) had to debug cache misses for the test
        # `//server/forum/realtime:realtime_tests_typecheck_test`. To do this, I
        # created two `cyberworlds` checkouts on my machine (in `a/cyberworlds` and
        # `b/cyberworlds`) and ran the following commands adapted from the [Bazel
        # remote cache hit debugging guide][2] (replace `$LOCAL` with some directory
        # on your machine to write the logs):
        #
        # ```sh
        # cd a/cyberworlds && \
        #     bazel clean && \
        #     bazel \
        #         --bazelrc=admin/bazel/aspect_bazelrc/ci.bazelrc \
        #         test //server/forum/realtime:realtime_tests_typecheck_test \
        #         --show_progress_rate_limit=0.2 \
        #         --remote_cache=http://localhost:8080
        #
        # cd a/cyberworlds && \
        #     bazel clean &&
        #     bazel \
        #         --bazelrc=admin/bazel/aspect_bazelrc/ci.bazelrc \
        #         test //server/forum/realtime:realtime_tests_typecheck_test \
        #         --show_progress_rate_limit=0.2 \
        #         --remote_cache=http://localhost:8080 \
        #         --execution_log_binary_file=$LOCAL/a.log \
        #         --noremote_upload_local_results
        #
        # cd b/cyberworlds && \
        #     bazel clean &&
        #     bazel \
        #         --bazelrc=admin/bazel/aspect_bazelrc/ci.bazelrc \
        #         test //server/forum/realtime:realtime_tests_typecheck_test \
        #         --show_progress_rate_limit=0.2 \
        #         --remote_cache=http://localhost:8080 \
        #         --execution_log_binary_file=$LOCAL/b.log \
        #         --noremote_upload_local_results
        # ```
        #
        # This uses a similar configuration to CI. Once you have a local reproduction
        # of the miss and have execution log files you can continue following the steps
        # in Bazel's debugging guide.
        #
        # [1]: https://bazel.build/remote/caching
        # [2]: https://bazel.build/remote/cache-remote
        # [3]: https://github.com/buchgr/bazel-remote
        - name: Start Bazel remote cache
          shell: bash
          run: |
                admin/aws/internal/aws_github_runners_bazel_remote_cache.sh
