load("//admin/typescript:typescript.bzl", "ts_project")

ts_project(
    name = "web_socket",
    visibility = ["//server:__subpackages__"],
    deps = [
        "//server/helpers",
        "//server/tracer",
        "//shared/context",
        "//shared/error",
        "//shared/helpers",
        "//shared/id",
        "//shared/rpc",
        "//shared/schema",
        "//shared/tracer",
        "//shared/web_socket",
    ],
)
