filegroup(
    name = "patches",
    srcs = glob(["*.patch"]),
    visibility = [
        "//:__pkg__",
        "//admin/open_source:__pkg__",
    ],
)

filegroup(
    name = "open_source_patch_source_configuration_inputs",
    srcs = ["BUILD"],
    visibility = ["//admin/open_source:__pkg__"],
)
