import {
    DocumentContentProsemirrorSchema,
    assertDocumentContent,
} from "~/shared/documents/document_content_schema.js";
import {Lazy} from "~/shared/helpers/control/lazy.open_source.js";

const schema = DocumentContentProsemirrorSchema;

/**
 * Part of the YouTube Wikipedia article:
 * https://en.wikipedia.org/wiki?curid=3524766
 *
 * Most viewed Wikipedia article according to:
 * https://huggingface.co/datasets/Cohere/wikipedia-22-12
 */
export const wikipediaYoutubeDocumentContent = new Lazy(() =>
    assertDocumentContent(
        schema.node("doc", {}, [
            schema.node("title", {}, [schema.text("YouTube")]),
            schema.node("paragraph", {}, [
                schema.text(
                    "YouTube is an American online video sharing and social media platform headquartered in San Bruno, California, United States. Accessible worldwide, it was launched on February 14, 2005, by Steve Chen, Chad Hurley, and Jawed Karim. It is owned by Google and is the second most visited website in the world, after Google Search. YouTube has more than 2.5 billion monthly users, who collectively watch more than one billion hours of videos every day. As of May 2019, videos were being uploaded to the platform at a rate of more than 500 hours of content per minute.",
                ),
            ]),
            schema.node("paragraph", {}, [
                schema.text(
                    "In October 2006, YouTube was bought by Google for $1.65 billion. Google\u2019s ownership of YouTube expanded the site\u2019s business model, expanding from generating revenue from advertisements alone to offering paid content such as movies and exclusive content produced by YouTube. It also offers YouTube Premium, a paid subscription option for watching content without ads. YouTube also approved creators to participate in Google\u2019s AdSense program, which seeks to generate more revenue for both parties. In 2021, YouTube\u2019s annual advertising revenue increased to $28.8 billion, an increase in revenue of $9 billion from the previous year. YouTube reported revenue of $29.2 billion in 2022.",
                ),
            ]),
            schema.node("paragraph", {}, [
                schema.text(
                    "Since its purchase by Google, YouTube has expanded beyond the core website into mobile apps, network television, and the ability to link with other platforms. Video categories on YouTube include music videos, video clips, news, short films, feature films, songs, documentaries, movie trailers, teasers, live streams, vlogs, and more. Most content is generated by individuals, including collaborations between YouTubers and corporate sponsors. Established media corporations such as Disney, Paramount, NBCUniversal, and Warner Bros. Discovery have also created and expanded their corporate YouTube channels to advertise to a greater audience.",
                ),
            ]),
            schema.node("paragraph", {}, [
                schema.text(
                    "YouTube has had unprecedented social impact, influencing popular culture, internet trends, and creating multimillionaire celebrities. Despite its growth and success, it has been widely criticized for allegedly facilitating the spread of misinformation, the sharing of copyrighted content, routinely violating its users\u2019 privacy, enabling censorship, endangering child safety and wellbeing, and for its inconsistent or incorrect implementation of platform guidelines.",
                ),
            ]),
            schema.node("heading", {level: 1}, [schema.text("History")]),
            schema.node("paragraph", {}, [
                schema.text(
                    "YouTube was founded by Steve Chen, Chad Hurley, and Jawed Karim. The trio were early employees of PayPal, which left them enriched after the company was bought by eBay. Hurley had studied design at the Indiana University of Pennsylvania, and Chen and Karim studied computer science together at the University of Illinois Urbana-Champaign.",
                ),
            ]),
            schema.node("paragraph", {}, [
                schema.text(
                    "According to a story that has often been repeated in the media, Hurley and Chen developed the idea for YouTube during the early months of 2005, after they had experienced difficulty sharing videos that had been shot at a dinner party at Chen\u2019s apartment in San Francisco. Karim did not attend the party and denied that it had occurred, but Chen remarked that the idea that YouTube was founded after a dinner party \u201Cwas probably very strengthened by marketing ideas around creating a story that was very digestible\u201D.",
                ),
            ]),
            schema.node("paragraph", {}, [
                schema.text(
                    "YouTube began as a venture capital–funded technology startup. Between November 2005 and April 2006, the company raised money from various investors, with Sequoia Capital and Artis Capital Management being the largest two. YouTube\u2019s early headquarters were situated above a pizzeria and a Japanese restaurant in San Mateo, California. In February 2005, the company activated www.youtube.com. The first video was uploaded on April 23, 2005. Titled \u201CMe at the zoo\u201D, it shows co-founder Jawed Karim at the San Diego Zoo and can still be viewed on the site. In May, the company launched a public beta and by November, a Nike ad featuring Ronaldinho became the first video to reach one million total views. The site launched officially on December 15, 2005, by which time the site was receiving 8 million views a day. Clips at the time were limited to 100 megabytes, as little as 30 seconds of footage.",
                ),
            ]),
            schema.node("paragraph", {}, [
                schema.text(
                    "YouTube was not the first video-sharing site on the Internet; Vimeo was launched in November 2004, though that site remained a side project of its developers from CollegeHumor. The week of YouTube\u2019s launch, NBC-Universal\u2019s Saturday Night Live ran a skit \u201DLazy Sunday\u201D by The Lonely Island. Besides helping to bolster ratings and long-term viewership for Saturday Night Live, \u201DLazy Sunday\u201D\u2019s status as an early viral video helped establish YouTube as an important website. Unofficial uploads of the skit to YouTube drew in more than five million collective views by February 2006 before they were removed when NBCUniversal requested it two months later based on copyright concerns. Despite eventually being taken down, these duplicate uploads of the skit helped popularize YouTube\u2019s reach and led to the upload of more third-party content. The site grew rapidly; in July 2006, the company announced that more than 65,000 new videos were being uploaded every day and that the site was receiving 100 million video views per day.",
                ),
            ]),
            schema.node("paragraph", {}, [
                schema.text(
                    "The choice of the name www.youtube.com led to problems for a similarly named website, www.utube.com. That site\u2019s owner, Universal Tube & Rollform Equipment, filed a lawsuit against YouTube in November 2006 after being regularly overloaded by people looking for YouTube. Universal Tube subsequently changed its website to www.utubeonline.com.",
                ),
            ]),
        ]),
    ),
);
