load("//admin/typescript:typescript.bzl", "ts_project")

ts_project(
    name = "emails",
    visibility = ["//visibility:public"],
    deps = [
        "//:node_modules/@types/node",
        "//shared/helpers",
    ],
)
