load("//admin/typescript:typescript.bzl", "ts_project")

ts_project(
    name = "files",
    visibility = ["//visibility:public"],
    deps = [
        "//:node_modules/@types/whatwg-mimetype",
        "//:node_modules/whatwg-mimetype",
        "//shared/error",
        "//shared/helpers",
        "//shared/id",
        "//shared/lezer",
        "//shared/schema",
    ],
)
