load("//admin/typescript:typescript.bzl", "ts_project")

ts_project(
    name = "spell_check",
    visibility = ["//visibility:public"],
    deps = [
        "//shared/error",
        "//shared/helpers",
        "//shared/id",
        "//shared/schema",
    ],
)
