export type EdgeServiceEnv = {
    AppStaticBucket: R2Bucket;
    FilesBucket: R2Bucket;
    AvatarsBucket: R2Bucket;
    DocumentCollaborationDurableObjectNamespace: DurableObjectNamespace;
    PostRealtimeDurableObjectNamespace: DurableObjectNamespace;
    ChannelRealtimeDurableObjectNamespace: DurableObjectNamespace;
    ChatRealtimeDurableObjectNamespace: DurableObjectNamespace;
    MyAccountDurableObjectNamespace: DurableObjectNamespace;
    TaskNotesCollaborationDurableObjectNamespace: DurableObjectNamespace;
    COOKIE_NAME_SUFFIX: string;
    APP_SERVICE_PUBLIC_KEY?: string;
    EDGE_SERVICE_FAMILY_PUBLIC_KEY?: string;
    TASK_REALTIME_SERVICE_PUBLIC_KEY?: string;
    JOB_QUEUE_SERVICE_PUBLIC_KEY?: string;
    FILE_PROCESSOR_SERVICE_PUBLIC_KEY?: string;
    API_SERVICE_PUBLIC_KEY?: string;
    RESOURCE_SERVICE_PUBLIC_KEY?: string;
    EDGE_SERVICE_FAMILY_PRIVATE_KEY?: string;
    TOKEN_AGENT_SECRET?: string;
    FILE_PROCESSOR_SERVICE_URL?: string;
    HONEYCOMB_API_KEY?: string;
    KINESIS_TRACER_STREAM_NAME?: string;
    KINESIS_AWS_ACCESS_KEY_ID?: string;
    KINESIS_AWS_SECRET_ACCESS_KEY?: string;
};
