# We call this Cloudflare Worker `edge-service` to ease a future migration
# where the edge service family is split up into different Cloudflare Workers.
# This service will keep just the edge service piece and we'll create new
# Cloudflare Workers.
name = "edge-service"
main = "edge_service_bundle.js"
no_bundle = true
compatibility_date = "2022-07-12"
compatibility_flags = ["streams_enable_constructors"]
workers_dev = false

[vars]
COOKIE_NAME_SUFFIX = ""

[route]
pattern = "alpine.inc/*"
zone_name = "alpine.inc"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
destinations = ["honeycomb-logs"]
head_sampling_rate = 1

[observability.traces]
enabled = true
destinations = ["honeycomb-traces"]
head_sampling_rate = 1

[[r2_buckets]]
binding = "AppStaticBucket"
bucket_name = "cyberworlds-app-static"

[[r2_buckets]]
binding = "FilesBucket"
bucket_name = "cyberworlds-files"

[[r2_buckets]]
binding = "AvatarsBucket"
bucket_name = "cyberworlds-avatars"

# We deploy our durable objects with our edge service but we think of our
# durable objects as logically different services. We could choose in the
# future to deploy them as separate Cloudflare Workers.
#
# We refer to the Cloudflare Worker which proxies our `AppService` as
# `EdgeService`. We refer to the broader collection of services owned by
# `EdgeService` as `EdgeServiceFamily`.

[[durable_objects.bindings]]
name = "DocumentCollaborationDurableObjectNamespace"
class_name = "DocumentCollaborationDurableObject"

[[durable_objects.bindings]]
name = "PostRealtimeDurableObjectNamespace"
class_name = "PostRealtimeDurableObject"

[[durable_objects.bindings]]
name = "ChatRealtimeDurableObjectNamespace"
class_name = "ChatRealtimeDurableObject"

[[durable_objects.bindings]]
name = "MyAccountDurableObjectNamespace"
class_name = "MyAccountDurableObject"

[[durable_objects.bindings]]
name = "TaskNotesCollaborationDurableObjectNamespace"
class_name = "TaskNotesCollaborationDurableObject"

[[durable_objects.bindings]]
name = "ChannelRealtimeDurableObjectNamespace"
class_name = "ChannelRealtimeDurableObject"

[[migrations]]
tag = "v1"
new_classes = ["DocumentCollaborationDurableObject"]

[[migrations]]
tag = "v2"
new_classes = ["PostRealtimeDurableObject"]

[[migrations]]
tag = "v3"
new_classes = ["ChatRealtimeDurableObject"]

[[migrations]]
tag = "v4"
new_classes = ["MyAccountDurableObject"]

[[migrations]]
tag = "v5"
new_classes = ["TaskNotesCollaborationDurableObject"]

[[migrations]]
tag = "v6"
new_classes = ["ChannelRealtimeDurableObject"]
