load("//admin/typescript:typescript.bzl", "ts_project")

ts_project(
    name = "remix",
    visibility = ["//visibility:public"],
    deps = [
        "//shared/helpers",
        "//shared/schema",
    ],
)
