import assert from "node:assert/strict";
import {readFile, writeFile} from "node:fs/promises";
import {basename, dirname, join, resolve} from "node:path";
import {fileURLToPath} from "node:url";

const repositoryPath = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const outputPaths = parseOutputPaths();
const rootPackage = JSON.parse(await readFile(join(repositoryPath, "package.json"), "utf8"));
const publicRootPackage = JSON.parse(
    await readFile(join(repositoryPath, "package.open_source.json"), "utf8"),
);
const cliPackage = JSON.parse(
    await readFile(join(repositoryPath, "packages/cli/package.open_source.json"), "utf8"),
);
const packageLock = JSON.parse(
    await readFile(join(repositoryPath, "package-lock.open_source.json"), "utf8"),
);

const patchEntries = findCliPatchEntries();
const patchList =
    [
        "# @generated by //admin/open_source:write_open_source_cli_patch_list",
        "",
        ...patchEntries.flatMap(({packageName, sourceFileName, version}) => [
            `- packageName: ${JSON.stringify(packageName)}`,
            `  sourceFileName: ${JSON.stringify(sourceFileName)}`,
            `  version: ${JSON.stringify(version)}`,
        ]),
    ].join("\n") + "\n";
publicRootPackage.overrides = Object.fromEntries(
    patchEntries.map(({packageName, patchedVersion}) => [packageName, patchedVersion]),
);

await writeFile(outputPaths.patchList, patchList);
await writeFile(outputPaths.publicPackage, `${JSON.stringify(publicRootPackage, undefined, 4)}\n`);

function parseOutputPaths() {
    const argumentValues = new Map();
    for (let argumentIndex = 2; argumentIndex < process.argv.length; argumentIndex += 2) {
        const name = process.argv[argumentIndex];
        const value = process.argv[argumentIndex + 1];
        assert.ok(name?.startsWith("--") && value, "Expected named output paths.");
        assert.ok(!argumentValues.has(name), `Received ${name} more than once.`);
        argumentValues.set(name, value);
    }
    assert.equal(argumentValues.size, 2, "Expected exactly two output paths.");

    return {
        patchList: requiredArgument(argumentValues, "--patch-list-output"),
        publicPackage: requiredArgument(argumentValues, "--public-package-output"),
    };
}

function requiredArgument(argumentValues, name) {
    const value = argumentValues.get(name);
    assert.ok(value, `Expected ${name}.`);
    return value;
}

function findCliPatchEntries() {
    // The public CLI needs patches for both its runtime and build dependencies. Walk
    // the lockfile rather than the private dependency tree so the list cannot include
    // a package absent from the published repository.
    const packagePaths = new Set();
    for (const packageName of Object.keys({
        ...cliPackage.dependencies,
        ...cliPackage.devDependencies,
    })) {
        const packagePath = resolveDependencyPackagePath({
            packageName,
            parentPackagePath: "packages/cli",
        });
        assert.ok(packagePath, `Public lockfile is missing ${packageName} for the CLI.`);
        collectDependencyPackagePaths({packagePath, packagePaths});
    }

    return [...packagePaths]
        .flatMap(packagePath => {
            const packageData = packageLock.packages[packagePath];
            const packageName = packageNameForPackagePath(packagePath);
            const rootPatch = findRootPatch({
                packageName,
                packageVersion: packageData.version,
            });
            if (!rootPatch) return [];
            return [
                {
                    packageName,
                    patchedVersion: rootPatch.version,
                    sourceFileName: basename(rootPatch.sourcePath),
                    version: rootPatch.version,
                },
            ];
        })
        .sort((left, right) => left.packageName.localeCompare(right.packageName));
}

function findRootPatch({packageName, packageVersion}) {
    const matchingPatchEntries = Object.entries(rootPackage.pnpm.patchedDependencies).filter(
        ([patchedPackageVersion]) =>
            packageNameForPatchedDependency(patchedPackageVersion) === packageName,
    );
    if (matchingPatchEntries.length === 0) return undefined;

    const exactPatchEntry = matchingPatchEntries.find(
        ([patchedPackageVersion]) => patchedPackageVersion === `${packageName}@${packageVersion}`,
    );
    if (exactPatchEntry) return rootPatchForEntry(exactPatchEntry);

    // The existing public lockfile may resolve a different patch version than private
    // pnpm. If exactly one private patch has the same major version, pin that version
    // in the generated public package so the next lockfile generation resolves it
    // before patch-package runs.
    const compatiblePatchEntries = matchingPatchEntries.filter(([patchedPackageVersion]) => {
        const patchedVersion = patchedPackageVersion.slice(
            patchedPackageVersion.lastIndexOf("@") + 1,
        );
        return patchedVersion.split(".")[0] === packageVersion.split(".")[0];
    });
    if (compatiblePatchEntries.length === 0) return undefined;
    assert.equal(
        compatiblePatchEntries.length,
        1,
        `The public CLI resolves ${packageName}@${packageVersion}, but multiple patches exist for ${packageName}.`,
    );
    return rootPatchForEntry(compatiblePatchEntries[0]);
}

function rootPatchForEntry([patchedPackageVersion, sourcePath]) {
    return {
        sourcePath,
        version: patchedPackageVersion.slice(patchedPackageVersion.lastIndexOf("@") + 1),
    };
}

function packageNameForPatchedDependency(patchedPackageVersion) {
    return patchedPackageVersion.slice(0, patchedPackageVersion.lastIndexOf("@"));
}

function packageNameForPackagePath(packagePath) {
    const pathParts = packagePath.split("/");
    const nodeModulesIndex = pathParts.lastIndexOf("node_modules");
    const packageName = pathParts[nodeModulesIndex + 1];
    assert.ok(packageName, `Expected an npm package path, received ${packagePath}.`);
    return packageName.startsWith("@")
        ? `${packageName}/${pathParts[nodeModulesIndex + 2]}`
        : packageName;
}

function collectDependencyPackagePaths({packagePath, packagePaths}) {
    if (packagePaths.has(packagePath)) return;
    packagePaths.add(packagePath);

    const packageData = packageLock.packages[packagePath];
    for (const packageName of Object.keys({
        ...packageData.dependencies,
        ...packageData.optionalDependencies,
    })) {
        const dependencyPackagePath = resolveDependencyPackagePath({
            packageName,
            parentPackagePath: packagePath,
        });
        if (dependencyPackagePath)
            collectDependencyPackagePaths({
                packagePath: dependencyPackagePath,
                packagePaths,
            });
    }
}

function resolveDependencyPackagePath({packageName, parentPackagePath}) {
    const hoistedPackagePath = join("node_modules", packageName);
    if (packageLock.packages[hoistedPackagePath]) return hoistedPackagePath;

    for (
        let ancestorPackagePath = parentPackagePath;
        ;
        ancestorPackagePath = dirname(ancestorPackagePath)
    ) {
        const nestedPackagePath = join(ancestorPackagePath, "node_modules", packageName);
        if (packageLock.packages[nestedPackagePath]) return nestedPackagePath;

        if (basename(ancestorPackagePath) === "node_modules") {
            const hoistedPackagePath = join(ancestorPackagePath, packageName);
            if (packageLock.packages[hoistedPackagePath]) return hoistedPackagePath;
        }
        if (ancestorPackagePath === ".") return undefined;
    }
}
