load("//admin/typescript:typescript.bzl", "ts_project")

ts_project(
    name = "error",
    visibility = ["//server/files/processor:__subpackages__"],
    deps = [
        "//shared/files",
    ],
)
