import fs from "fs/promises";
import Mustache from "mustache";
import openapiTypescript, {astToString} from "openapi-typescript";
import {join as joinPath} from "path";
import prettier from "prettier";
import ts from "typescript";
import {runfilesPath} from "~/server/helpers/node/runfiles_path.js";
import {contentCodeBlockLanguageIds} from "~/shared/content/content_code_block_language_id.js";
import {runAllPromises} from "~/shared/helpers/async/run_all_promises.js";
import {assert} from "~/shared/helpers/control/assert.js";
import {hasOwnProperty} from "~/shared/helpers/object/has_own_property.js";
import {quote} from "~/shared/helpers/string/quote.js";
import {idRegExp} from "~/shared/id/id_reg_exp.js";

async function main() {
    /* ========================================================================== *\
     *                       Render YAML Mustache template                        *
    \* ========================================================================== */

    const specificationContent = await fs.readFile(
        joinPath(runfilesPath, "cyberworlds/server/api/specification/api_specification.yaml"),
        "utf8",
    );

    let specificationFinalContent = Mustache.render(
        specificationContent,
        {
            idRegExp: idRegExp.source,
            codeBlockLanguageIds: JSON.stringify(contentCodeBlockLanguageIds),
        },
        undefined,
        {escape: string => string},
    );

    specificationFinalContent = specificationFinalContent.replace(/^ *#[^\n]*\n+/gm, "");

    specificationFinalContent =
        "# @generated by //server/api/specification:write_specification\n\n" +
        specificationFinalContent;

    /* ========================================================================== *\
     *                         Generate TypeScript types                          *
    \* ========================================================================== */

    const supportedIdTypes = [
        "AccountId",
        "BotWebhookEventId",
        "ChatId",
        "DocumentId",
        "DocumentThreadId",
        "PostId",
        "SpaceId",
        "TaskId",
    ];

    const supportedIdTypeByMetadataPath = new Map(
        supportedIdTypes.map(idType => [`#/components/schemas/${idType}`, idType]),
    );

    function createTsIdType(name: string) {
        return ts.factory.createTypeReferenceNode(
            ts.factory.createQualifiedName(ts.factory.createIdentifier("IdTypes"), name),
        );
    }

    const specificationTypesAst = await openapiTypescript(specificationFinalContent, {
        immutable: true,
        transform: (schema, options) => {
            if (schema.format === "date-time") {
                return ts.factory.createTypeReferenceNode(
                    ts.factory.createIdentifier("DateString"),
                );
            }

            const supportedIdType = options.path
                ? supportedIdTypeByMetadataPath.get(options.path)
                : undefined;

            if (supportedIdType !== undefined) {
                assert(
                    schema.type === "string" &&
                        hasOwnProperty(schema, "pattern") &&
                        schema.pattern === `^${idRegExp.source}$`,
                    quote`Expected ${options.path} to have a string schema with \`pattern\` of \`^{{idRegExp}}$\``,
                );

                if (supportedIdType === "DocumentThreadId") {
                    return createTsIdType("DocumentCommentThreadId");
                } else {
                    return createTsIdType(supportedIdType);
                }
            }

            for (const [pathName, pathPrefix, idType] of [
                ["AccountPath", "/accounts/", "AccountId"],
                ["ChannelPath", "/channels/", "ChannelId"],
                ["ChatPath", "/chats/", "ChatId"],
                ["DocumentPath", "/documents/", "DocumentId"],
                ["PostPath", "/posts/", "PostId"],
                ["TaskPath", "/tasks/", "TaskId"],
                ["TaskCollectionPath", "/task-collections/", "TaskCollectionId"],
            ] as const) {
                if (options.path === `#/components/schemas/${pathName}`) {
                    return ts.factory.createTemplateLiteralType(
                        ts.factory.createTemplateHead(pathPrefix),
                        [
                            ts.factory.createTemplateLiteralTypeSpan(
                                createTsIdType(idType),
                                ts.factory.createTemplateTail(""),
                            ),
                        ],
                    );
                }
            }

            if (options.path === "#/components/schemas/DocumentThreadPath") {
                return ts.factory.createTemplateLiteralType(
                    ts.factory.createTemplateHead("/documents/"),
                    [
                        ts.factory.createTemplateLiteralTypeSpan(
                            createTsIdType("DocumentId"),
                            ts.factory.createTemplateMiddle("/threads/"),
                        ),
                        ts.factory.createTemplateLiteralTypeSpan(
                            createTsIdType("DocumentCommentThreadId"),
                            ts.factory.createTemplateTail(""),
                        ),
                    ],
                );
            }
        },
    });

    let specificationTypesContent = astToString(specificationTypesAst);

    specificationTypesContent =
        // eslint-disable-next-line string-quotes
        '// @generated by //server/api/specification:write_specification\n/* eslint-disable @typescript-eslint/array-type */\n\nimport type {DateString} from "~/shared/helpers/date/date_string.js";\nimport type * as IdTypes from "~/shared/id/types/id_types.js";\n\nexport namespace ApiSpecification {' +
        specificationTypesContent +
        "}\n";

    const prettierConfig = await prettier.resolveConfig(joinPath(runfilesPath, "cyberworlds"));

    specificationTypesContent = prettier.format(specificationTypesContent, {
        ...prettierConfig,
        parser: "typescript",
    });

    /* ========================================================================== *\
     *                                Write files                                 *
    \* ========================================================================== */

    await runAllPromises([
        fs.writeFile(
            "server/api/specification/api_specification_final_generated.yaml",
            specificationFinalContent,
        ),
        fs.writeFile(
            "server/api/specification/types/api_specification_types_generated.ts",
            specificationTypesContent,
        ),
    ]);
}

main().catch(error => {
    // eslint-disable-next-line no-console
    console.error(error);
    process.exitCode = 1;
});
