name = "resource-service"
main = "resource_service_bundle.js"
no_bundle = true
compatibility_date = "2022-07-12"
workers_dev = false

[route]
pattern = "resources.alpine.inc"
custom_domain = true

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
destinations = [ "honeycomb-logs" ]
head_sampling_rate = 1

[[r2_buckets]]
binding = "AvatarsBucket"
bucket_name = "cyberworlds-avatars"

[[r2_buckets]]
binding = "AppStaticBucket"
bucket_name = "cyberworlds-app-static"

[[r2_buckets]]
binding = "FilesBucket"
bucket_name = "cyberworlds-files"

[vars]
CORS_TRUSTED_ORIGINS = ["https://alpine.inc"]
