import {collab, getVersion, receiveTransaction, sendableSteps} from "prosemirror-collab";
import {history} from "prosemirror-history";
import {Node} from "prosemirror-model";
import {EditorState, Plugin, PluginKey, Selection, Transaction} from "prosemirror-state";
import {Step} from "prosemirror-transform";
import {
    ContentEditorFloaterState,
    initialContentEditorFloaterState,
} from "~/client/content/internal/content_editor_floater";
import {buildInputRulesPlugin} from "~/client/content/internal/content_editor_plugin_input_rules";
import {
    buildKeymapPlugin,
    openKeyboardHighlightFloaterMetaKey,
    openKeyboardLinkFloaterMetaKey,
} from "~/client/content/internal/content_editor_plugin_keymap";
import {trimSpacesFromRange} from "~/client/content/internal/content_editor_prosemirror_helpers";
import {ContentProsemirrorSchema} from "~/shared/content/content_schema";
import {assert} from "~/shared/helpers/control/assert";
import {assertExists} from "~/shared/helpers/control/assert_exists";
import {generateId, isId} from "~/shared/id/id";
import {ContentEditorClientId} from "~/shared/id/types/id_types";

function buildPlugins(schema: ContentProsemirrorSchema) {
    return [
        history(),
        buildInputRulesPlugin(schema),
        buildKeymapPlugin(schema),
        contentEditorFloaterStatePlugin(),
    ];
}

/**
 * Represents the entire state of our `<ContentEditor>` component.
 *
 * We have a wrapper to require the user of certain plugins.
 *
 * Wraps around ProseMirror's own `EditorState` and provides a controlled
 * interface to the outside world.
 */
export class ContentEditorState<Content extends Node> {
    /**
     * Creates a new state for our content editor.
     */
    public static create<Content extends Node>(
        content: Content,
        {selectionAt = "start"}: {selectionAt?: "start" | "end"} = {},
    ): ContentEditorState<Content> {
        assert(content.type.schema.topNodeType === content.type);

        const plugins = buildPlugins(content.type.schema);

        return new ContentEditorState(
            EditorState.create({
                doc: content,
                plugins,
                selection:
                    selectionAt === "end" ? Selection.atEnd(content) : Selection.atStart(content),
            }),
        );
    }

    /**
     * Creates a new collaborative state for our content editor.
     */
    public static createCollaborative<Content extends Node>({
        version,
        content,
        selectionAt,
    }: {
        /**
         * The content version for collaborative editing.
         */
        version: number;

        /**
         * The initial content in the editor. If no content is provided then we
         * start with empty content.
         */
        content: Content;

        /**
         * Where to put the selection at in the editor.
         */
        selectionAt?: "start" | "end";
    }): ContentEditorState<Content> {
        assert(content.type.schema.topNodeType === content.type);

        const plugins = [
            ...buildPlugins(content.type.schema),
            collab({
                // Every client gets its own ID generated by the client. If a bad actor
                // client impersonates another, known, client they can cause some annoying bugs
                // but that's about it.
                //
                // The ID is necessary so the client knows when it is confirming steps it
                // generated vs. receiving steps from another client. We generate an ID for
                // every content state instance because if you have two content editors on the
                // page they need separate IDs so they don't conflict.
                clientID: generateId(),
                version,
            }),
        ];

        const state = new ContentEditorState<Content>(
            EditorState.create({
                doc: content,
                plugins,
                selection:
                    selectionAt === "end" ? Selection.atEnd(content) : Selection.atStart(content),
            }),
        );

        assert(state.isCollaborative());
        return state;
    }

    private readonly _state: EditorState;

    private constructor(state: EditorState) {
        this._state = state;
    }

    /**
     * The current content rendered in the editor.
     *
     * Our state contains more information than just the content. For instance,
     * the cursor position.
     */
    public getContent(): Content {
        return this._state.doc as Content;
    }

    /**
     * Get the current selection.
     */
    public getSelection(): Selection {
        return this._state.selection;
    }

    /**
     * Get the current floater state.
     */
    public getFloaterState(): ContentEditorFloaterState {
        return getContentEditorFloaterState(this._state);
    }

    /**
     * Is this content editor state collaborative?
     */
    public isCollaborative(): boolean {
        return isCollabPlugin(this._state.plugins[this._state.plugins.length - 1]!);
    }

    /**
     * Gets the ID we generated for this client when it was created.
     */
    public getClientId(): ContentEditorClientId {
        const collabPlugin = this._state.plugins[this._state.plugins.length - 1]!;
        assert(isCollabPlugin(collabPlugin));
        return collabPlugin.spec.config.clientID;
    }

    /**
     * Get the current version of our content for collaborative editing.
     *
     * May only call this method if the content editor state is collaborative.
     * (Can check with `isCollab()`.)
     */
    public getVersion(): number {
        assert(this.isCollaborative());
        return getVersion(this._state);
    }

    /**
     * Are there any unconfirmed local steps the server hasn't acknowledged?
     *
     * May only call this method if the content editor state is collaborative.
     * (Can check with `isCollab()`.)
     */
    public hasSendableSteps(): boolean {
        assert(this.isCollaborative());
        assert(collabPluginKey);
        return collabPluginKey.getState(this._state).unconfirmed.length > 0;
    }

    /**
     * Provides the unconfirmed steps for this content that we need to send to
     * a central authority.
     *
     * May only call this method if the content editor state is collaborative.
     * (Can check with `isCollab()`.)
     */
    public sendableSteps(): {
        version: number;
        steps: ReadonlyArray<Step>;
        origins: ReadonlyArray<Transaction>;
        clientId: ContentEditorClientId;
    } | null {
        assert(this.isCollaborative());

        const result = sendableSteps(this._state);
        if (!result) return null;

        assert(typeof result.clientID === "string" && isId(result.clientID));

        return {
            version: result.version,
            steps: result.steps,
            origins: result.origins,
            clientId: result.clientID as ContentEditorClientId,
        };
    }

    /**
     * Receive steps that originated from a `sendableSteps()` call.
     *
     * May only call this method if the content editor state is collaborative.
     * (Can check with `isCollab()`.)
     */
    public receiveSteps(
        steps: Iterable<{step: Step; clientId: ContentEditorClientId}>,
    ): ContentEditorState<Content> {
        assert(this.isCollaborative());

        const stepsWithoutClientId = [];
        const clientIds = [];

        for (const {step, clientId} of steps) {
            stepsWithoutClientId.push(step);
            clientIds.push(clientId);
        }

        const transaction = receiveTransaction(this._state, stepsWithoutClientId, clientIds, {
            // Users usually prefer this, but it isn't done by default for reasons
            // of backwards compatibility.
            mapSelectionBackward: true,
        });

        return new ContentEditorState(this._state.apply(transaction));
    }

    private _contentWithoutSendableSteps: Content | null = null;

    /**
     * Get the underlying content as if there are no unconfirmed steps.
     *
     * This is the content as the server currently sees it.
     */
    public getContentWithoutSendableSteps(): Content {
        assert(this.isCollaborative());

        if (!this._contentWithoutSendableSteps) {
            assert(collabPluginKey);
            const {unconfirmed} = collabPluginKey.getState(this._state);

            let content = this._state.doc;

            for (let i = unconfirmed.length - 1; i >= 0; i--) {
                const invertedStep: Step = unconfirmed[i].inverted;
                const stepResult = invertedStep.apply(content);
                assert(stepResult.doc);
                content = stepResult.doc;
            }

            this._contentWithoutSendableSteps = content as Content;
        }

        return this._contentWithoutSendableSteps;
    }
}

let collabPluginKey: PluginKey;

/**
 * Is the provided plugin a `prosemirror-collab` plugin?
 */
function isCollabPlugin(plugin: Plugin) {
    if (collabPluginKey === undefined) {
        const {key} = collab().spec;
        assert(key);
        collabPluginKey = key;
    }
    return plugin.spec.key === collabPluginKey;
}

const contentEditorFloaterStateKey = new PluginKey<ContentEditorFloaterState>(
    "contentEditorFloaterState",
);

function contentEditorFloaterStatePlugin() {
    return new Plugin<ContentEditorFloaterState>({
        key: contentEditorFloaterStateKey,
        state: {
            init: () => initialContentEditorFloaterState,
            apply: (transaction, floaterState, oldState, newState) => {
                const transactionFloaterState: ContentEditorFloaterState | undefined =
                    transaction.getMeta(contentEditorFloaterStateKey);
                if (transactionFloaterState) return transactionFloaterState;

                // Open our toolbars on the current selection when certain meta is set on
                // our transaction.
                if (transaction.getMeta(openKeyboardHighlightFloaterMetaKey)) {
                    return {
                        type: "KeyboardHighlight",
                        range: trimSpacesFromRange(newState.doc, newState.selection),
                    };
                }
                if (transaction.getMeta(openKeyboardLinkFloaterMetaKey)) {
                    return {
                        type: "KeyboardLink",
                        range: trimSpacesFromRange(newState.doc, newState.selection),
                    };
                }

                // `PointerToolbar` is the only state which does not record its range.
                if (floaterState.type === "PointerToolbar") return floaterState;

                const newRangeFrom = transaction.mapping.map(floaterState.range.from);
                const newRangeTo = transaction.mapping.map(floaterState.range.to);
                if (
                    floaterState.range.from === newRangeFrom &&
                    floaterState.range.to === newRangeTo
                ) {
                    return floaterState;
                }

                // If the range collapsed into a single position (maybe the content was
                // deleted?) reset to the initial state.
                if (newRangeFrom === newRangeTo) return initialContentEditorFloaterState;

                return {
                    ...floaterState,
                    range: {from: newRangeFrom, to: newRangeTo},
                };
            },
        },
    });
}

export function getContentEditorFloaterState(state: EditorState): ContentEditorFloaterState {
    return assertExists(contentEditorFloaterStateKey.getState(state));
}

export function setContentEditorFloaterState(
    transaction: Transaction,
    floaterState: ContentEditorFloaterState,
): Transaction {
    return transaction.setMeta(contentEditorFloaterStateKey, floaterState);
}
