import {collab, getVersion, receiveTransaction, sendableSteps} from "prosemirror-collab";
import {history} from "prosemirror-history";
import {Node} from "prosemirror-model";
import {EditorState, Plugin, PluginKey, TextSelection, Transaction} from "prosemirror-state";
import {Step} from "prosemirror-transform";
import {buildInputRulesPlugin} from "~/client/content/internal/content_editor_plugin_input_rules";
import {buildKeymapPlugin} from "~/client/content/internal/content_editor_plugin_keymap";
import {ContentProsemirrorSchema} from "~/shared/content/content_schema";
import {assert} from "~/shared/helpers/control/assert";
import {Id, generateId, isId} from "~/shared/id/id";

function buildPlugins(schema: ContentProsemirrorSchema) {
    return [history(), buildInputRulesPlugin(schema), buildKeymapPlugin(schema)];
}

/**
 * Represents the entire state of our `<ContentEditor>` component.
 *
 * We have a wrapper to require the user of certain plugins.
 *
 * Wraps around ProseMirror's own `EditorState` and provides a controlled
 * interface to the outside world.
 */
export class ContentEditorState<Content extends Node> {
    /**
     * Creates a new state for our content editor.
     */
    public static create<Content extends Node>(content: Content): ContentEditorState<Content> {
        assert(content.type.schema.topNodeType === content.type);

        const plugins = buildPlugins(content.type.schema);

        return new ContentEditorState(
            EditorState.create({
                doc: content,
                plugins,
            }),
        );
    }

    /**
     * Creates a new collaborative state for our content editor.
     */
    public static createCollab<Content extends Node>({
        version,
        content,
    }: {
        /**
         * The content version for collaborative editing.
         */
        version: number;

        /**
         * The initial content in the editor. If no content is provided then we
         * start with empty content.
         */
        content: Content;
    }): ContentEditorState<Content> {
        assert(content.type.schema.topNodeType === content.type);

        const plugins = [
            ...buildPlugins(content.type.schema),
            collab({
                // Every client gets its own ID generated by the client. If a bad actor
                // client impersonates another, known, client they can cause some annoying bugs
                // but that's about it.
                //
                // The ID is necessary so the client knows when it is confirming steps it
                // generated vs. receiving steps from another client. We generate an ID for
                // every content state instance because if you have two content editors on the
                // page they need separate IDs so they don't conflict.
                clientID: generateId(),
                version,
            }),
        ];

        const state = new ContentEditorState<Content>(
            EditorState.create({
                doc: content,
                plugins,
            }),
        );

        assert(state.isCollab());
        return state;
    }

    private readonly _state: EditorState;

    private constructor(state: EditorState) {
        this._state = state;
    }

    /**
     * The current content rendered in the editor.
     *
     * Our state contains more information than just the content. For instance,
     * the cursor position.
     */
    public getContent(): Content {
        return this._state.doc as Content;
    }

    /**
     * Get the current text selection if it exists.
     */
    public getTextSelection(): TextSelection | null {
        if (!(this._state.selection instanceof TextSelection)) return null;
        return this._state.selection;
    }

    /**
     * Is this content editor state collaborative?
     */
    public isCollab() {
        return isCollabPlugin(this._state.plugins[this._state.plugins.length - 1]!);
    }

    /**
     * Gets the ID we generated for this client when it was created.
     */
    public getClientId(): Id {
        const collabPlugin = this._state.plugins[this._state.plugins.length - 1]!;
        assert(isCollabPlugin(collabPlugin));
        return collabPlugin.spec.config.clientID;
    }

    /**
     * Get the current version of our content for collaborative editing.
     *
     * May only call this method if the content editor state is collaborative.
     * (Can check with `isCollab()`.)
     */
    public getVersion(): number {
        assert(this.isCollab());
        return getVersion(this._state);
    }

    /**
     * Are there any unconfirmed local steps the server hasn't acknowledged?
     *
     * May only call this method if the content editor state is collaborative.
     * (Can check with `isCollab()`.)
     */
    public hasSendableSteps(): boolean {
        assert(this.isCollab());
        assert(collabPluginKey);
        return collabPluginKey.getState(this._state).unconfirmed.length > 0;
    }

    /**
     * Provides the unconfirmed steps for this content that we need to send to
     * a central authority.
     *
     * May only call this method if the content editor state is collaborative.
     * (Can check with `isCollab()`.)
     */
    public sendableSteps(): {
        version: number;
        steps: ReadonlyArray<Step>;
        origins: ReadonlyArray<Transaction>;
        clientId: Id;
    } | null {
        assert(this.isCollab());

        const result = sendableSteps(this._state);
        if (!result) return null;

        assert(typeof result.clientID === "string" && isId(result.clientID));

        return {
            version: result.version,
            steps: result.steps,
            origins: result.origins,
            clientId: result.clientID,
        };
    }

    /**
     * Receive steps that originated from a `sendableSteps()` call.
     *
     * May only call this method if the content editor state is collaborative.
     * (Can check with `isCollab()`.)
     */
    public receiveSteps(steps: Iterable<{step: Step; clientId: Id}>): ContentEditorState<Content> {
        assert(this.isCollab());

        const stepsWithoutClientId = [];
        const clientIds = [];

        for (const {step, clientId} of steps) {
            stepsWithoutClientId.push(step);
            clientIds.push(clientId);
        }

        const transaction = receiveTransaction(this._state, stepsWithoutClientId, clientIds, {
            // Users usually prefer this, but it isn't done by default for reasons
            // of backwards compatibility.
            mapSelectionBackward: true,
        });

        return new ContentEditorState(this._state.apply(transaction));
    }

    /**
     * Get the underlying content as if there are no unconfirmed steps.
     *
     * This is the content as the server currently sees it.
     */
    public getContentWithoutSendableSteps(): Content {
        assert(this.isCollab());

        assert(collabPluginKey);
        const {unconfirmed} = collabPluginKey.getState(this._state);

        let content = this._state.doc;

        for (let i = unconfirmed.length - 1; i >= 0; i--) {
            const invertedStep: Step = unconfirmed[i].inverted;
            const stepResult = invertedStep.apply(content);
            assert(stepResult.doc);
            content = stepResult.doc;
        }

        return content as Content;
    }
}

let collabPluginKey: PluginKey;

/**
 * Is the provided plugin a `prosemirror-collab` plugin?
 */
function isCollabPlugin(plugin: Plugin) {
    if (collabPluginKey === undefined) {
        const {key} = collab().spec;
        assert(key);
        collabPluginKey = key;
    }
    return plugin.spec.key === collabPluginKey;
}
