load("//admin/typescript:typescript.bzl", "ts_project")

ts_project(
    name = "feed",
    visibility = ["//visibility:public"],
    deps = [
        "//shared/accounts",
        "//shared/content",
        "//shared/documents",
        "//shared/error",
        "//shared/forum",
        "//shared/id",
        "//shared/schema",
        "//shared/search",
        "//shared/tasks",
    ],
)
