name = "agent-service"
main = "agent_service_bundle.js"
no_bundle = true
compatibility_date = "2022-07-12"
compatibility_flags = ["streams_enable_constructors"]
workers_dev = true

[vars]
COOKIE_NAME_SUFFIX = ""

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
destinations = ["honeycomb-logs"]
head_sampling_rate = 1

[[durable_objects.bindings]]
name = "ChatGptAgentDurableObjectNamespace"
class_name = "ChatGptAgentDurableObject"

[[durable_objects.bindings]]
name = "MockAgentDurableObjectNamespace"
class_name = "MockAgentDurableObject"

[[migrations]]
tag = "v1"
new_classes = ["ChatGptAgentDurableObject"]

[[migrations]]
tag = "v2"
new_classes = ["MockAgentDurableObject"]

[[d1_databases]]
binding = "AgentUsageDatabase"
database_name = "agent-usage"
database_id = "c6cc146c-55f6-410a-a7d5-b1d6c6b55e68"
migrations_dir = "internal/d1/migrations"
