name = "agent-service"
main = "agent_service_bundle.js"
no_bundle = true
compatibility_date = "2022-07-12"
compatibility_flags = ["streams_enable_constructors"]
workers_dev = true

[observability]
enabled = true
head_sampling_rate = 1

[[durable_objects.bindings]]
name = "ChatGptAgentDurableObjectNamespace"
class_name = "ChatGptAgentDurableObject"

[[durable_objects.bindings]]
name = "MockAgentDurableObjectNamespace"
class_name = "MockAgentDurableObject"

[[migrations]]
tag = "v1"
new_classes = ["ChatGptAgentDurableObject"]

[[migrations]]
tag = "v2"
new_classes = ["MockAgentDurableObject"]

[[d1_databases]]
binding = "AgentUsageDatabase"
database_name = "agent-usage"
database_id = "agent-usage"
migrations_dir = "internal/d1/migrations"
