load("//admin/typescript:typescript.bzl", "ts_project")

ts_project(
    name = "test_helpers",
    testonly = True,
    visibility = ["//visibility:public"],
    deps = [
        "//shared/id",
        "//shared/spaces",
    ],
)
