name = "app"
main = "./build/server.js"
compatibility_date = "2022-07-12"
compatibility_flags = ["streams_enable_constructors"]
workers_dev = false

[route]
pattern = "cyberworlds.dev/*"
zone_name = "cyberworlds.dev"

[site]
bucket = "./public"

[[rules]]
type = "ESModule"
globs = ["**/*.js"]

[[durable_objects.bindings]]
name = "DocumentCollaborationDurableObjectNamespace"
class_name = "DocumentCollaborationDurableObject"

[[durable_objects.bindings]]
name = "PostRealtimeDurableObjectNamespace"
class_name = "PostRealtimeDurableObject"

[[durable_objects.bindings]]
name = "ChatRealtimeDurableObjectNamespace"
class_name = "ChatRealtimeDurableObject"

[[migrations]]
tag = "v1"
new_classes = ["DocumentCollaborationDurableObject"]

[[migrations]]
tag = "v2"
new_classes = ["PostRealtimeDurableObject"]

[[migrations]]
tag = "v3"
new_classes = ["ChatRealtimeDurableObject"]
