// @generated by //shared/api:write_specification
/* eslint-disable @typescript-eslint/array-type */

import type {DateString} from "~/shared/helpers/date/date_string.js";
import type * as IdTypes from "~/shared/id/types/id_types.js";

export namespace ApiSpecification {
    export interface paths {
        readonly "/accounts/{id}": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: components["schemas"]["AccountId"];
                };
                readonly cookie?: never;
            };
            readonly get: {
                readonly parameters: {
                    readonly query?: never;
                    readonly header?: never;
                    readonly path: {
                        readonly id: components["schemas"]["AccountId"];
                    };
                    readonly cookie?: never;
                };
                readonly requestBody?: never;
                readonly responses: {
                    readonly 200: {
                        headers: {
                            readonly [name: string]: unknown;
                        };
                        content: {
                            readonly "application/json": {
                                readonly account: components["schemas"]["AccountWithoutSpace"];
                            };
                        };
                    };
                    readonly default: components["responses"]["Error"];
                };
            };
            readonly put?: never;
            readonly post?: never;
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
        readonly "/spaces/{id}": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: components["schemas"]["SpaceId"];
                };
                readonly cookie?: never;
            };
            readonly get: {
                readonly parameters: {
                    readonly query?: never;
                    readonly header?: never;
                    readonly path: {
                        readonly id: components["schemas"]["SpaceId"];
                    };
                    readonly cookie?: never;
                };
                readonly requestBody?: never;
                readonly responses: {
                    readonly 200: {
                        headers: {
                            readonly [name: string]: unknown;
                        };
                        content: {
                            readonly "application/json": {
                                readonly space: components["schemas"]["Space"];
                            };
                        };
                    };
                    readonly default: components["responses"]["Error"];
                };
            };
            readonly put?: never;
            readonly post?: never;
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
        readonly "/spaces/{id}/accounts/{accountId}": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: components["schemas"]["SpaceId"];
                    readonly accountId: components["schemas"]["AccountId"];
                };
                readonly cookie?: never;
            };
            readonly get: {
                readonly parameters: {
                    readonly query?: never;
                    readonly header?: never;
                    readonly path: {
                        readonly id: components["schemas"]["SpaceId"];
                        readonly accountId: components["schemas"]["AccountId"];
                    };
                    readonly cookie?: never;
                };
                readonly requestBody?: never;
                readonly responses: {
                    readonly 200: {
                        headers: {
                            readonly [name: string]: unknown;
                        };
                        content: {
                            readonly "application/json": {
                                readonly account: components["schemas"]["Account"];
                            };
                        };
                    };
                    readonly default: components["responses"]["Error"];
                };
            };
            readonly put?: never;
            readonly post?: never;
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
        readonly "/chats/{id}": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: components["schemas"]["ChatId"];
                };
                readonly cookie?: never;
            };
            readonly get: {
                readonly parameters: {
                    readonly query?: never;
                    readonly header?: never;
                    readonly path: {
                        readonly id: components["schemas"]["ChatId"];
                    };
                    readonly cookie?: never;
                };
                readonly requestBody?: never;
                readonly responses: {
                    readonly 200: {
                        headers: {
                            readonly [name: string]: unknown;
                        };
                        content: {
                            readonly "application/json": {
                                readonly spaceId: components["schemas"]["SpaceId"];
                                readonly chat: components["schemas"]["Chat"];
                            };
                        };
                    };
                    readonly default: components["responses"]["Error"];
                };
            };
            readonly put?: never;
            readonly post?: never;
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
        readonly "/chats/{id}/messages/{index}": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: components["schemas"]["ChatId"];
                    readonly index: number;
                };
                readonly cookie?: never;
            };
            readonly get: {
                readonly parameters: {
                    readonly query?: never;
                    readonly header?: never;
                    readonly path: {
                        readonly id: components["schemas"]["ChatId"];
                        readonly index: number;
                    };
                    readonly cookie?: never;
                };
                readonly requestBody?: never;
                readonly responses: {
                    readonly 200: components["responses"]["GetMessage"];
                    readonly default: components["responses"]["Error"];
                };
            };
            readonly put?: never;
            readonly post?: never;
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
        readonly "/chats/{id}/messages": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: components["schemas"]["ChatId"];
                };
                readonly cookie?: never;
            };
            readonly get: {
                readonly parameters: {
                    readonly query?: {
                        readonly limit?: number;
                        readonly cursor?: number;
                        readonly from?: "start" | "end";
                    };
                    readonly header?: never;
                    readonly path: {
                        readonly id: components["schemas"]["ChatId"];
                    };
                    readonly cookie?: never;
                };
                readonly requestBody?: never;
                readonly responses: {
                    readonly 200: components["responses"]["GetMessages"];
                    readonly default: components["responses"]["Error"];
                };
            };
            readonly put?: never;
            readonly post: {
                readonly parameters: {
                    readonly query?: never;
                    readonly header?: never;
                    readonly path: {
                        readonly id: components["schemas"]["ChatId"];
                    };
                    readonly cookie?: never;
                };
                readonly requestBody: components["requestBodies"]["CreateMessage"];
                readonly responses: {
                    readonly 200: components["responses"]["GetMessage"];
                    readonly default: components["responses"]["Error"];
                };
            };
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
        readonly "/chats/{id}/messages/{index}/stream/completion": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: components["schemas"]["ChatId"];
                    readonly index: number;
                };
                readonly cookie?: never;
            };
            readonly get?: never;
            readonly put: {
                readonly parameters: {
                    readonly query?: never;
                    readonly header?: never;
                    readonly path: {
                        readonly id: components["schemas"]["ChatId"];
                        readonly index: number;
                    };
                    readonly cookie?: never;
                };
                readonly requestBody?: never;
                readonly responses: {
                    readonly 200: components["responses"]["GetMessageStreamCompletion"];
                    readonly default: components["responses"]["Error"];
                };
            };
            readonly post?: never;
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
        readonly "/chats/{id}/messages/{index}/stream/parts/{partIndex}": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: components["schemas"]["ChatId"];
                    readonly index: number;
                    readonly partIndex: number;
                };
                readonly cookie?: never;
            };
            readonly get?: never;
            readonly put: {
                readonly parameters: {
                    readonly query?: never;
                    readonly header?: never;
                    readonly path: {
                        readonly id: components["schemas"]["ChatId"];
                        readonly index: number;
                        readonly partIndex: number;
                    };
                    readonly cookie?: never;
                };
                readonly requestBody: components["requestBodies"]["PutMessageStreamPart"];
                readonly responses: {
                    readonly 200: components["responses"]["GetMessageStreamPart"];
                    readonly default: components["responses"]["Error"];
                };
            };
            readonly post?: never;
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
        readonly "/documents/{id}": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: components["schemas"]["DocumentId"];
                };
                readonly cookie?: never;
            };
            readonly get: {
                readonly parameters: {
                    readonly query?: never;
                    readonly header?: never;
                    readonly path: {
                        readonly id: components["schemas"]["DocumentId"];
                    };
                    readonly cookie?: never;
                };
                readonly requestBody?: never;
                readonly responses: {
                    readonly 200: {
                        headers: {
                            readonly [name: string]: unknown;
                        };
                        content: {
                            readonly "application/json": {
                                readonly spaceId: components["schemas"]["SpaceId"];
                                readonly document: components["schemas"]["Document"];
                            };
                        };
                    };
                    readonly default: components["responses"]["Error"];
                };
            };
            readonly put?: never;
            readonly post?: never;
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
        readonly "/documents/{id}/threads/{threadId}/messages/{index}": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: components["schemas"]["DocumentId"];
                    readonly threadId: components["schemas"]["DocumentThreadId"];
                    readonly index: number;
                };
                readonly cookie?: never;
            };
            readonly get: {
                readonly parameters: {
                    readonly query?: never;
                    readonly header?: never;
                    readonly path: {
                        readonly id: components["schemas"]["DocumentId"];
                        readonly threadId: components["schemas"]["DocumentThreadId"];
                        readonly index: number;
                    };
                    readonly cookie?: never;
                };
                readonly requestBody?: never;
                readonly responses: {
                    readonly 200: components["responses"]["GetMessage"];
                    readonly default: components["responses"]["Error"];
                };
            };
            readonly put?: never;
            readonly post?: never;
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
        readonly "/documents/{id}/threads/{threadId}/messages": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: components["schemas"]["DocumentId"];
                    readonly threadId: components["schemas"]["DocumentThreadId"];
                };
                readonly cookie?: never;
            };
            readonly get: {
                readonly parameters: {
                    readonly query?: {
                        readonly limit?: number;
                        readonly cursor?: number;
                        readonly from?: "start" | "end";
                    };
                    readonly header?: never;
                    readonly path: {
                        readonly id: components["schemas"]["DocumentId"];
                        readonly threadId: components["schemas"]["DocumentThreadId"];
                    };
                    readonly cookie?: never;
                };
                readonly requestBody?: never;
                readonly responses: {
                    readonly 200: components["responses"]["GetMessages"];
                    readonly default: components["responses"]["Error"];
                };
            };
            readonly put?: never;
            readonly post: {
                readonly parameters: {
                    readonly query?: never;
                    readonly header?: never;
                    readonly path: {
                        readonly id: components["schemas"]["DocumentId"];
                        readonly threadId: components["schemas"]["DocumentThreadId"];
                    };
                    readonly cookie?: never;
                };
                readonly requestBody: components["requestBodies"]["CreateMessage"];
                readonly responses: {
                    readonly 200: components["responses"]["GetMessage"];
                    readonly default: components["responses"]["Error"];
                };
            };
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
        readonly "/documents/{id}/threads/{threadId}/messages/{index}/stream/completion": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: components["schemas"]["DocumentId"];
                    readonly threadId: components["schemas"]["DocumentThreadId"];
                    readonly index: number;
                };
                readonly cookie?: never;
            };
            readonly get?: never;
            readonly put: {
                readonly parameters: {
                    readonly query?: never;
                    readonly header?: never;
                    readonly path: {
                        readonly id: components["schemas"]["DocumentId"];
                        readonly threadId: components["schemas"]["DocumentThreadId"];
                        readonly index: number;
                    };
                    readonly cookie?: never;
                };
                readonly requestBody?: never;
                readonly responses: {
                    readonly 200: components["responses"]["GetMessageStreamCompletion"];
                    readonly default: components["responses"]["Error"];
                };
            };
            readonly post?: never;
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
        readonly "/documents/{id}/threads/{threadId}/messages/{index}/stream/parts/{partIndex}": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: components["schemas"]["DocumentId"];
                    readonly threadId: components["schemas"]["DocumentThreadId"];
                    readonly index: number;
                    readonly partIndex: number;
                };
                readonly cookie?: never;
            };
            readonly get?: never;
            readonly put: {
                readonly parameters: {
                    readonly query?: never;
                    readonly header?: never;
                    readonly path: {
                        readonly id: components["schemas"]["DocumentId"];
                        readonly threadId: components["schemas"]["DocumentThreadId"];
                        readonly index: number;
                        readonly partIndex: number;
                    };
                    readonly cookie?: never;
                };
                readonly requestBody: components["requestBodies"]["PutMessageStreamPart"];
                readonly responses: {
                    readonly 200: components["responses"]["GetMessageStreamPart"];
                    readonly default: components["responses"]["Error"];
                };
            };
            readonly post?: never;
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
        readonly "/channels/{id}": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: components["schemas"]["ChannelId"];
                };
                readonly cookie?: never;
            };
            readonly get: {
                readonly parameters: {
                    readonly query?: never;
                    readonly header?: never;
                    readonly path: {
                        readonly id: components["schemas"]["ChannelId"];
                    };
                    readonly cookie?: never;
                };
                readonly requestBody?: never;
                readonly responses: {
                    readonly 200: {
                        headers: {
                            readonly [name: string]: unknown;
                        };
                        content: {
                            readonly "application/json": {
                                readonly spaceId: components["schemas"]["SpaceId"];
                                readonly channel: components["schemas"]["Channel"];
                            };
                        };
                    };
                    readonly default: components["responses"]["Error"];
                };
            };
            readonly put?: never;
            readonly post?: never;
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
        readonly "/posts": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly get?: never;
            readonly put?: never;
            readonly post: {
                readonly parameters: {
                    readonly query?: never;
                    readonly header?: never;
                    readonly path?: never;
                    readonly cookie?: never;
                };
                readonly requestBody: {
                    readonly content: {
                        readonly "application/json": {
                            readonly channelId: components["schemas"]["ChannelId"];
                            readonly content: components["schemas"]["Content"];
                        };
                    };
                };
                readonly responses: {
                    readonly 200: components["responses"]["GetPost"];
                    readonly default: components["responses"]["Error"];
                };
            };
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
        readonly "/posts/{id}": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: components["schemas"]["PostId"];
                };
                readonly cookie?: never;
            };
            readonly get: {
                readonly parameters: {
                    readonly query?: never;
                    readonly header?: never;
                    readonly path: {
                        readonly id: components["schemas"]["PostId"];
                    };
                    readonly cookie?: never;
                };
                readonly requestBody?: never;
                readonly responses: {
                    readonly 200: components["responses"]["GetPost"];
                    readonly default: components["responses"]["Error"];
                };
            };
            readonly put?: never;
            readonly post?: never;
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
        readonly "/posts/{id}/messages/{index}": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: components["schemas"]["PostId"];
                    readonly index: number;
                };
                readonly cookie?: never;
            };
            readonly get: {
                readonly parameters: {
                    readonly query?: never;
                    readonly header?: never;
                    readonly path: {
                        readonly id: components["schemas"]["PostId"];
                        readonly index: number;
                    };
                    readonly cookie?: never;
                };
                readonly requestBody?: never;
                readonly responses: {
                    readonly 200: components["responses"]["GetMessage"];
                    readonly default: components["responses"]["Error"];
                };
            };
            readonly put?: never;
            readonly post?: never;
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
        readonly "/posts/{id}/messages": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: components["schemas"]["PostId"];
                };
                readonly cookie?: never;
            };
            readonly get: {
                readonly parameters: {
                    readonly query?: {
                        readonly limit?: number;
                        readonly cursor?: number;
                        readonly from?: "start" | "end";
                    };
                    readonly header?: never;
                    readonly path: {
                        readonly id: components["schemas"]["PostId"];
                    };
                    readonly cookie?: never;
                };
                readonly requestBody?: never;
                readonly responses: {
                    readonly 200: components["responses"]["GetMessages"];
                    readonly default: components["responses"]["Error"];
                };
            };
            readonly put?: never;
            readonly post: {
                readonly parameters: {
                    readonly query?: never;
                    readonly header?: never;
                    readonly path: {
                        readonly id: components["schemas"]["PostId"];
                    };
                    readonly cookie?: never;
                };
                readonly requestBody: components["requestBodies"]["CreateMessage"];
                readonly responses: {
                    readonly 200: components["responses"]["GetMessage"];
                    readonly default: components["responses"]["Error"];
                };
            };
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
        readonly "/posts/{id}/messages/{index}/stream/completion": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: components["schemas"]["PostId"];
                    readonly index: number;
                };
                readonly cookie?: never;
            };
            readonly get?: never;
            readonly put: {
                readonly parameters: {
                    readonly query?: never;
                    readonly header?: never;
                    readonly path: {
                        readonly id: components["schemas"]["PostId"];
                        readonly index: number;
                    };
                    readonly cookie?: never;
                };
                readonly requestBody?: never;
                readonly responses: {
                    readonly 200: components["responses"]["GetMessageStreamCompletion"];
                    readonly default: components["responses"]["Error"];
                };
            };
            readonly post?: never;
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
        readonly "/posts/{id}/messages/{index}/stream/parts/{partIndex}": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: components["schemas"]["PostId"];
                    readonly index: number;
                    readonly partIndex: number;
                };
                readonly cookie?: never;
            };
            readonly get?: never;
            readonly put: {
                readonly parameters: {
                    readonly query?: never;
                    readonly header?: never;
                    readonly path: {
                        readonly id: components["schemas"]["PostId"];
                        readonly index: number;
                        readonly partIndex: number;
                    };
                    readonly cookie?: never;
                };
                readonly requestBody: components["requestBodies"]["PutMessageStreamPart"];
                readonly responses: {
                    readonly 200: components["responses"]["GetMessageStreamPart"];
                    readonly default: components["responses"]["Error"];
                };
            };
            readonly post?: never;
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
        readonly "/spaces/{id}/search": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: components["schemas"]["SpaceId"];
                };
                readonly cookie?: never;
            };
            readonly get: {
                readonly parameters: {
                    readonly query: {
                        readonly query: string;
                        readonly limit?: number;
                    };
                    readonly header?: never;
                    readonly path: {
                        readonly id: components["schemas"]["SpaceId"];
                    };
                    readonly cookie?: never;
                };
                readonly requestBody?: never;
                readonly responses: {
                    readonly 200: {
                        headers: {
                            readonly [name: string]: unknown;
                        };
                        content: {
                            readonly "application/json": {
                                readonly results: readonly components["schemas"]["SearchResult"][];
                            };
                        };
                    };
                    readonly default: components["responses"]["Error"];
                };
            };
            readonly put?: never;
            readonly post?: never;
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
        readonly "/tasks/{id}": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: components["schemas"]["TaskId"];
                };
                readonly cookie?: never;
            };
            readonly get: {
                readonly parameters: {
                    readonly query?: never;
                    readonly header?: never;
                    readonly path: {
                        readonly id: components["schemas"]["TaskId"];
                    };
                    readonly cookie?: never;
                };
                readonly requestBody?: never;
                readonly responses: {
                    readonly 200: {
                        headers: {
                            readonly [name: string]: unknown;
                        };
                        content: {
                            readonly "application/json": {
                                readonly spaceId: components["schemas"]["SpaceId"];
                                readonly task: components["schemas"]["Task"];
                            };
                        };
                    };
                    readonly default: components["responses"]["Error"];
                };
            };
            readonly put?: never;
            readonly post?: never;
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
        readonly "/tasks/{id}/messages/{index}": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: components["schemas"]["TaskId"];
                    readonly index: number;
                };
                readonly cookie?: never;
            };
            readonly get: {
                readonly parameters: {
                    readonly query?: never;
                    readonly header?: never;
                    readonly path: {
                        readonly id: components["schemas"]["TaskId"];
                        readonly index: number;
                    };
                    readonly cookie?: never;
                };
                readonly requestBody?: never;
                readonly responses: {
                    readonly 200: components["responses"]["GetMessage"];
                    readonly default: components["responses"]["Error"];
                };
            };
            readonly put?: never;
            readonly post?: never;
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
        readonly "/tasks/{id}/messages": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: components["schemas"]["TaskId"];
                };
                readonly cookie?: never;
            };
            readonly get: {
                readonly parameters: {
                    readonly query?: {
                        readonly limit?: number;
                        readonly cursor?: number;
                        readonly from?: "start" | "end";
                    };
                    readonly header?: never;
                    readonly path: {
                        readonly id: components["schemas"]["TaskId"];
                    };
                    readonly cookie?: never;
                };
                readonly requestBody?: never;
                readonly responses: {
                    readonly 200: components["responses"]["GetMessages"];
                    readonly default: components["responses"]["Error"];
                };
            };
            readonly put?: never;
            readonly post: {
                readonly parameters: {
                    readonly query?: never;
                    readonly header?: never;
                    readonly path: {
                        readonly id: components["schemas"]["TaskId"];
                    };
                    readonly cookie?: never;
                };
                readonly requestBody: components["requestBodies"]["CreateMessage"];
                readonly responses: {
                    readonly 200: components["responses"]["GetMessage"];
                    readonly default: components["responses"]["Error"];
                };
            };
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
        readonly "/tasks/{id}/messages/{index}/stream/completion": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: components["schemas"]["TaskId"];
                    readonly index: number;
                };
                readonly cookie?: never;
            };
            readonly get?: never;
            readonly put: {
                readonly parameters: {
                    readonly query?: never;
                    readonly header?: never;
                    readonly path: {
                        readonly id: components["schemas"]["TaskId"];
                        readonly index: number;
                    };
                    readonly cookie?: never;
                };
                readonly requestBody?: never;
                readonly responses: {
                    readonly 200: components["responses"]["GetMessageStreamCompletion"];
                    readonly default: components["responses"]["Error"];
                };
            };
            readonly post?: never;
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
        readonly "/tasks/{id}/messages/{index}/stream/parts/{partIndex}": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: components["schemas"]["TaskId"];
                    readonly index: number;
                    readonly partIndex: number;
                };
                readonly cookie?: never;
            };
            readonly get?: never;
            readonly put: {
                readonly parameters: {
                    readonly query?: never;
                    readonly header?: never;
                    readonly path: {
                        readonly id: components["schemas"]["TaskId"];
                        readonly index: number;
                        readonly partIndex: number;
                    };
                    readonly cookie?: never;
                };
                readonly requestBody: components["requestBodies"]["PutMessageStreamPart"];
                readonly responses: {
                    readonly 200: components["responses"]["GetMessageStreamPart"];
                    readonly default: components["responses"]["Error"];
                };
            };
            readonly post?: never;
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
        readonly "/task-collections/{id}": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: components["schemas"]["TaskCollectionId"];
                };
                readonly cookie?: never;
            };
            readonly get: {
                readonly parameters: {
                    readonly query?: never;
                    readonly header?: never;
                    readonly path: {
                        readonly id: components["schemas"]["TaskCollectionId"];
                    };
                    readonly cookie?: never;
                };
                readonly requestBody?: never;
                readonly responses: {
                    readonly 200: {
                        headers: {
                            readonly [name: string]: unknown;
                        };
                        content: {
                            readonly "application/json": {
                                readonly spaceId: components["schemas"]["SpaceId"];
                                readonly taskCollection: components["schemas"]["TaskCollection"];
                            };
                        };
                    };
                    readonly default: components["responses"]["Error"];
                };
            };
            readonly put?: never;
            readonly post?: never;
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
    }
    export interface webhooks {
        readonly bot: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly get?: never;
            readonly put?: never;
            readonly post: {
                readonly parameters: {
                    readonly query?: never;
                    readonly header?: never;
                    readonly path?: never;
                    readonly cookie?: never;
                };
                readonly requestBody: {
                    readonly content: {
                        readonly "application/json": {
                            readonly spaceId: components["schemas"]["SpaceId"];
                            readonly accountId: components["schemas"]["AccountId"];
                            readonly attempt: number;
                            readonly accessToken: string;
                            readonly eventId: components["schemas"]["BotWebhookEventId"];
                            readonly event: components["schemas"]["BotWebhookEvent"];
                        };
                    };
                };
                readonly responses: {
                    /** @description Return a 200 status to indicate that the data was received successfully */
                    readonly 200: {
                        headers: {
                            readonly [name: string]: unknown;
                        };
                        content?: never;
                    };
                };
            };
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
    }
    export interface components {
        schemas: {
            readonly LabelString: string;
            readonly AccountId: IdTypes.AccountId;
            readonly BotId: IdTypes.BotId;
            readonly BotWebhookEventId: IdTypes.BotWebhookEventId;
            readonly ChannelId: IdTypes.ChannelId;
            readonly ChatId: IdTypes.ChatId;
            readonly DocumentId: IdTypes.DocumentId;
            readonly DocumentThreadId: IdTypes.DocumentCommentThreadId;
            readonly PostId: IdTypes.PostId;
            readonly SpaceId: IdTypes.SpaceId;
            readonly TaskId: IdTypes.TaskId;
            readonly TaskCollectionId: IdTypes.TaskCollectionId;
            readonly AccountPath: `/accounts/${IdTypes.AccountId}`;
            readonly ChannelPath: `/channels/${IdTypes.ChannelId}`;
            readonly ChatPath: `/chats/${IdTypes.ChatId}`;
            readonly ChatMessagePath: `/chats/${IdTypes.ChatId}/messages/${number}`;
            readonly ChatMessagesListPath: `/chats/${IdTypes.ChatId}/messages`;
            readonly DocumentPath: `/documents/${IdTypes.DocumentId}`;
            readonly DocumentMessagePath: `/documents/${IdTypes.DocumentId}/threads/${IdTypes.DocumentCommentThreadId}/messages/${number}`;
            readonly DocumentThreadPath: `/documents/${IdTypes.DocumentId}/threads/${IdTypes.DocumentCommentThreadId}`;
            readonly DocumentThreadMessagesListPath: `/documents/${IdTypes.DocumentId}/threads/${IdTypes.DocumentCommentThreadId}/messages`;
            readonly PostPath: `/posts/${IdTypes.PostId}`;
            readonly PostMessagePath: `/posts/${IdTypes.PostId}/messages/${number}`;
            readonly PostMessagesListPath: `/posts/${IdTypes.PostId}/messages`;
            readonly TaskPath: `/tasks/${IdTypes.TaskId}`;
            readonly TaskCollectionPath: `/task-collections/${IdTypes.TaskCollectionId}`;
            readonly TaskMessagePath: `/tasks/${IdTypes.TaskId}/messages/${number}`;
            readonly TaskMessagesListPath: `/tasks/${IdTypes.TaskId}/messages`;
            readonly MessageRoomPath:
                | components["schemas"]["ChatPath"]
                | components["schemas"]["DocumentThreadPath"]
                | components["schemas"]["PostPath"]
                | components["schemas"]["TaskPath"];
            readonly MessagesListPath:
                | components["schemas"]["ChatMessagesListPath"]
                | components["schemas"]["DocumentThreadMessagesListPath"]
                | components["schemas"]["PostMessagesListPath"]
                | components["schemas"]["TaskMessagesListPath"];
            readonly ContentMentionInlineElementTargetPath:
                | components["schemas"]["AccountPath"]
                | components["schemas"]["ChannelPath"]
                | components["schemas"]["DocumentPath"]
                | components["schemas"]["PostPath"]
                | components["schemas"]["TaskPath"]
                | components["schemas"]["TaskCollectionPath"];
            readonly SearchResultPath:
                | components["schemas"]["AccountPath"]
                | components["schemas"]["ChannelPath"]
                | components["schemas"]["ChatPath"]
                | components["schemas"]["ChatMessagePath"]
                | components["schemas"]["DocumentPath"]
                | components["schemas"]["DocumentMessagePath"]
                | components["schemas"]["PostPath"]
                | components["schemas"]["PostMessagePath"]
                | components["schemas"]["TaskPath"]
                | components["schemas"]["TaskMessagePath"]
                | components["schemas"]["TaskCollectionPath"];
            readonly Content: {
                readonly elements: readonly components["schemas"]["ContentBlockElement"][];
            };
            readonly ContentBlockElement:
                | components["schemas"]["ContentParagraphBlockElement"]
                | components["schemas"]["ContentUnorderedListBlockElement"]
                | components["schemas"]["ContentOrderedListBlockElement"]
                | components["schemas"]["ContentQuoteBlockElement"]
                | components["schemas"]["ContentHeadingBlockElement"]
                | components["schemas"]["ContentDividerBlockElement"]
                | components["schemas"]["ContentTableBlockElement"]
                | components["schemas"]["ContentCodeBlockElement"];
            readonly ContentParagraphBlockElement: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Paragraph";
                readonly elements: readonly components["schemas"]["ContentInlineElement"][];
            };
            readonly ContentListBlockElement:
                | components["schemas"]["ContentUnorderedListBlockElement"]
                | components["schemas"]["ContentOrderedListBlockElement"];
            readonly ContentUnorderedListBlockElement: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "UnorderedList";
                readonly items: readonly components["schemas"]["ContentListBlockElementItem"][];
            };
            readonly ContentOrderedListBlockElement: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "OrderedList";
                readonly items: readonly components["schemas"]["ContentListBlockElementItem"][];
            };
            readonly ContentListBlockElementItem: {
                readonly elements: readonly components["schemas"]["ContentParagraphBlockElement"][];
                readonly nestedListElements?: readonly components["schemas"]["ContentListBlockElement"][];
            };
            readonly ContentQuoteBlockElement: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Quote";
                readonly elements: readonly components["schemas"]["ContentQuoteBlockElementBlockElement"][];
            };
            readonly ContentQuoteBlockElementBlockElement:
                | components["schemas"]["ContentParagraphBlockElement"]
                | components["schemas"]["ContentUnorderedListBlockElement"]
                | components["schemas"]["ContentOrderedListBlockElement"];
            readonly ContentHeadingBlockElement: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Heading";
                readonly level: number;
                readonly elements: readonly components["schemas"]["ContentInlineElement"][];
            };
            readonly ContentDividerBlockElement: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Divider";
            };
            readonly ContentTableBlockElement: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Table";
                readonly width: number;
                readonly hasHeaderRow?: boolean;
                readonly hasHeaderColumn?: boolean;
                readonly columns: readonly {
                    readonly width: number;
                }[];
                readonly rows: readonly components["schemas"]["ContentTableBlockElementRow"][];
            };
            readonly ContentTableBlockElementRow: {
                readonly cells: readonly components["schemas"]["ContentTableBlockElementCell"][];
            };
            readonly ContentTableBlockElementCell: {
                readonly elements: readonly components["schemas"]["ContentTableBlockElementCellBlockElement"][];
            };
            readonly ContentTableBlockElementCellBlockElement:
                | components["schemas"]["ContentParagraphBlockElement"]
                | components["schemas"]["ContentUnorderedListBlockElement"]
                | components["schemas"]["ContentOrderedListBlockElement"]
                | components["schemas"]["ContentQuoteBlockElement"]
                | components["schemas"]["ContentCodeBlockElement"];
            readonly ContentCodeBlockElement: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Code";
                /** @enum {string} */
                readonly language:
                    | "text"
                    | "javascript"
                    | "html"
                    | "css"
                    | "sql"
                    | "python"
                    | "typescript"
                    | "shell"
                    | "java"
                    | "json"
                    | "markdown"
                    | "csharp"
                    | "cpp"
                    | "c"
                    | "php"
                    | "go"
                    | "yaml"
                    | "powershell"
                    | "rust"
                    | "kotlin"
                    | "ruby"
                    | "lua"
                    | "xml"
                    | "dart"
                    | "swift"
                    | "assembly"
                    | "webassembly"
                    | "scala"
                    | "r"
                    | "elixir"
                    | "objectivec"
                    | "perl"
                    | "haskell"
                    | "solidity"
                    | "clojure"
                    | "erlang"
                    | "ocaml";
                readonly lines: readonly components["schemas"]["ContentCodeBlockElementLine"][];
            };
            readonly ContentCodeBlockElementLine: {
                readonly elements: readonly components["schemas"]["ContentCodeBlockElementTextInlineElement"][];
            };
            readonly ContentInlineElement:
                | components["schemas"]["ContentTextInlineElement"]
                | components["schemas"]["ContentBreakInlineElement"]
                | components["schemas"]["ContentMentionInlineElement"];
            readonly ContentTextInlineElement: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Text";
                readonly text: string;
                readonly marks?: readonly components["schemas"]["ContentInlineElementMark"][];
            };
            readonly ContentBreakInlineElement: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Break";
                readonly marks?: readonly components["schemas"]["ContentInlineElementMark"][];
            };
            readonly ContentMentionInlineElement: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Mention";
                readonly targetPath: components["schemas"]["ContentMentionInlineElementTargetPath"];
                readonly title?: string;
                readonly isAccountShortName?: boolean;
                readonly marks?: readonly components["schemas"]["ContentInlineElementMark"][];
            };
            readonly ContentInlineElementMark:
                | components["schemas"]["ContentInlineElementBoldMark"]
                | components["schemas"]["ContentInlineElementItalicMark"]
                | components["schemas"]["ContentInlineElementStrikeMark"]
                | components["schemas"]["ContentInlineElementLinkMark"]
                | components["schemas"]["ContentInlineElementCodeMark"]
                | components["schemas"]["ContentInlineElementHighlightMark"]
                | components["schemas"]["ContentInlineElementCommentMark"];
            readonly ContentInlineElementBoldMark: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Bold";
            };
            readonly ContentInlineElementItalicMark: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Italic";
            };
            readonly ContentInlineElementStrikeMark: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Strike";
            };
            readonly ContentInlineElementLinkMark: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Link";
                readonly url: string;
            };
            readonly ContentInlineElementCodeMark: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Code";
            };
            readonly ContentInlineElementHighlightMark: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Highlight";
                readonly color: components["schemas"]["ContentInlineElementHighlightMarkColor"];
            };
            /** @enum {string} */
            readonly ContentInlineElementHighlightMarkColor:
                | "Red"
                | "Orange"
                | "Green"
                | "Blue"
                | "Purple";
            readonly ContentInlineElementCommentMark: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Comment";
                readonly threadId: components["schemas"]["DocumentThreadId"];
            };
            readonly ContentCodeBlockElementTextInlineElement: {
                /** @constant */
                readonly type: "Text";
                readonly text: string;
                readonly marks?: readonly components["schemas"]["ContentCodeBlockElementTextInlineElementMark"][];
            };
            readonly ContentCodeBlockElementTextInlineElementMark:
                | components["schemas"]["ContentInlineElementBoldMark"]
                | components["schemas"]["ContentInlineElementItalicMark"]
                | components["schemas"]["ContentInlineElementStrikeMark"]
                | components["schemas"]["ContentInlineElementLinkMark"]
                | components["schemas"]["ContentInlineElementHighlightMark"]
                | components["schemas"]["ContentInlineElementCommentMark"];
            readonly AccountWithoutSpace: {
                readonly id: components["schemas"]["AccountId"];
                readonly name: components["schemas"]["LabelString"];
                readonly shortName: components["schemas"]["LabelString"];
                readonly botId?: components["schemas"]["BotId"];
            };
            readonly Space: {
                readonly id: components["schemas"]["SpaceId"];
                readonly name: components["schemas"]["LabelString"];
            };
            readonly Account: {
                readonly id: components["schemas"]["AccountId"];
                readonly name: components["schemas"]["LabelString"];
                readonly shortName: string;
                readonly botId?: components["schemas"]["BotId"];
                readonly space: {
                    /** @enum {string} */
                    readonly role: "Owner" | "Admin" | "Member";
                    /** Format: date-time */
                    readonly addedTime: DateString;
                    readonly inactive?:
                        | {
                              /** @constant */
                              readonly type: "Removed";
                              /** Format: date-time */
                              readonly removedTime?: DateString;
                          }
                        | {
                              /** @constant */
                              readonly type: "InvitePending";
                          };
                };
            };
            readonly Chat: {
                readonly id: components["schemas"]["ChatId"];
                readonly members: readonly {
                    readonly account: components["schemas"]["Account"];
                }[];
            };
            readonly Document: {
                readonly id: components["schemas"]["DocumentId"];
                readonly title: string;
                readonly content: components["schemas"]["Content"];
            };
            readonly DocumentPreview: {
                readonly id: components["schemas"]["DocumentId"];
                readonly title: string;
            };
            readonly ChannelPreview: {
                readonly id: components["schemas"]["ChannelId"];
                readonly name: components["schemas"]["LabelString"];
            };
            readonly Channel: {
                readonly id: components["schemas"]["ChannelId"];
                readonly name: components["schemas"]["LabelString"];
                readonly description: components["schemas"]["Content"];
            };
            readonly Post: {
                readonly id: components["schemas"]["PostId"];
                readonly author: components["schemas"]["Account"];
                readonly channel?: components["schemas"]["ChannelPreview"];
                readonly content: components["schemas"]["Content"];
                readonly contentPreview: string;
            };
            readonly PostPreview: {
                readonly id: components["schemas"]["PostId"];
                readonly author: components["schemas"]["Account"];
                readonly channel?: components["schemas"]["ChannelPreview"];
                readonly contentPreview: string;
            };
            readonly Task: {
                readonly id: components["schemas"]["TaskId"];
                readonly status: components["schemas"]["TaskStatus"];
                readonly title: string;
                readonly assignee?: components["schemas"]["Account"];
                readonly due?: {
                    /** Format: date */
                    readonly date: string;
                };
                /** @enum {string} */
                readonly priority?: "Low" | "Medium" | "High" | "Urgent";
                readonly content: components["schemas"]["Content"];
            };
            readonly TaskPreview: {
                readonly id: components["schemas"]["TaskId"];
                readonly status: components["schemas"]["TaskStatus"];
                readonly title: string;
            };
            readonly TaskStatus:
                | {
                      /** @constant */
                      readonly type: "Open";
                      readonly isActive: boolean;
                  }
                | {
                      /** @constant */
                      readonly type: "Closed";
                  };
            readonly TaskCollection: {
                readonly id: components["schemas"]["TaskCollectionId"];
                readonly name: components["schemas"]["LabelString"];
            };
            readonly Message: {
                readonly index: number;
                readonly author: components["schemas"]["Account"];
                /** Format: date-time */
                readonly createdTime: DateString;
                readonly payload: components["schemas"]["MessagePayload"];
            };
            readonly MessagePayload:
                | components["schemas"]["MessageContentPayload"]
                | components["schemas"]["MessageDeletedPayload"];
            readonly MessageContentPayload: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Content";
                readonly parent?: components["schemas"]["MessageContentPayloadMessageParent"];
                readonly content: components["schemas"]["Content"];
            };
            readonly MessageContentPayloadMessageParent: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Message";
                readonly index: number;
            };
            readonly MessageDeletedPayload: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Deleted";
            };
            readonly MessageStreamPart: {
                readonly index: number;
                readonly version: number;
                readonly payload: components["schemas"]["MessageStreamPartPayload"];
            };
            readonly MessageStreamPartPayload:
                | components["schemas"]["MessageStreamContentPartPayload"]
                | components["schemas"]["MessageStreamToolCallPartPayload"];
            readonly MessageStreamContentPartPayload: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Content";
                readonly content: components["schemas"]["Content"];
            };
            readonly MessageStreamToolCallPartPayload: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "ToolCall";
                readonly call: components["schemas"]["MessageStreamToolCallPartPayloadCall"];
            };
            readonly MessageStreamToolCallPartPayloadCall: components["schemas"]["MessageStreamToolCallPartPayloadReadCall"];
            readonly MessageStreamToolCallPartPayloadReadCall: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Read";
                readonly targetPath: components["schemas"]["ContentMentionInlineElementTargetPath"];
                readonly title: string;
            };
            readonly BotWebhookEvent: components["schemas"]["BotWebhookNewMessageEvent"];
            readonly BotWebhookNewMessageEvent: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "NewMessage";
                readonly roomPath: components["schemas"]["MessageRoomPath"];
                readonly index: number;
                readonly authorId: components["schemas"]["AccountId"];
                readonly wasMentioned?: boolean;
            };
            readonly SearchResult:
                | components["schemas"]["SearchAccountResult"]
                | components["schemas"]["SearchChannelResult"]
                | components["schemas"]["SearchChatResult"]
                | components["schemas"]["SearchChatMessageResult"]
                | components["schemas"]["SearchDocumentResult"]
                | components["schemas"]["SearchDocumentMessageResult"]
                | components["schemas"]["SearchPostResult"]
                | components["schemas"]["SearchPostMessageResult"]
                | components["schemas"]["SearchTaskResult"]
                | components["schemas"]["SearchTaskMessageResult"]
                | components["schemas"]["SearchTaskCollectionResult"];
            readonly SearchAccountResult: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Account";
                readonly path: components["schemas"]["AccountPath"];
                readonly title: string;
                /** @constant */
                readonly bodyMatch: null;
            };
            readonly SearchChannelResult: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Channel";
                readonly path: components["schemas"]["ChannelPath"];
                readonly title: string;
                readonly bodyMatch: components["schemas"]["SearchResultBodyMatches"] | null;
            };
            readonly SearchChatResult: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Chat";
                readonly path: components["schemas"]["ChatPath"];
                readonly title: string;
                /** @constant */
                readonly bodyMatch: null;
            };
            readonly SearchChatMessageResult: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "ChatMessage";
                readonly path: components["schemas"]["ChatMessagePath"];
                readonly bodyMatch: components["schemas"]["SearchResultBodyMatches"];
                /** @constant */
                readonly title: null;
                readonly author: components["schemas"]["Account"];
            };
            readonly SearchDocumentResult: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Document";
                readonly path: components["schemas"]["DocumentPath"];
                readonly title: string;
                readonly bodyMatch: components["schemas"]["SearchResultBodyMatches"] | null;
            };
            readonly SearchDocumentMessageResult: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "DocumentMessage";
                readonly path: components["schemas"]["DocumentMessagePath"];
                /** @constant */
                readonly title: null;
                readonly bodyMatch: components["schemas"]["SearchResultBodyMatches"] | null;
                readonly author: components["schemas"]["Account"];
            };
            readonly SearchPostResult: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Post";
                readonly path: components["schemas"]["PostPath"];
                readonly title: string;
                readonly bodyMatch: components["schemas"]["SearchResultBodyMatches"] | null;
                readonly author: components["schemas"]["Account"];
            };
            readonly SearchPostMessageResult: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "PostMessage";
                readonly path: components["schemas"]["PostMessagePath"];
                /** @constant */
                readonly title: null;
                readonly bodyMatch: components["schemas"]["SearchResultBodyMatches"] | null;
                readonly author: components["schemas"]["Account"];
            };
            readonly SearchTaskResult: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Task";
                readonly path: components["schemas"]["TaskPath"];
                readonly title: string;
                readonly bodyMatch: components["schemas"]["SearchResultBodyMatches"] | null;
                readonly status: components["schemas"]["TaskStatus"];
            };
            readonly SearchTaskMessageResult: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "TaskMessage";
                readonly path: components["schemas"]["TaskMessagePath"];
                /** @constant */
                readonly title: null;
                readonly bodyMatch: components["schemas"]["SearchResultBodyMatches"] | null;
                readonly author: components["schemas"]["Account"];
            };
            readonly SearchTaskCollectionResult: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "TaskCollection";
                readonly path: components["schemas"]["TaskCollectionPath"];
                readonly title: string;
                /** @constant */
                readonly bodyMatch: null;
            };
            readonly SearchResultBodyMatches: readonly {
                readonly text: string;
                /** @constant */
                readonly isMatch?: true;
            }[];
        };
        responses: {
            readonly Error: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly error: {
                            /** @description A human-readable message providing more details about the error. */
                            readonly message: string;
                        };
                    };
                };
            };
            readonly GetMessage: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly spaceId: components["schemas"]["SpaceId"];
                        readonly message: components["schemas"]["Message"];
                    };
                };
            };
            readonly GetMessages: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly spaceId: components["schemas"]["SpaceId"];
                        readonly totalMessageCount: number;
                        readonly nextCursor: number | null;
                        readonly messages: readonly components["schemas"]["Message"][];
                    };
                };
            };
            readonly GetMessageStreamCompletion: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly spaceId: components["schemas"]["SpaceId"];
                        readonly completion: {
                            /** Format: date-time */
                            readonly completedTime: DateString;
                        };
                    };
                };
            };
            readonly GetMessageStreamPart: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly spaceId: components["schemas"]["SpaceId"];
                    };
                };
            };
            readonly GetPost: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly spaceId: components["schemas"]["SpaceId"];
                        readonly post: components["schemas"]["Post"];
                    };
                };
            };
        };
        parameters: never;
        requestBodies: {
            readonly CreateMessage: {
                readonly content: {
                    readonly "application/json": {
                        readonly isStream?: boolean;
                        readonly content: components["schemas"]["Content"];
                    };
                };
            };
            readonly PutMessageStreamPart: {
                readonly content: {
                    readonly "application/json": {
                        readonly payload: components["schemas"]["MessageStreamPartPayload"];
                    };
                };
            };
        };
        headers: never;
        pathItems: never;
    }
    export type $defs = Record<string, never>;
    export type operations = Record<string, never>;
}
