load("//admin/typescript:typescript.bzl", "ts_project")

ts_project(
    name = "sharp",
    visibility = ["//server/files/processor:__subpackages__"],
    deps = [
        "//server/files/processor/error",
        "//shared/error",
        "//shared/helpers",
    ],
)
