// Same list as `server/opensearch/opensearch_visibility.bzl` but available in
// JavaScript. The implementation of this file is generated by
// `//admin/crawl:opensearch_visibility_src`.
export const opensearchVisibilityBazelPackagePaths: ReadonlyArray<string>;
