// @generated by //admin/dynamo:write_schema

/**
 * A list of keys to replace `*` in the `dynamodb.consumed_capacity.*` event
 * attribute. It is generated by `generate_dynamo_files_main.ts`.
 *
 * We need a list of DynamoDB tables so we generate it from `//server/dynamo`
 * instead of importing `//server/dynamo` at runtime. That way code which doesn't
 * directly depend on DynamoDB doesn't need to pay the runtime cost of initializing
 * DynamoDB tables.
 *
 * We commit the file so there isn't a package dependency on `//server/dynamo`
 * either which our dev server would see and rebuild `//server/tracer` dependents
 * on `//server/dynamo` changes.
 */
export const tracerEventDataDynamoConsumedCapacityKeys = new Set([
    "Accounts",
    "AlphaAccess",
    "BotWebhookEvents",
    "Bots",
    "Chat",
    "Deploy",
    "Documents",
    "Feed",
    "Files",
    "Forum",
    "ForumRealtime",
    "Inbox",
    "Integrations",
    "Notifications",
    "NotionImporter",
    "SearchEntities",
    "Spaces",
    "SpellCheck",
    "TaskActions",
    "Tasks",
    "Accounts_Index1",
    "Bots_Index1",
    "Chat_Index1",
    "Files_Index1",
    "ForumRealtime_Index1",
    "Inbox_Index1",
    "Inbox_Index2",
    "Notifications_Index1",
    "NotionImporter_Index1",
    "SearchEntities_Index1",
    "SearchEntities_Index2",
    "SearchEntities_Index3",
    "SearchEntities_Index4",
    "TaskActions_Index1",
]);

/**
 * All the partition types for each table. We use these to build the tracer event
 * data schema for `dynamodb.item` which includes partition types and sort range
 * types in a nested format.
 *
 * We generate this map from `//server/dynamo` instead of importing
 * `//server/dynamo` at runtime. That way code which doesn't directly depend on
 * DynamoDB doesn't need to pay the runtime cost of initializing DynamoDB tables.
 *
 * We commit the file so there isn't a package dependency on `//server/dynamo`
 * either which our dev server would see and rebuild `//server/tracer` dependents
 * on `//server/dynamo` changes.
 */
// prettier-ignore
export const tracerEventDataDynamoPartitionTypesByTableName = new Map<string, ReadonlyArray<string>>([
    ["Accounts", ["Account", "AccountEmailAddress", "Session", "StripeCustomer", "TryOnDesktopEmailOptOut", "SentTryOnDesktopEmail"]],
    ["AlphaAccess", ["AlphaConfiguration", "AlphaAccessRequests"]],
    ["BotWebhookEvents", ["BotSpace"]],
    ["Bots", ["Bot", "ApiKey", "Space"]],
    ["Chat", ["Chat"]],
    ["Deploy", ["Deploy"]],
    ["Documents", ["Document", "DocumentCommentThread"]],
    ["Feed", ["FeedCandidates", "FeedAccountCandidates", "Feed"]],
    ["Files", ["Space", "File"]],
    ["Forum", ["Channel", "Post", "Account"]],
    ["ForumRealtime", ["Channel", "Post", "Realtime", "Graveyard"]],
    ["Inbox", ["Account", "Inbox", "Realtime", "Graveyard"]],
    ["Integrations", ["SlackSpaceIntegration"]],
    ["Notifications", ["Inbox", "PushTargets"]],
    ["NotionImporter", ["Import"]],
    ["SearchEntities", ["Account", "SpaceChannels", "SpaceTaskCollections", "IndexSearchEntityEmbeddingChunksJob"]],
    ["Spaces", ["Space", "AutoAddAccountsFromEmailDomain", "Account", "Bot"]],
    ["SpellCheck", ["IgnoredLint", "Realtime", "Graveyard"]],
    ["TaskActions", ["TaskActions"]],
    ["Tasks", ["Account", "TaskCollection", "Task", "TaskGridViewExpansionState"]],
]);
