import {Lazy} from "~/shared/helpers/control/lazy.js";
import {Reaction, ReactionMap} from "~/shared/reactions/reaction.js";

/**
 * The integer ID for each reaction icon.
 */
export const reactionIds: ReactionMap<number> = {
    Cat: {
        Grey: {
            Celebrate: 1,
            DeadInside: 2,
            Hardship: 3,
            Happy: 4,
            Laugh: 5,
            Lolsob: 6,
            No: 7,
            Shock: 8,
            Yes: 9,
            ThankYou: 82,
            Heart: 83,
        },
        Pink: {
            Celebrate: 10,
            DeadInside: 11,
            Hardship: 12,
            Happy: 13,
            Laugh: 14,
            Lolsob: 15,
            No: 16,
            Shock: 17,
            Yes: 18,
            ThankYou: 84,
            Heart: 85,
        },
        Yellow: {
            Celebrate: 19,
            DeadInside: 20,
            Hardship: 21,
            Happy: 22,
            Laugh: 23,
            Lolsob: 24,
            No: 25,
            Shock: 26,
            Yes: 27,
            ThankYou: 86,
            Heart: 87,
        },
    },
    Tree: {
        Blue: {
            Celebrate: 46,
            DeadInside: 47,
            Hardship: 48,
            Happy: 49,
            Laugh: 50,
            Lolsob: 51,
            No: 52,
            Shock: 53,
            Yes: 54,
            ThankYou: 88,
            Heart: 89,
        },
        Green: {
            Celebrate: 37,
            DeadInside: 38,
            Hardship: 39,
            Happy: 40,
            Laugh: 41,
            Lolsob: 42,
            No: 43,
            Shock: 44,
            Yes: 45,
            ThankYou: 90,
            Heart: 91,
        },
        Pink: {
            Celebrate: 28,
            DeadInside: 29,
            Hardship: 30,
            Happy: 31,
            Laugh: 32,
            Lolsob: 33,
            No: 34,
            Shock: 35,
            Yes: 36,
            ThankYou: 92,
            Heart: 93,
        },
    },
    Yeti: {
        Blue: {
            Celebrate: 55,
            DeadInside: 56,
            Hardship: 57,
            Happy: 58,
            Laugh: 59,
            Lolsob: 60,
            No: 61,
            Shock: 62,
            Yes: 63,
            ThankYou: 94,
            Heart: 95,
        },
        Brown: {
            Celebrate: 64,
            DeadInside: 65,
            Hardship: 66,
            Happy: 67,
            Laugh: 68,
            Lolsob: 69,
            No: 70,
            Shock: 71,
            Yes: 72,
            ThankYou: 96,
            Heart: 97,
        },
        Olive: {
            Celebrate: 73,
            DeadInside: 74,
            Hardship: 75,
            Happy: 76,
            Laugh: 77,
            Lolsob: 78,
            No: 79,
            Shock: 80,
            Yes: 81,
            ThankYou: 98,
            Heart: 99,
        },
    },
    Frog: {
        Green: {
            Celebrate: 100,
            DeadInside: 101,
            Hardship: 102,
            Happy: 103,
            Laugh: 104,
            Lolsob: 105,
            Shock: 106,
            Heart: 107,
            Yes: 108,
            No: 109,
            ThankYou: 110,
        },
        Cyan: {
            Celebrate: 111,
            DeadInside: 112,
            Hardship: 113,
            Happy: 114,
            Laugh: 115,
            Lolsob: 116,
            Shock: 117,
            Heart: 118,
            Yes: 119,
            No: 120,
            ThankYou: 121,
        },
        Yellow: {
            Celebrate: 122,
            DeadInside: 123,
            Hardship: 124,
            Happy: 125,
            Laugh: 126,
            Lolsob: 127,
            Shock: 128,
            Heart: 129,
            Yes: 130,
            No: 131,
            ThankYou: 132,
        },
    },
    Pigeon: {
        Plain: {
            Celebrate: 133,
            DeadInside: 134,
            Hardship: 135,
            Happy: 136,
            Laugh: 137,
            Lolsob: 138,
            Shock: 139,
            Heart: 140,
            Yes: 141,
            No: 142,
            ThankYou: 143,
        },
        Brown: {
            Celebrate: 144,
            DeadInside: 145,
            Hardship: 146,
            Happy: 147,
            Laugh: 148,
            Lolsob: 149,
            Shock: 150,
            Heart: 151,
            Yes: 152,
            No: 153,
            ThankYou: 154,
        },
        Grey: {
            Celebrate: 155,
            DeadInside: 156,
            Hardship: 157,
            Happy: 158,
            Laugh: 159,
            Lolsob: 160,
            Shock: 161,
            Heart: 162,
            Yes: 163,
            No: 164,
            ThankYou: 165,
        },
    },
    Tulip: {
        Yellow: {
            Celebrate: 166,
            DeadInside: 167,
            Hardship: 168,
            Happy: 169,
            Laugh: 170,
            Lolsob: 171,
            Shock: 172,
            Heart: 173,
            Yes: 174,
            No: 175,
            ThankYou: 176,
        },
        Pink: {
            Celebrate: 177,
            DeadInside: 178,
            Hardship: 179,
            Happy: 180,
            Laugh: 181,
            Lolsob: 182,
            Shock: 183,
            Heart: 184,
            Yes: 185,
            No: 186,
            ThankYou: 187,
        },
        Violet: {
            Celebrate: 188,
            DeadInside: 189,
            Hardship: 190,
            Happy: 191,
            Laugh: 192,
            Lolsob: 193,
            Shock: 194,
            Heart: 195,
            Yes: 196,
            No: 197,
            ThankYou: 198,
        },
    },
};

/**
 * Get the `Reaction` object for a given ID.
 */
export const reactionById = new Lazy<ReadonlyMap<number, Reaction>>(() => {
    const reactionById = new Map<number, Reaction>();

    for (const [type, characterMap] of Object.entries(reactionIds as any)) {
        for (const [variant, variantMap] of Object.entries(characterMap as any)) {
            for (const [emotion, id] of Object.entries(variantMap as any)) {
                reactionById.set(id as any, {character: {type, variant}, emotion} as any);
            }
        }
    }

    return reactionById;
});
