import {encodeId} from "~/shared/id/id.open_source.js";
import {DocumentId, SpaceId} from "~/shared/id/types/id_types.open_source.js";

/**
 * Generates a deterministic document ID based on the target space ID, Notion
 * workspace ID, and document's notion ID. This ensures that:
 *
 * 1. Importing the same Notion workspace into the same space multiple times
 *    produces the same document IDs (idempotent imports).
 * 2. Importing the same Notion workspace into different spaces produces different
 *    document IDs (no cross-space collisions).
 *
 * The space ID is included in the hash input to ensure document IDs are unique per
 * destination space. Without this, two different spaces importing the same Notion
 * workspace would create documents with identical IDs, which would cause conflicts
 * in any shared storage layer.
 *
 * The ID is generated by hashing the concatenation of space ID, workspace ID, and
 * notion ID using SHA-256, then taking the first 16 bytes and encoding them as an
 * ID.
 *
 * @param spaceId - The Alpine space ID where the document will be created @param
 * workspaceId - The Notion workspace ID (from index.html) @param notionId - The
 * document's notion ID (32-char hex from filename)
 */
export async function generateDeterministicNotionDocumentId(
    spaceId: SpaceId,
    workspaceId: string,
    notionId: string,
): Promise<DocumentId> {
    const input = `notion:${spaceId}:${workspaceId}:${notionId}`;
    const encoder = new TextEncoder();
    const data = encoder.encode(input);

    const hashBuffer = await crypto.subtle.digest("SHA-256", data);
    const hashBytes = new Uint8Array(hashBuffer);

    // Take the first 16 bytes (128 bits) for the ID
    return encodeId<DocumentId>(hashBytes);
}

/**
 * Synchronous version using a simple hash function for cases where async is not
 * convenient. Uses FNV-1a hash to generate 16 bytes by computing 4 different
 * 32-bit hashes (with different suffixes) and using all 4 bytes from each.
 *
 * See generateDeterministicNotionDocumentId for documentation on why the space ID
 * is included in the hash.
 */
export function generateDeterministicNotionDocumentIdSync(
    spaceId: SpaceId,
    workspaceId: string,
    notionId: string,
): DocumentId {
    const input = `notion:${spaceId}:${workspaceId}:${notionId}`;
    const bytes = new Uint8Array(16);

    // Generate 16 bytes using 4 FNV-1a hashes (32 bits each = 4 bytes each)
    for (let i = 0; i < 4; i++) {
        const hash = fnv1aHash32(`${input}:${i}`);
        bytes[i * 4] = (hash >>> 24) & 0xff;
        bytes[i * 4 + 1] = (hash >>> 16) & 0xff;
        bytes[i * 4 + 2] = (hash >>> 8) & 0xff;
        bytes[i * 4 + 3] = hash & 0xff;
    }

    return encodeId<DocumentId>(bytes);
}

/**
 * FNV-1a hash function that returns a 32-bit hash.
 */
function fnv1aHash32(str: string): number {
    let hash = 2166136261; // FNV offset basis (32-bit)

    for (let i = 0; i < str.length; i++) {
        hash ^= str.charCodeAt(i);
        hash = Math.imul(hash, 16777619); // FNV prime
    }

    // Return as unsigned 32-bit integer
    return hash >>> 0;
}
