load("//admin/typescript:typescript.bzl", "ts_project")

ts_project(
    name = "test_helpers",
    testonly = True,
    visibility = ["//visibility:public"],
    deps = [
        "//:node_modules/@types/prettier",
        "//:node_modules/prettier",
    ],
)
