import {
    dynamoKeyAttributeMaxCharCode,
    dynamoKeyAttributeMinCharCode,
    isDynamoKeyAttribute,
} from "~/server/dynamo/internal/dynamo-key-attribute-schema";

test("key attributes can be a reasonable set of ASCII characters", () => {
    const chars = [];

    for (
        let charCode = dynamoKeyAttributeMinCharCode;
        charCode <= dynamoKeyAttributeMaxCharCode;
        charCode++
    ) {
        const char = String.fromCharCode(charCode);
        expect(isDynamoKeyAttribute(char)).toEqual(true);
        chars.push(char);
    }

    expect(chars).toEqual([
        "$",
        "%",
        "&",
        "'",
        "(",
        ")",
        "*",
        "+",
        ",",
        "-",
        ".",
        "/",
        "0",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        ":",
        ";",
        "<",
        "=",
        ">",
        "?",
        "@",
        "A",
        "B",
        "C",
        "D",
        "E",
        "F",
        "G",
        "H",
        "I",
        "J",
        "K",
        "L",
        "M",
        "N",
        "O",
        "P",
        "Q",
        "R",
        "S",
        "T",
        "U",
        "V",
        "W",
        "X",
        "Y",
        "Z",
        "[",
        "\\",
        "]",
        "^",
        "_",
        "`",
        "a",
        "b",
        "c",
        "d",
        "e",
        "f",
        "g",
        "h",
        "i",
        "j",
        "k",
        "l",
        "m",
        "n",
        "o",
        "p",
        "q",
        "r",
        "s",
        "t",
        "u",
        "v",
        "w",
        "x",
        "y",
        "z",
        "{",
        "|",
        "}",
        "~",
    ]);
});
