// @generated by
// //server/agents/bots:write_cursor_cloud_agents_api_specification_types
/* eslint-disable @typescript-eslint/array-type */

export namespace CursorCloudAgentsApiSpecification {
    /**
     * This file was auto-generated by openapi-typescript. Do not make direct changes
     * to the file.
     */

    export interface paths {
        readonly "/v0/agents": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            /**
             * List agents @description List all cloud agents for the authenticated user
             */
            readonly get: operations["listAgents"];
            readonly put?: never;
            /**
             * Launch an agent @description Start a new cloud agent to work on your repository
             */
            readonly post: operations["createAgent"];
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
        readonly "/v0/agents/{id}": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            /**
             * Agent status @description Retrieve the current status and results of a cloud
             * agent
             */
            readonly get: operations["getAgent"];
            readonly put?: never;
            readonly post?: never;
            /**
             * Delete an agent @description Delete a cloud agent. This action is permanent and
             * cannot be undone.
             */
            readonly delete: operations["deleteAgent"];
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
        readonly "/v0/agents/{id}/followup": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly get?: never;
            readonly put?: never;
            /**
             * Add followup @description Add a followup instruction to an existing cloud agent
             */
            readonly post: operations["addFollowup"];
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
        readonly "/v0/agents/{id}/stop": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly get?: never;
            readonly put?: never;
            /**
             * Stop an agent @description Stop a running cloud agent. This pauses the agent's
             * execution without deleting it. Stopped agents cannot be resumed.
             */
            readonly post: operations["stopAgent"];
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
        readonly "/v0/agents/{id}/conversation": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            /**
             * Get agent conversation @description Retrieve the conversation history of a cloud
             * agent, including all user prompts and assistant responses
             */
            readonly get: operations["getAgentConversation"];
            readonly put?: never;
            readonly post?: never;
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
        readonly "/v0/me": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            /**
             * API key info @description Retrieve information about the API key being used for
             * authentication
             */
            readonly get: operations["getMe"];
            readonly put?: never;
            readonly post?: never;
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
        readonly "/v0/models": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            /**
             * List available models @description Retrieve a list of recommended models for
             * cloud agents
             */
            readonly get: operations["listModels"];
            readonly put?: never;
            readonly post?: never;
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
        readonly "/v0/repositories": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            /**
             * List GitHub repositories @description Retrieve a list of GitHub repositories
             * accessible to the authenticated user
             */
            readonly get: operations["listRepositories"];
            readonly put?: never;
            readonly post?: never;
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
    }
    export type webhooks = Record<string, never>;
    export interface components {
        schemas: {
            readonly ImageDimension: {
                /** @description Width must be a positive integer */
                readonly width: number;
                /** @description Height must be a positive integer */
                readonly height: number;
            };
            readonly Image: {
                /**
                 * @description Base64 encoded image data @example iVBORw0KGgoAAAANSUhEUgAA...
                 */
                readonly data: string;
                readonly dimension?: components["schemas"]["ImageDimension"];
            };
            readonly CreateAgentRequest: {
                readonly prompt: {
                    /**
                     * @description The task or instructions for the agent to execute @example Add a
                     * README.md file with installation instructions
                     */
                    readonly text: string;
                    /**
                     * @description Optional array of base64 encoded images (max 5) @example [ {
                     * "data": "iVBORw0KGgoAAAANSUhEUgAA...", "dimension": { "width": 1024, "height":
                     * 768 } } ]
                     */
                    readonly images?: readonly components["schemas"]["Image"][];
                };
                /**
                 * @description The LLM to use @example claude-4-sonnet
                 */
                readonly model?: string;
                readonly source: {
                    /**
                     * @description The GitHub repository URL. Required unless prUrl is provided.
                     * @example https://github.com/your-org/your-repo
                     */
                    readonly repository?: string;
                    /**
                     * @description Git ref (branch/tag) to use as the base branch @example main
                     */
                    readonly ref?: string;
                    /**
                     * Format: uri @description GitHub pull request URL. When provided, the agent works
                     * on this PR's repository and branches. Mutually exclusive with repository/ref.
                     * @example https://github.com/your-org/your-repo/pull/123
                     */
                    readonly prUrl?: string;
                };
                readonly target?: {
                    /**
                     * @description Whether to automatically create a pull request when the agent
                     * completes @default false
                     */
                    readonly autoCreatePr: boolean;
                    /**
                     * @description Whether to open the pull request as the Cursor GitHub App instead
                     * of as the user. Only applies if autoCreatePr is true. @default false
                     */
                    readonly openAsCursorGithubApp: boolean;
                    /**
                     * @description Whether to skip adding the user as a reviewer to the pull request.
                     * Only applies if autoCreatePr is true and the PR is opened as the Cursor GitHub
                     * App. @default false
                     */
                    readonly skipReviewerRequest: boolean;
                    /**
                     * @description Custom branch name for the agent to create @example
                     * feature/add-readme
                     */
                    readonly branchName?: string;
                    /**
                     * @description Whether to create a new branch (true) or use the PR's existing head
                     * branch (false). Only applies when source.prUrl is provided. @default true
                     */
                    readonly autoBranch: boolean;
                };
                readonly webhook?: {
                    /**
                     * Format: uri @description URL to receive webhook notifications about agent status
                     * changes @example https://example.com/webhooks/cursor-agent
                     */
                    readonly url: string;
                    /**
                     * @description Secret key for webhook payload verification @example
                     * your-webhook-secret-key-minimum-32-characters
                     */
                    readonly secret?: string;
                };
            };
            readonly Error: {
                readonly error?: {
                    /** @description Human-readable error message */
                    readonly message?: string;
                    /** @description Machine-readable error code */
                    readonly code?: string;
                };
            };
        };
        responses: never;
        parameters: never;
        requestBodies: never;
        headers: never;
        pathItems: never;
    }
    export type $defs = Record<string, never>;
    export interface operations {
        readonly listAgents: {
            readonly parameters: {
                readonly query?: {
                    /** @description Number of cloud agents to return */
                    readonly limit?: number;
                    /** @description Pagination cursor from the previous response */
                    readonly cursor?: string;
                    /** @description Filter agents by pull request URL */
                    readonly prUrl?: string;
                };
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description Agents retrieved successfully */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": {
                            /** @description List of agents */
                            readonly agents: readonly {
                                /**
                                 * @description Unique identifier for the cloud agent @example bc_abc123
                                 */
                                readonly id: string;
                                /**
                                 * @description Name for the agent @example Add README Documentation
                                 */
                                readonly name: string;
                                /**
                                 * @description Current status of the cloud agent @example RUNNING @enum {string}
                                 */
                                readonly status:
                                    | "RUNNING"
                                    | "FINISHED"
                                    | "ERROR"
                                    | "CREATING"
                                    | "EXPIRED";
                                readonly source: {
                                    /**
                                     * @description The GitHub repository URL @example
                                     * https://github.com/your-org/your-repo
                                     */
                                    readonly repository?: string;
                                    /**
                                     * @description Git ref (branch/tag) used as the base branch @example main
                                     */
                                    readonly ref?: string;
                                };
                                readonly target: {
                                    /**
                                     * @description The Git branch name where the agent is working @example
                                     * cursor/add-readme-1234
                                     */
                                    readonly branchName?: string;
                                    /**
                                     * @description URL to view the agent in Cursor Web @example
                                     * https://cursor.com/agents?id=bc_abc123
                                     */
                                    readonly url: string;
                                    /**
                                     * @description URL to view the pull request in GitHub, if any @example
                                     * https://github.com/your-org/your-repo/pull/1234
                                     */
                                    readonly prUrl?: string;
                                    /**
                                     * @description Whether a pull request will be automatically created @example false
                                     */
                                    readonly autoCreatePr?: boolean;
                                    /**
                                     * @description Whether the pull request will be opened as the Cursor GitHub App
                                     * @example false
                                     */
                                    readonly openAsCursorGithubApp?: boolean;
                                    /**
                                     * @description Whether to skip adding the user as a reviewer to the pull request
                                     * @example false
                                     */
                                    readonly skipReviewerRequest?: boolean;
                                };
                                /**
                                 * @description Summary of the agent's work @example Added README.md with
                                 * installation instructions and usage examples
                                 */
                                readonly summary?: string;
                                /**
                                 * Format: date-time @description When the agent was created @example
                                 * 2024-01-15T10:30:00Z
                                 */
                                readonly createdAt: string;
                            }[];
                            /**
                             * @description Cursor for fetching the next page of results @example bc_def456
                             */
                            readonly nextCursor?: string;
                        };
                    };
                };
                /** @description Invalid request - bad query parameters */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized - invalid or missing API key */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden - insufficient permissions */
                readonly 403: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limit exceeded */
                readonly 429: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                readonly 500: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        readonly createAgent: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": components["schemas"]["CreateAgentRequest"];
                };
            };
            readonly responses: {
                /** @description Agent created successfully */
                readonly 201: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": {
                            /**
                             * @description Unique identifier for the cloud agent @example bc_abc123
                             */
                            readonly id: string;
                            /**
                             * @description Name for the agent @example Add README Documentation
                             */
                            readonly name: string;
                            /**
                             * @description Initial status of the newly created agent @example CREATING @enum
                             * {string}
                             */
                            readonly status: "CREATING";
                            readonly source: {
                                /**
                                 * @description The GitHub repository URL @example
                                 * https://github.com/your-org/your-repo
                                 */
                                readonly repository: string;
                                /**
                                 * @description Git ref (branch/tag) used as the base branch @example main
                                 */
                                readonly ref?: string;
                            };
                            readonly target: {
                                /**
                                 * @description The Git branch name where the agent is working @example
                                 * cursor/add-readme-1234
                                 */
                                readonly branchName?: string;
                                /**
                                 * @description URL to view the agent in Cursor Web @example
                                 * https://cursor.com/agents?id=bc_abc123
                                 */
                                readonly url: string;
                                /**
                                 * @description URL of the pull request, if agent was created from a PR @example
                                 * https://github.com/your-org/your-repo/pull/123
                                 */
                                readonly prUrl?: string;
                                /**
                                 * @description Whether a pull request will be automatically created @example false
                                 */
                                readonly autoCreatePr?: boolean;
                                /**
                                 * @description Whether the pull request will be opened as the Cursor GitHub App
                                 * @example false
                                 */
                                readonly openAsCursorGithubApp?: boolean;
                                /**
                                 * @description Whether to skip adding the user as a reviewer to the pull request
                                 * @example false
                                 */
                                readonly skipReviewerRequest?: boolean;
                            };
                            /**
                             * Format: date-time @description When the agent was created @example
                             * 2024-01-15T10:30:00Z
                             */
                            readonly createdAt: string;
                        };
                    };
                };
                /** @description Invalid request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized - invalid or missing API key */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /**
                 * @description Forbidden - insufficient permissions, plan limits exceeded, or
                 * storage full
                 */
                readonly 403: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limit exceeded */
                readonly 429: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                readonly 500: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        readonly getAgent: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    /** @description Unique identifier for the cloud agent */
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description Agent details retrieved successfully */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": {
                            /**
                             * @description Unique identifier for the cloud agent @example bc_abc123
                             */
                            readonly id: string;
                            /**
                             * @description Name for the agent @example Add README Documentation
                             */
                            readonly name: string;
                            /**
                             * @description Current status of the cloud agent @example RUNNING @enum {string}
                             */
                            readonly status:
                                | "RUNNING"
                                | "FINISHED"
                                | "ERROR"
                                | "CREATING"
                                | "EXPIRED";
                            readonly source: {
                                /**
                                 * @description The GitHub repository URL @example
                                 * https://github.com/your-org/your-repo
                                 */
                                readonly repository?: string;
                                /**
                                 * @description Git ref (branch/tag) used as the base branch @example main
                                 */
                                readonly ref?: string;
                            };
                            readonly target: {
                                /**
                                 * @description The Git branch name where the agent is working @example
                                 * cursor/add-readme-1234
                                 */
                                readonly branchName?: string;
                                /**
                                 * @description URL to view the agent in Cursor Web @example
                                 * https://cursor.com/agents?id=bc_abc123
                                 */
                                readonly url: string;
                                /**
                                 * @description URL to view the pull request in GitHub, if any @example
                                 * https://github.com/your-org/your-repo/pull/1234
                                 */
                                readonly prUrl?: string;
                                /**
                                 * @description Whether a pull request will be automatically created @example false
                                 */
                                readonly autoCreatePr?: boolean;
                                /**
                                 * @description Whether the pull request will be opened as the Cursor GitHub App
                                 * @example false
                                 */
                                readonly openAsCursorGithubApp?: boolean;
                                /**
                                 * @description Whether to skip adding the user as a reviewer to the pull request
                                 * @example false
                                 */
                                readonly skipReviewerRequest?: boolean;
                            };
                            /**
                             * @description Summary of the agent's work @example Added README.md with
                             * installation instructions and usage examples
                             */
                            readonly summary?: string;
                            /**
                             * Format: date-time @description When the agent was created @example
                             * 2024-01-15T10:30:00Z
                             */
                            readonly createdAt: string;
                        };
                    };
                };
                /** @description Invalid request - bad agent ID format */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized - invalid or missing API key */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden - insufficient permissions */
                readonly 403: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Agent not found or access denied */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limit exceeded */
                readonly 429: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                readonly 500: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        readonly deleteAgent: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    /** @description Unique identifier for the cloud agent */
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description Agent deleted successfully */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": {
                            /**
                             * @description Unique identifier for the cloud agent @example bc_abc123
                             */
                            readonly id: string;
                        };
                    };
                };
                /** @description Invalid request - bad agent ID format */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized - invalid or missing API key */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden - insufficient permissions */
                readonly 403: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Agent not found or access denied */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Conflict - agent is deleted or archived */
                readonly 409: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limit exceeded */
                readonly 429: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                readonly 500: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        readonly addFollowup: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    /** @description Unique identifier for the cloud agent */
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": {
                        readonly prompt: {
                            /**
                             * @description The followup instruction for the agent @example Also add a section
                             * about troubleshooting
                             */
                            readonly text: string;
                            /**
                             * @description Optional array of base64 encoded images (max 5) @example [ {
                             * "data": "iVBORw0KGgoAAAANSUhEUgAA...", "dimension": { "width": 1024, "height":
                             * 768 } } ]
                             */
                            readonly images?: readonly components["schemas"]["Image"][];
                        };
                    };
                };
            };
            readonly responses: {
                /** @description Followup added successfully */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": {
                            /**
                             * @description Unique identifier for the cloud agent @example bc_abc123
                             */
                            readonly id: string;
                        };
                    };
                };
                /**
                 * @description Invalid request - bad agent ID format or invalid request body
                 */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized - invalid or missing API key */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden - insufficient permissions */
                readonly 403: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Agent not found or access denied */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Conflict - agent is deleted or archived */
                readonly 409: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limit exceeded */
                readonly 429: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                readonly 500: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        readonly stopAgent: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    /** @description Unique identifier for the cloud agent */
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description Agent stopped successfully */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": {
                            /**
                             * @description Unique identifier for the cloud agent @example bc_abc123
                             */
                            readonly id: string;
                        };
                    };
                };
                /** @description Invalid request - bad agent ID format */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized - invalid or missing API key */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden - insufficient permissions */
                readonly 403: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Agent not found or access denied */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Conflict - agent is deleted or archived */
                readonly 409: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limit exceeded */
                readonly 429: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                readonly 500: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        readonly getAgentConversation: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    /** @description Unique identifier for the cloud agent */
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description Conversation retrieved successfully */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": {
                            /**
                             * @description Unique identifier for the cloud agent @example bc_abc123
                             */
                            readonly id: string;
                            /** @description Array of conversation messages ordered chronologically */
                            readonly messages: readonly {
                                /**
                                 * @description Unique identifier for the message @example msg_123
                                 */
                                readonly id: string;
                                /**
                                 * @description Type of message - either from the user or the model @example
                                 * user_message @enum {string}
                                 */
                                readonly type: "user_message" | "assistant_message";
                                /**
                                 * @description The content of the message @example Add a README.md file with
                                 * installation instructions
                                 */
                                readonly text: string;
                            }[];
                        };
                    };
                };
                /** @description Invalid request - bad agent ID format */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized - invalid or missing API key */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden - insufficient permissions */
                readonly 403: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Agent not found or access denied */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Conflict - agent is deleted or archived */
                readonly 409: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limit exceeded */
                readonly 429: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                readonly 500: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        readonly getMe: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description API key information retrieved successfully */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": {
                            /**
                             * @description The name of the API key @example Production API Key
                             */
                            readonly apiKeyName: string;
                            /**
                             * Format: date-time @description When the API key was created @example
                             * 2024-01-15T10:30:00Z
                             */
                            readonly createdAt: string;
                            /**
                             * Format: email @description Email address of the user who owns the API key (if
                             * available) @example developer@example.com
                             */
                            readonly userEmail?: string;
                        };
                    };
                };
                /** @description Unauthorized - invalid or missing API key */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description API key not found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limit exceeded */
                readonly 429: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                readonly 500: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        readonly listModels: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description Models retrieved successfully */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": {
                            /**
                             * @description Array of available model names @example [
                             * "claude-4-sonnet-thinking", "gpt-5.2", "claude-4.5-sonnet-thinking" ]
                             */
                            readonly models: readonly string[];
                        };
                    };
                };
                /** @description Unauthorized - invalid or missing API key */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limit exceeded */
                readonly 429: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                readonly 500: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        readonly listRepositories: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description Repositories retrieved successfully */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": {
                            /** @description Array of GitHub repositories the user has access to */
                            readonly repositories: readonly {
                                /**
                                 * @description The owner of the repository (user or organization) @example
                                 * your-org
                                 */
                                readonly owner: string;
                                /**
                                 * @description The name of the repository @example your-repo
                                 */
                                readonly name: string;
                                /**
                                 * Format: uri @description The full URL to the GitHub repository @example
                                 * https://github.com/your-org/your-repo
                                 */
                                readonly repository: string;
                            }[];
                        };
                    };
                };
                /** @description Unauthorized - invalid or missing API key */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limit exceeded */
                readonly 429: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal server error */
                readonly 500: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
    }
}
