import {RpcDefinition} from "~/shared/rpc/rpc_definition.js";

// The implementation of this file is generated by Bazel. It imports all the files
// in `~/shared/rpc` and exports their definitions.

export const allRpcDefinitions: ReadonlyMap<string, RpcDefinition<any, any>>;
