// @generated by //admin/dynamo:write_schema

/**
 * A list of keys to replace `*` in the `dynamodb.consumed_capacity.*` event
 * attribute. It is generated by
 * `generate_tracer_event_data_dynamo_consumed_capacity_keys_main.ts`.
 *
 * We need a list of DynamoDB tables so we generate it from `//server/dynamo`
 * instead of importing `//server/dynamo` at runtime. That way code which
 * doesn't directly depend on DynamoDB doesn't need to pay the runtime cost of
 * initializing DynamoDB tables.
 *
 * We commit the file so there isn't a package dependency on `//server/dynamo`
 * either which our dev server would see and rebuild `//server/tracer`
 * dependents on `//server/dynamo` changes.
 */
export const tracerEventDataDynamoConsumedCapacityKeys = [
    "Accounts",
    "AlphaAccess",
    "Chat",
    "Documents",
    "Forum",
    "Inbox",
    "Spaces",
    "TaskActions",
    "Tasks",
    "Chat_Index1",
    "Forum_Index1",
    "Inbox_Index1",
];
