load("//admin/typescript:typescript.bzl", "ts_project")

ts_project(
    name = "docs",
    visibility = ["//visibility:public"],
    deps = [
        "//shared/error:error_core",
        "//shared/helpers",
    ],
)
