import fs from "fs-extra";
import opentype from "opentype.js";
import {join as joinPath} from "path";
import wawoff2 from "wawoff2";
import {runfilesPath} from "~/server/helpers/node/runfiles_path.js";
import {assert} from "~/shared/helpers/control/assert.js";
import {assertExists} from "~/shared/helpers/control/assert_exists.js";

main().catch(error => {
    // eslint-disable-next-line no-console
    console.error(error);
    process.exitCode = 1;
});

async function main() {
    const commitMonoFontContents = await fs
        .readFile(joinPath(runfilesPath, "cyberworlds/app/static/fonts/commit-mono.woff2"))
        .then(contents => wawoff2.decompress(contents))
        .then(array => array.buffer.slice(array.byteOffset, array.byteOffset + array.byteLength));

    // We run into issues when trying to read/decompress in parallel. Presumably
    // the WebAssembly module has issues with parallelism.
    const interFontContents = await fs
        .readFile(joinPath(runfilesPath, "cyberworlds/app/static/fonts/inter.woff2"))
        .then(contents => wawoff2.decompress(contents))
        .then(array => array.buffer.slice(array.byteOffset, array.byteOffset + array.byteLength));

    const commitMonoFont = opentype.parse(commitMonoFontContents);
    const interFont = opentype.parse(interFontContents);

    assert("os2" in interFont.tables);
    assert("os2" in commitMonoFont.tables);

    const interFontAscenderPercentage = interFont.ascender / interFont.unitsPerEm;
    const interFontDescenderPercentage = interFont.descender / interFont.unitsPerEm;

    // Make sure the x-height of our monospace font matches the x-height of Inter.
    const commitMonoFontSizeAdjust =
        interFont.tables.os2.sxHeight /
        interFont.unitsPerEm /
        (commitMonoFont.tables.os2.sxHeight / commitMonoFont.unitsPerEm);

    // We want Commit Mono to have the same ascender/descender proportions as
    // Inter. This means in the browser `background-color`s, font sizes, line
    // heights, everything set on this font will line up with our main font Inter.
    //
    // Ideally this is handled by the CSS `ascent-override` and `descent-override`
    // but unfortunately Safari doesn't support those CSS properties so to better
    // support Safari we update our font with the correct metrics.
    const newCommitMonoFontAscender = Math.round(
        interFontAscenderPercentage * (commitMonoFont.unitsPerEm / commitMonoFontSizeAdjust),
    );
    const newCommitMonoFontDescender = Math.round(
        interFontDescenderPercentage * (commitMonoFont.unitsPerEm / commitMonoFontSizeAdjust),
    );

    let interDigitGlyphMaxAdvanceWidth = 0;

    for (const char of "0123456789".split("")) {
        const glyph = interFont.charToGlyph(char);
        assert(glyph.advanceWidth);

        if (glyph.advanceWidth > interDigitGlyphMaxAdvanceWidth) {
            interDigitGlyphMaxAdvanceWidth = glyph.advanceWidth;
        }
    }

    const interTabularZeroGlyph = assertExists(
        getSubstitutedGlyph(interFont, interFont.charToGlyph("0"), "tnum"),
    );

    const interTabularZeroGlyphAdvanceWidth = interTabularZeroGlyph.advanceWidth;

    await fs.writeFile(
        "fonts/font_metrics.ts",
        `// @generated by //shared/design:write_font_metrics

export const interFontAscender: number = ${interFont.ascender};
export const interFontDescender: number = ${-interFont.descender};
export const interFontUnitsPerEm: number = ${interFont.unitsPerEm};
export const interFontXHeight: number = ${interFont.tables.os2.sxHeight};
export const interFontCapHeight: number = ${interFont.tables.os2.sCapHeight};
export const interDigitGlyphMaxAdvanceWidth: number = ${interDigitGlyphMaxAdvanceWidth};
export const interTabularZeroGlyphAdvanceWidth: number = ${interTabularZeroGlyphAdvanceWidth};

export const commitMonoFontAscender: number = ${newCommitMonoFontAscender};
export const commitMonoFontDescender: number = ${-newCommitMonoFontDescender};
export const commitMonoFontUnitsPerEm: number = ${commitMonoFont.unitsPerEm};
export const commitMonoFontXHeight: number = ${commitMonoFont.tables.os2.sxHeight};
export const commitMonoFontCapHeight: number = ${commitMonoFont.tables.os2.sCapHeight};

export const commitMonoFontSizeAdjust: number = ${commitMonoFontSizeAdjust};
`,
    );

    const commitMonoTtxPatchTemplate = await fs.readFile(
        joinPath(runfilesPath, "cyberworlds/app/static/fonts/commit-mono.ttx.patch.template"),
        "utf8",
    );

    const commitMonoTtxPatch = commitMonoTtxPatchTemplate
        .replaceAll("{{newCommitMonoFontAscender}}", `${newCommitMonoFontAscender}`)
        .replaceAll("{{newCommitMonoFontDescender}}", `${-newCommitMonoFontDescender}`);

    await fs.writeFile("fonts/commit-mono.ttx.patch", commitMonoTtxPatch);
}

// NOTE(calebmer): Generated by Claude. I don't understand this code.
function getSubstitutedGlyph(font: opentype.Font, glyph: opentype.Glyph, featureTag: string) {
    const {gsub} = font.tables;
    if (!gsub) return null;

    // Find the feature
    const feature = gsub.features.find((feature: any) => feature.tag === featureTag);
    if (!feature) return null;

    // Look through the lookups referenced by this feature
    for (const lookupIndex of feature.feature.lookupListIndexes) {
        const lookup = gsub.lookups[lookupIndex];

        for (const subtable of lookup.subtables) {
            // Handle single substitution (type 1)
            if (subtable.coverage && subtable.substitute) {
                const coverageIndex = getCoverageIndex(subtable.coverage, glyph.index);
                if (coverageIndex !== -1) {
                    const newGlyphIndex = subtable.substitute[coverageIndex];
                    return font.glyphs.get(newGlyphIndex);
                }
            }
        }
    }
    return null;
}

// NOTE(calebmer): Generated by Claude. I don't understand this code.
function getCoverageIndex(coverage: any, glyphIndex: number) {
    if (coverage.format === 1) {
        return coverage.glyphs.indexOf(glyphIndex);
    } else if (coverage.format === 2) {
        for (let i = 0; i < coverage.ranges.length; i++) {
            const range = coverage.ranges[i];
            if (glyphIndex >= range.start && glyphIndex <= range.end) {
                return range.index + (glyphIndex - range.start);
            }
        }
    }
    return -1;
}
