load("//admin/typescript:typescript.bzl", "ts_project")

ts_project(
    name = "sites",
    visibility = ["//visibility:public"],
    deps = [
        "//shared/access",
        "//shared/dynamo",
        "//shared/error",
        "//shared/files",
        "//shared/helpers",
        "//shared/id",
        "//shared/schema",
        "//shared/search",
        "//shared/web_socket",
    ],
)
