load("//admin/typescript:typescript.bzl", "ts_project")

ts_project(
    name = "sites",
    visibility = ["//visibility:public"],
    deps = [
        "//shared/access",
        "//shared/id",
        "//shared/helpers",
        "//shared/schema",
        "//shared/search"
    ],
)
