load("//admin/typescript:typescript.bzl", "ts_project")

ts_project(
    name = "accounts",
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//shared/avatar",
        "//shared/helpers",
        "//shared/id",
        "//shared/reactions",
        "//shared/schema",
    ],
)
