// @generated by //shared/api/specification:write_specification

import {ApiSpecification} from "~/shared/api/specification/types/api_specification_types.open_source.js";

export type ApiContentPosition = ApiSpecification.components["schemas"]["ContentPosition"];

export type ApiContentInlinePosition =
    ApiSpecification.components["schemas"]["ContentInlinePosition"];

export type ApiContentBeforePosition =
    ApiSpecification.components["schemas"]["ContentBeforePosition"];

export type ApiContentAfterPosition =
    ApiSpecification.components["schemas"]["ContentAfterPosition"];

export type ApiContentRange = ApiSpecification.components["schemas"]["ContentRange"];

export type ApiTaskCollectionColor = ApiSpecification.components["schemas"]["TaskCollectionColor"];

export type ApiAccountReferenceRequest =
    ApiSpecification.components["schemas"]["AccountReference_Request"];

export type ApiAccountReference = ApiSpecification.components["schemas"]["AccountReference"];

export type ApiChannelReferenceRequest =
    ApiSpecification.components["schemas"]["ChannelReference_Request"];

export type ApiChannelReference = ApiSpecification.components["schemas"]["ChannelReference"];

export type ApiChatReferenceRequest =
    ApiSpecification.components["schemas"]["ChatReference_Request"];

export type ApiChatReference = ApiSpecification.components["schemas"]["ChatReference"];

export type ApiDocumentReferenceRequest =
    ApiSpecification.components["schemas"]["DocumentReference_Request"];

export type ApiDocumentReference = ApiSpecification.components["schemas"]["DocumentReference"];

export type ApiPostReferenceRequest =
    ApiSpecification.components["schemas"]["PostReference_Request"];

export type ApiPostReference = ApiSpecification.components["schemas"]["PostReference"];

export type ApiTaskReferenceRequest =
    ApiSpecification.components["schemas"]["TaskReference_Request"];

export type ApiTaskReference = ApiSpecification.components["schemas"]["TaskReference"];

export type ApiTaskCollectionReferenceRequest =
    ApiSpecification.components["schemas"]["TaskCollectionReference_Request"];

export type ApiTaskCollectionReference =
    ApiSpecification.components["schemas"]["TaskCollectionReference"];

export type ApiSiteReferenceRequest =
    ApiSpecification.components["schemas"]["SiteReference_Request"];

export type ApiSiteReference = ApiSpecification.components["schemas"]["SiteReference"];

export type ApiMentionReference = ApiSpecification.components["schemas"]["MentionReference"];

export type ApiPreviewReference = ApiSpecification.components["schemas"]["PreviewReference"];

export type ApiAuth = ApiSpecification.components["schemas"]["Auth"];

export type ApiBotAccountAuth = ApiSpecification.components["schemas"]["BotAccountAuth"];

export type ApiContent = ApiSpecification.components["schemas"]["Content"];

export type ApiContentBlockElement = ApiSpecification.components["schemas"]["ContentBlockElement"];

export type ApiContentParagraphBlockElementRequest =
    ApiSpecification.components["schemas"]["ContentParagraphBlockElement_Request"];

export type ApiContentParagraphBlockElement =
    ApiSpecification.components["schemas"]["ContentParagraphBlockElement"];

export type ApiContentParagraphBlockElementWithoutKeys =
    ApiSpecification.components["schemas"]["ContentParagraphBlockElement_WithoutKeys"];

export type ApiContentListBlockElement =
    ApiSpecification.components["schemas"]["ContentListBlockElement"];

export type ApiContentUnorderedListBlockElement =
    ApiSpecification.components["schemas"]["ContentUnorderedListBlockElement"];

export type ApiContentOrderedListBlockElement =
    ApiSpecification.components["schemas"]["ContentOrderedListBlockElement"];

export type ApiContentCheckListBlockElement =
    ApiSpecification.components["schemas"]["ContentCheckListBlockElement"];

export type ApiContentListBlockElementItem =
    ApiSpecification.components["schemas"]["ContentListBlockElementItem"];

export type ApiContentCheckListBlockElementItem =
    ApiSpecification.components["schemas"]["ContentCheckListBlockElementItem"];

export type ApiContentQuoteBlockElement =
    ApiSpecification.components["schemas"]["ContentQuoteBlockElement"];

export type ApiContentQuoteBlockElementBlockElement =
    ApiSpecification.components["schemas"]["ContentQuoteBlockElementBlockElement"];

export type ApiContentHeadingBlockElementRequest =
    ApiSpecification.components["schemas"]["ContentHeadingBlockElement_Request"];

export type ApiContentHeadingBlockElement =
    ApiSpecification.components["schemas"]["ContentHeadingBlockElement"];

export type ApiContentHeadingBlockElementWithoutKeys =
    ApiSpecification.components["schemas"]["ContentHeadingBlockElement_WithoutKeys"];

export type ApiContentDividerBlockElementRequest =
    ApiSpecification.components["schemas"]["ContentDividerBlockElement_Request"];

export type ApiContentDividerBlockElement =
    ApiSpecification.components["schemas"]["ContentDividerBlockElement"];

export type ApiContentDividerBlockElementWithoutKeys =
    ApiSpecification.components["schemas"]["ContentDividerBlockElement_WithoutKeys"];

export type ApiContentTableBlockElement =
    ApiSpecification.components["schemas"]["ContentTableBlockElement"];

export type ApiContentTableBlockElementRow =
    ApiSpecification.components["schemas"]["ContentTableBlockElementRow"];

export type ApiContentTableBlockElementCell =
    ApiSpecification.components["schemas"]["ContentTableBlockElementCell"];

export type ApiContentTableBlockElementCellBlockElement =
    ApiSpecification.components["schemas"]["ContentTableBlockElementCellBlockElement"];

export type ApiContentCodeBlockElement =
    ApiSpecification.components["schemas"]["ContentCodeBlockElement"];

export type ApiContentCodeBlockElementLineRequest =
    ApiSpecification.components["schemas"]["ContentCodeBlockElementLine_Request"];

export type ApiContentCodeBlockElementLine =
    ApiSpecification.components["schemas"]["ContentCodeBlockElementLine"];

export type ApiContentCodeBlockElementLineWithoutKeys =
    ApiSpecification.components["schemas"]["ContentCodeBlockElementLine_WithoutKeys"];

export type ApiContentFileBlockElementRequest =
    ApiSpecification.components["schemas"]["ContentFileBlockElement_Request"];

export type ApiContentFileBlockElement =
    ApiSpecification.components["schemas"]["ContentFileBlockElement"];

export type ApiContentFileBlockElementWithoutKeys =
    ApiSpecification.components["schemas"]["ContentFileBlockElement_WithoutKeys"];

export type ApiContentFileBlockElementFileRequest =
    ApiSpecification.components["schemas"]["ContentFileBlockElementFile_Request"];

export type ApiContentFileBlockElementFile =
    ApiSpecification.components["schemas"]["ContentFileBlockElementFile"];

export type ApiContentPreviewBlockElementRequest =
    ApiSpecification.components["schemas"]["ContentPreviewBlockElement_Request"];

export type ApiContentPreviewBlockElement =
    ApiSpecification.components["schemas"]["ContentPreviewBlockElement"];

export type ApiContentPreviewBlockElementWithoutKeys =
    ApiSpecification.components["schemas"]["ContentPreviewBlockElement_WithoutKeys"];

export type ApiContentFileGalleryBlockElement =
    ApiSpecification.components["schemas"]["ContentFileGalleryBlockElement"];

export type ApiContentFileGalleryBlockElementRow =
    ApiSpecification.components["schemas"]["ContentFileGalleryBlockElementRow"];

export type ApiContentFileGalleryBlockElementRowItemRequest =
    ApiSpecification.components["schemas"]["ContentFileGalleryBlockElementRowItem_Request"];

export type ApiContentFileGalleryBlockElementRowItem =
    ApiSpecification.components["schemas"]["ContentFileGalleryBlockElementRowItem"];

export type ApiContentFileFloatBlockElement =
    ApiSpecification.components["schemas"]["ContentFileFloatBlockElement"];

export type ApiContentInlineElement =
    ApiSpecification.components["schemas"]["ContentInlineElement"];

export type ApiContentTextInlineElement =
    ApiSpecification.components["schemas"]["ContentTextInlineElement"];

export type ApiContentBreakInlineElement =
    ApiSpecification.components["schemas"]["ContentBreakInlineElement"];

export type ApiContentMentionInlineElement =
    ApiSpecification.components["schemas"]["ContentMentionInlineElement"];

export type ApiContentInlineElementMark =
    ApiSpecification.components["schemas"]["ContentInlineElementMark"];

export type ApiContentBoldMark = ApiSpecification.components["schemas"]["ContentBoldMark"];

export type ApiContentItalicMark = ApiSpecification.components["schemas"]["ContentItalicMark"];

export type ApiContentStrikeMark = ApiSpecification.components["schemas"]["ContentStrikeMark"];

export type ApiContentLinkMark = ApiSpecification.components["schemas"]["ContentLinkMark"];

export type ApiContentCodeMark = ApiSpecification.components["schemas"]["ContentCodeMark"];

export type ApiContentHighlightMark =
    ApiSpecification.components["schemas"]["ContentHighlightMark"];

export type ApiContentHighlightMarkColor =
    ApiSpecification.components["schemas"]["ContentHighlightMarkColor"];

export type ApiContentCommentMark = ApiSpecification.components["schemas"]["ContentCommentMark"];

export type ApiContentCodeBlockElementTextInlineElement =
    ApiSpecification.components["schemas"]["ContentCodeBlockElementTextInlineElement"];

export type ApiContentCodeBlockElementTextInlineElementMark =
    ApiSpecification.components["schemas"]["ContentCodeBlockElementTextInlineElementMark"];

export type ApiLabelContent = ApiSpecification.components["schemas"]["LabelContent"];

export type ApiLabelContentInlineElement =
    ApiSpecification.components["schemas"]["LabelContentInlineElement"];

export type ApiLabelContentInlineElementMark =
    ApiSpecification.components["schemas"]["LabelContentInlineElementMark"];

export type ApiLabelContentTextInlineElement =
    ApiSpecification.components["schemas"]["LabelContentTextInlineElement"];

export type ApiLabelContentMentionInlineElement =
    ApiSpecification.components["schemas"]["LabelContentMentionInlineElement"];

export type ApiAccountWithoutSpace = ApiSpecification.components["schemas"]["AccountWithoutSpace"];

export type ApiSpace = ApiSpecification.components["schemas"]["Space"];

export type ApiAccountRequest = ApiSpecification.components["schemas"]["Account_Request"];

export type ApiAccount = ApiSpecification.components["schemas"]["Account"];

export type ApiBotAccount = ApiSpecification.components["schemas"]["BotAccount"];

export type ApiAccountSpace = ApiSpecification.components["schemas"]["AccountSpace"];

export type ApiAccountSpaceInactive =
    ApiSpecification.components["schemas"]["AccountSpaceInactive"];

export type ApiAccountSpaceRemovedInactive =
    ApiSpecification.components["schemas"]["AccountSpaceRemovedInactive"];

export type ApiAccountSpaceInvitePendingInactive =
    ApiSpecification.components["schemas"]["AccountSpaceInvitePendingInactive"];

export type ApiInbox = ApiSpecification.components["schemas"]["Inbox"];

export type ApiInboxEntryTitleItem = ApiSpecification.components["schemas"]["InboxEntryTitleItem"];

export type ApiInboxEntryTitleTextItem =
    ApiSpecification.components["schemas"]["InboxEntryTitleTextItem"];

export type ApiInboxEntryTitleAccountItem =
    ApiSpecification.components["schemas"]["InboxEntryTitleAccountItem"];

export type ApiInboxEntryPreviewItem =
    ApiSpecification.components["schemas"]["InboxEntryPreviewItem"];

export type ApiInboxEntryPreviewTextItem =
    ApiSpecification.components["schemas"]["InboxEntryPreviewTextItem"];

export type ApiInboxEntryPreviewAccountItem =
    ApiSpecification.components["schemas"]["InboxEntryPreviewAccountItem"];

export type ApiInboxEntryAccountFeatured =
    ApiSpecification.components["schemas"]["InboxEntryAccountFeatured"];

export type ApiInboxEntry = ApiSpecification.components["schemas"]["InboxEntry"];

export type ApiInboxChatEntry = ApiSpecification.components["schemas"]["InboxChatEntry"];

export type ApiInboxCreatedChannelPostsEntry =
    ApiSpecification.components["schemas"]["InboxCreatedChannelPostsEntry"];

export type ApiInboxPostEntry = ApiSpecification.components["schemas"]["InboxPostEntry"];

export type ApiInboxCreatedDocumentThreadsEntry =
    ApiSpecification.components["schemas"]["InboxCreatedDocumentThreadsEntry"];

export type ApiInboxDocumentThreadEntry =
    ApiSpecification.components["schemas"]["InboxDocumentThreadEntry"];

export type ApiInboxTaskMessagesEntry =
    ApiSpecification.components["schemas"]["InboxTaskMessagesEntry"];

export type ApiChat = ApiSpecification.components["schemas"]["Chat"];

export type ApiDirectChat = ApiSpecification.components["schemas"]["DirectChat"];

export type ApiRoomChat = ApiSpecification.components["schemas"]["RoomChat"];

export type ApiChatCreateRequest = ApiSpecification.components["schemas"]["ChatCreate_Request"];

export type ApiDirectChatCreateRequest =
    ApiSpecification.components["schemas"]["DirectChatCreate_Request"];

export type ApiRoomChatCreateRequest =
    ApiSpecification.components["schemas"]["RoomChatCreate_Request"];

export type ApiDocument = ApiSpecification.components["schemas"]["Document"];

export type ApiDocumentSetTitlePatch =
    ApiSpecification.components["schemas"]["DocumentSetTitlePatch"];

export type ApiDocumentThread = ApiSpecification.components["schemas"]["DocumentThread"];

export type ApiDocumentThreadPatch = ApiSpecification.components["schemas"]["DocumentThreadPatch"];

export type ApiDocumentThreadResolvePatch =
    ApiSpecification.components["schemas"]["DocumentThreadResolvePatch"];

export type ApiDocumentThreadUnresolvePatch =
    ApiSpecification.components["schemas"]["DocumentThreadUnresolvePatch"];

export type ApiDocumentThreadWithPreview =
    ApiSpecification.components["schemas"]["DocumentThreadWithPreview"];

export type ApiChannelPreview = ApiSpecification.components["schemas"]["ChannelPreview"];

export type ApiChannel = ApiSpecification.components["schemas"]["Channel"];

export type ApiChannelSetNamePatch = ApiSpecification.components["schemas"]["ChannelSetNamePatch"];

export type ApiPost = ApiSpecification.components["schemas"]["Post"];

export type ApiPostPreview = ApiSpecification.components["schemas"]["PostPreview"];

export type ApiTaskQueryItem = ApiSpecification.components["schemas"]["TaskQueryItem"];

export type ApiTask = ApiSpecification.components["schemas"]["Task"];

export type ApiTaskWithNotes = ApiSpecification.components["schemas"]["TaskWithNotes"];

export type ApiTaskSubtasks = ApiSpecification.components["schemas"]["TaskSubtasks"];

export type ApiTaskDue = ApiSpecification.components["schemas"]["TaskDue"];

export type ApiTaskPriority = ApiSpecification.components["schemas"]["TaskPriority"];

export type ApiTaskLowPriority = ApiSpecification.components["schemas"]["TaskLowPriority"];

export type ApiTaskMediumPriority = ApiSpecification.components["schemas"]["TaskMediumPriority"];

export type ApiTaskHighPriority = ApiSpecification.components["schemas"]["TaskHighPriority"];

export type ApiTaskUrgentPriority = ApiSpecification.components["schemas"]["TaskUrgentPriority"];

export type ApiTaskNotes = ApiSpecification.components["schemas"]["TaskNotes"];

export type ApiTaskLayout = ApiSpecification.components["schemas"]["TaskLayout"];

export type ApiTaskParentRequest = ApiSpecification.components["schemas"]["TaskParent_Request"];

export type ApiTaskParent = ApiSpecification.components["schemas"]["TaskParent"];

export type ApiTaskCollectionItem = ApiSpecification.components["schemas"]["TaskCollectionItem"];

export type ApiTaskCreateRequest = ApiSpecification.components["schemas"]["TaskCreate_Request"];

export type ApiTaskSetTitlePatch = ApiSpecification.components["schemas"]["TaskSetTitlePatch"];

export type ApiTaskSetStatusPatch = ApiSpecification.components["schemas"]["TaskSetStatusPatch"];

export type ApiTaskSetDuePatch = ApiSpecification.components["schemas"]["TaskSetDuePatch"];

export type ApiTaskSetPriorityPatch =
    ApiSpecification.components["schemas"]["TaskSetPriorityPatch"];

export type ApiTaskSetLayoutPatch = ApiSpecification.components["schemas"]["TaskSetLayoutPatch"];

export type ApiTaskMoveInParentPatch =
    ApiSpecification.components["schemas"]["TaskMoveInParentPatch"];

export type ApiTaskRemoveCollectionPatch =
    ApiSpecification.components["schemas"]["TaskRemoveCollectionPatch"];

export type ApiTaskMoveInCollectionPatch =
    ApiSpecification.components["schemas"]["TaskMoveInCollectionPatch"];

export type ApiTaskMoveInQueryPatchPosition =
    ApiSpecification.components["schemas"]["TaskMoveInQueryPatchPosition"];

export type ApiTaskMoveInQueryPatchStartPosition =
    ApiSpecification.components["schemas"]["TaskMoveInQueryPatchStartPosition"];

export type ApiTaskMoveInQueryPatchEndPosition =
    ApiSpecification.components["schemas"]["TaskMoveInQueryPatchEndPosition"];

export type ApiTaskMoveInQueryPatchBetweenPosition =
    ApiSpecification.components["schemas"]["TaskMoveInQueryPatchBetweenPosition"];

export type ApiTaskPatchResult = ApiSpecification.components["schemas"]["TaskPatchResult"];

export type ApiTaskSetTitlePatchResult =
    ApiSpecification.components["schemas"]["TaskSetTitlePatchResult"];

export type ApiTaskSetAssigneePatchResult =
    ApiSpecification.components["schemas"]["TaskSetAssigneePatchResult"];

export type ApiTaskSetStatusPatchResult =
    ApiSpecification.components["schemas"]["TaskSetStatusPatchResult"];

export type ApiTaskSetDuePatchResult =
    ApiSpecification.components["schemas"]["TaskSetDuePatchResult"];

export type ApiTaskSetPriorityPatchResult =
    ApiSpecification.components["schemas"]["TaskSetPriorityPatchResult"];

export type ApiTaskSetLayoutPatchResult =
    ApiSpecification.components["schemas"]["TaskSetLayoutPatchResult"];

export type ApiTaskSetParentPatchResult =
    ApiSpecification.components["schemas"]["TaskSetParentPatchResult"];

export type ApiTaskMoveInParentPatchResult =
    ApiSpecification.components["schemas"]["TaskMoveInParentPatchResult"];

export type ApiTaskAddCollectionPatchResult =
    ApiSpecification.components["schemas"]["TaskAddCollectionPatchResult"];

export type ApiTaskRemoveCollectionPatchResult =
    ApiSpecification.components["schemas"]["TaskRemoveCollectionPatchResult"];

export type ApiTaskMoveInCollectionPatchResult =
    ApiSpecification.components["schemas"]["TaskMoveInCollectionPatchResult"];

export type ApiTaskBatchPatchResult =
    ApiSpecification.components["schemas"]["TaskBatchPatchResult"];

export type ApiTaskBatchCreatePatchResult =
    ApiSpecification.components["schemas"]["TaskBatchCreatePatchResult"];

export type ApiTaskBatchUpdatePatchResult =
    ApiSpecification.components["schemas"]["TaskBatchUpdatePatchResult"];

export type ApiTaskCollectionPatch = ApiSpecification.components["schemas"]["TaskCollectionPatch"];

export type ApiTaskCollectionSetNamePatch =
    ApiSpecification.components["schemas"]["TaskCollectionSetNamePatch"];

export type ApiTaskCollectionSetColorPatch =
    ApiSpecification.components["schemas"]["TaskCollectionSetColorPatch"];

export type ApiTaskStatus = ApiSpecification.components["schemas"]["TaskStatus"];

export type ApiTaskOpenStatus = ApiSpecification.components["schemas"]["TaskOpenStatus"];

export type ApiTaskClosedStatus = ApiSpecification.components["schemas"]["TaskClosedStatus"];

export type ApiTaskCollection = ApiSpecification.components["schemas"]["TaskCollection"];

export type ApiTaskCollectionPreviewRequest =
    ApiSpecification.components["schemas"]["TaskCollectionPreview_Request"];

export type ApiTaskCollectionPreview =
    ApiSpecification.components["schemas"]["TaskCollectionPreview"];

export type ApiTaskQueryDefaults = ApiSpecification.components["schemas"]["TaskQueryDefaults"];

export type ApiTaskQueryFilter = ApiSpecification.components["schemas"]["TaskQueryFilter"];

export type ApiTaskQueryStatusFilter =
    ApiSpecification.components["schemas"]["TaskQueryStatusFilter"];

export type ApiTaskQueryStatusFilterOperation =
    ApiSpecification.components["schemas"]["TaskQueryStatusFilterOperation"];

export type ApiTaskQueryStatusFilterOneOfOperation =
    ApiSpecification.components["schemas"]["TaskQueryStatusFilterOneOfOperation"];

export type ApiTaskQueryStatusFilterNoneOfOperation =
    ApiSpecification.components["schemas"]["TaskQueryStatusFilterNoneOfOperation"];

export type ApiTaskQueryCollectionsFilter =
    ApiSpecification.components["schemas"]["TaskQueryCollectionsFilter"];

export type ApiTaskQueryCollectionsFilterOperation =
    ApiSpecification.components["schemas"]["TaskQueryCollectionsFilterOperation"];

export type ApiTaskQueryCollectionsFilterIncludesOneOfOperation =
    ApiSpecification.components["schemas"]["TaskQueryCollectionsFilterIncludesOneOfOperation"];

export type ApiTaskQueryCollectionsFilterIncludesAllOfOperation =
    ApiSpecification.components["schemas"]["TaskQueryCollectionsFilterIncludesAllOfOperation"];

export type ApiTaskQueryCollectionsFilterExcludesAllOfOperation =
    ApiSpecification.components["schemas"]["TaskQueryCollectionsFilterExcludesAllOfOperation"];

export type ApiTaskQueryCollectionsFilterIsEmptyOperation =
    ApiSpecification.components["schemas"]["TaskQueryCollectionsFilterIsEmptyOperation"];

export type ApiTaskQueryPriorityFilter =
    ApiSpecification.components["schemas"]["TaskQueryPriorityFilter"];

export type ApiTaskQueryPriorityFilterOperation =
    ApiSpecification.components["schemas"]["TaskQueryPriorityFilterOperation"];

export type ApiTaskQueryPriorityFilterOneOfOperation =
    ApiSpecification.components["schemas"]["TaskQueryPriorityFilterOneOfOperation"];

export type ApiTaskQueryPriorityFilterNoneOfOperation =
    ApiSpecification.components["schemas"]["TaskQueryPriorityFilterNoneOfOperation"];

export type ApiTaskQueryLayoutFilter =
    ApiSpecification.components["schemas"]["TaskQueryLayoutFilter"];

export type ApiTaskQueryLayoutFilterOperation =
    ApiSpecification.components["schemas"]["TaskQueryLayoutFilterOperation"];

export type ApiTaskQueryLayoutFilterOneOfOperation =
    ApiSpecification.components["schemas"]["TaskQueryLayoutFilterOneOfOperation"];

export type ApiTaskQueryLayoutFilterNoneOfOperation =
    ApiSpecification.components["schemas"]["TaskQueryLayoutFilterNoneOfOperation"];

export type ApiTaskQueryTitleFilter =
    ApiSpecification.components["schemas"]["TaskQueryTitleFilter"];

export type ApiTaskQueryTitleFilterOperation =
    ApiSpecification.components["schemas"]["TaskQueryTitleFilterOperation"];

export type ApiTaskQueryTitleFilterIncludesOperation =
    ApiSpecification.components["schemas"]["TaskQueryTitleFilterIncludesOperation"];

export type ApiTaskQueryTitleFilterExcludesOperation =
    ApiSpecification.components["schemas"]["TaskQueryTitleFilterExcludesOperation"];

export type ApiTaskQueryAssigneeFilter =
    ApiSpecification.components["schemas"]["TaskQueryAssigneeFilter"];

export type ApiTaskQueryCreatorFilter =
    ApiSpecification.components["schemas"]["TaskQueryCreatorFilter"];

export type ApiTaskQueryAssignerFilter =
    ApiSpecification.components["schemas"]["TaskQueryAssignerFilter"];

export type ApiTaskQueryAccountFilterOperation =
    ApiSpecification.components["schemas"]["TaskQueryAccountFilterOperation"];

export type ApiTaskQueryAccountFilterOneOfOperation =
    ApiSpecification.components["schemas"]["TaskQueryAccountFilterOneOfOperation"];

export type ApiTaskQueryAccountFilterNoneOfOperation =
    ApiSpecification.components["schemas"]["TaskQueryAccountFilterNoneOfOperation"];

export type ApiTaskQueryAccountFilterOperationAccount =
    ApiSpecification.components["schemas"]["TaskQueryAccountFilterOperationAccount"];

export type ApiTaskQueryAccountFilterOperationAccountItem =
    ApiSpecification.components["schemas"]["TaskQueryAccountFilterOperationAccountItem"];

export type ApiTaskQueryAccountFilterOperationCurrentAccount =
    ApiSpecification.components["schemas"]["TaskQueryAccountFilterOperationCurrentAccount"];

export type ApiTaskQueryAccountFilterOperationMissingAccount =
    ApiSpecification.components["schemas"]["TaskQueryAccountFilterOperationMissingAccount"];

export type ApiTaskQueryCreatorFilterOperation =
    ApiSpecification.components["schemas"]["TaskQueryCreatorFilterOperation"];

export type ApiTaskQueryCreatorFilterOneOfOperation =
    ApiSpecification.components["schemas"]["TaskQueryCreatorFilterOneOfOperation"];

export type ApiTaskQueryCreatorFilterNoneOfOperation =
    ApiSpecification.components["schemas"]["TaskQueryCreatorFilterNoneOfOperation"];

export type ApiTaskQueryCreatorFilterOperationAccount =
    ApiSpecification.components["schemas"]["TaskQueryCreatorFilterOperationAccount"];

export type ApiTaskQueryDueFilter = ApiSpecification.components["schemas"]["TaskQueryDueFilter"];

export type ApiTaskQueryDueFilterOperation =
    ApiSpecification.components["schemas"]["TaskQueryDueFilterOperation"];

export type ApiTaskQueryDueFilterOverdueOperation =
    ApiSpecification.components["schemas"]["TaskQueryDueFilterOverdueOperation"];

export type ApiTaskQueryDueFilterIsEmptyOperation =
    ApiSpecification.components["schemas"]["TaskQueryDueFilterIsEmptyOperation"];

export type ApiTaskQueryCreatedTimeFilter =
    ApiSpecification.components["schemas"]["TaskQueryCreatedTimeFilter"];

export type ApiTaskQueryAssignedTimeFilter =
    ApiSpecification.components["schemas"]["TaskQueryAssignedTimeFilter"];

export type ApiTaskQueryClosedTimeFilter =
    ApiSpecification.components["schemas"]["TaskQueryClosedTimeFilter"];

export type ApiTaskQueryActivatedTimeFilter =
    ApiSpecification.components["schemas"]["TaskQueryActivatedTimeFilter"];

export type ApiTaskQueryTimeFilterOperation =
    ApiSpecification.components["schemas"]["TaskQueryTimeFilterOperation"];

export type ApiTaskQueryTimeFilterLessThanOperation =
    ApiSpecification.components["schemas"]["TaskQueryTimeFilterLessThanOperation"];

export type ApiTaskQueryTimeFilterGreaterThanOperation =
    ApiSpecification.components["schemas"]["TaskQueryTimeFilterGreaterThanOperation"];

export type ApiTaskQueryTimeFilterOperationTime =
    ApiSpecification.components["schemas"]["TaskQueryTimeFilterOperationTime"];

export type ApiTaskQueryTimeFilterOperationAbsoluteDateTime =
    ApiSpecification.components["schemas"]["TaskQueryTimeFilterOperationAbsoluteDateTime"];

export type ApiTaskQueryTimeFilterOperationRelativeTodayTime =
    ApiSpecification.components["schemas"]["TaskQueryTimeFilterOperationRelativeTodayTime"];

export type ApiTaskQueryTimeFilterOperationRelativeAfterTodayTime =
    ApiSpecification.components["schemas"]["TaskQueryTimeFilterOperationRelativeAfterTodayTime"];

export type ApiTaskQueryTimeFilterOperationRelativeBeforeTodayTime =
    ApiSpecification.components["schemas"]["TaskQueryTimeFilterOperationRelativeBeforeTodayTime"];

export type ApiTaskQueryTimeFilterOperationDuration =
    ApiSpecification.components["schemas"]["TaskQueryTimeFilterOperationDuration"];

export type ApiTaskQueryTimeFilterOperationDaysDuration =
    ApiSpecification.components["schemas"]["TaskQueryTimeFilterOperationDaysDuration"];

export type ApiTaskQueryTimeFilterOperationWeeksDuration =
    ApiSpecification.components["schemas"]["TaskQueryTimeFilterOperationWeeksDuration"];

export type ApiTaskQueryTimeFilterOperationMonthsDuration =
    ApiSpecification.components["schemas"]["TaskQueryTimeFilterOperationMonthsDuration"];

export type ApiTaskQueryTimeFilterOperationYearsDuration =
    ApiSpecification.components["schemas"]["TaskQueryTimeFilterOperationYearsDuration"];

export type ApiTaskQuerySort = ApiSpecification.components["schemas"]["TaskQuerySort"];

export type ApiTaskQuerySortDirection =
    ApiSpecification.components["schemas"]["TaskQuerySortDirection"];

export type ApiTaskQuerySortMissing =
    ApiSpecification.components["schemas"]["TaskQuerySortMissing"];

export type ApiTaskQueryStatusSort = ApiSpecification.components["schemas"]["TaskQueryStatusSort"];

export type ApiTaskQueryPrioritySort =
    ApiSpecification.components["schemas"]["TaskQueryPrioritySort"];

export type ApiTaskQueryLayoutSort = ApiSpecification.components["schemas"]["TaskQueryLayoutSort"];

export type ApiTaskQueryAssigneeSort =
    ApiSpecification.components["schemas"]["TaskQueryAssigneeSort"];

export type ApiTaskQueryCreatorSort =
    ApiSpecification.components["schemas"]["TaskQueryCreatorSort"];

export type ApiTaskQueryAssignerSort =
    ApiSpecification.components["schemas"]["TaskQueryAssignerSort"];

export type ApiTaskQueryDueSort = ApiSpecification.components["schemas"]["TaskQueryDueSort"];

export type ApiTaskQueryCreatedTimeSort =
    ApiSpecification.components["schemas"]["TaskQueryCreatedTimeSort"];

export type ApiTaskQueryAssignedTimeSort =
    ApiSpecification.components["schemas"]["TaskQueryAssignedTimeSort"];

export type ApiTaskQueryClosedTimeSort =
    ApiSpecification.components["schemas"]["TaskQueryClosedTimeSort"];

export type ApiTaskQueryActivatedTimeSort =
    ApiSpecification.components["schemas"]["TaskQueryActivatedTimeSort"];

export type ApiMessage = ApiSpecification.components["schemas"]["Message"];

export type ApiMessagePayload = ApiSpecification.components["schemas"]["MessagePayload"];

export type ApiMessageContentPayload =
    ApiSpecification.components["schemas"]["MessageContentPayload"];

export type ApiMessageContentPayloadFileRequest =
    ApiSpecification.components["schemas"]["MessageContentPayloadFile_Request"];

export type ApiMessageContentPayloadFile =
    ApiSpecification.components["schemas"]["MessageContentPayloadFile"];

export type ApiMessageContentPayloadParent =
    ApiSpecification.components["schemas"]["MessageContentPayloadParent"];

export type ApiMessageContentPayloadMessageParentRequest =
    ApiSpecification.components["schemas"]["MessageContentPayloadMessageParent_Request"];

export type ApiMessageContentPayloadMessageParent =
    ApiSpecification.components["schemas"]["MessageContentPayloadMessageParent"];

export type ApiMessageContentPayloadPostParentRequest =
    ApiSpecification.components["schemas"]["MessageContentPayloadPostParent_Request"];

export type ApiMessageContentPayloadPostParent =
    ApiSpecification.components["schemas"]["MessageContentPayloadPostParent"];

export type ApiMessageDeletedPayload =
    ApiSpecification.components["schemas"]["MessageDeletedPayload"];

export type ApiMessageExperimentalApproval =
    ApiSpecification.components["schemas"]["MessageExperimentalApproval"];

export type ApiMessageExperimentalApprovalDecision =
    ApiSpecification.components["schemas"]["MessageExperimentalApprovalDecision"];

export type ApiMessageExperimentalApprovalDecisionSchema =
    ApiSpecification.components["schemas"]["MessageExperimentalApprovalDecisionSchema"];

export type ApiMessageExperimentalApprovalDecisionOption =
    ApiSpecification.components["schemas"]["MessageExperimentalApprovalDecisionOption"];

export type ApiMessageExperimentalApprovalDecisionApprovedOption =
    ApiSpecification.components["schemas"]["MessageExperimentalApprovalDecisionApprovedOption"];

export type ApiMessageExperimentalApprovalDecisionRejectedOption =
    ApiSpecification.components["schemas"]["MessageExperimentalApprovalDecisionRejectedOption"];

export type ApiMessageExperimentalApprovalDecisionApprovedForSessionOption =
    ApiSpecification.components["schemas"]["MessageExperimentalApprovalDecisionApprovedForSessionOption"];

export type ApiMessageExperimentalApprovalDecisionValue =
    ApiSpecification.components["schemas"]["MessageExperimentalApprovalDecisionValue"];

export type ApiMessageExperimentalApprovalDecisionApprovedValueRequest =
    ApiSpecification.components["schemas"]["MessageExperimentalApprovalDecisionApprovedValue_Request"];

export type ApiMessageExperimentalApprovalDecisionApprovedValue =
    ApiSpecification.components["schemas"]["MessageExperimentalApprovalDecisionApprovedValue"];

export type ApiMessageExperimentalApprovalDecisionRejectedValueRequest =
    ApiSpecification.components["schemas"]["MessageExperimentalApprovalDecisionRejectedValue_Request"];

export type ApiMessageExperimentalApprovalDecisionRejectedValue =
    ApiSpecification.components["schemas"]["MessageExperimentalApprovalDecisionRejectedValue"];

export type ApiMessageExperimentalApprovalDecisionApprovedForSessionValueRequest =
    ApiSpecification.components["schemas"]["MessageExperimentalApprovalDecisionApprovedForSessionValue_Request"];

export type ApiMessageExperimentalApprovalDecisionApprovedForSessionValue =
    ApiSpecification.components["schemas"]["MessageExperimentalApprovalDecisionApprovedForSessionValue"];

export type ApiMessageExperimentalApprovalDecisionApprovedForSessionValueScope =
    ApiSpecification.components["schemas"]["MessageExperimentalApprovalDecisionApprovedForSessionValueScope"];

export type ApiBotWebhookEvent = ApiSpecification.components["schemas"]["BotWebhookEvent"];

export type ApiBotWebhookCreatedMessageEvent =
    ApiSpecification.components["schemas"]["BotWebhookCreatedMessageEvent"];

export type ApiBotWebhookCreatedMessageEventParent =
    ApiSpecification.components["schemas"]["BotWebhookCreatedMessageEventParent"];

export type ApiBotWebhookCreatedMessageEventMessageParent =
    ApiSpecification.components["schemas"]["BotWebhookCreatedMessageEventMessageParent"];

export type ApiBotWebhookCreatedMessageEventPostParent =
    ApiSpecification.components["schemas"]["BotWebhookCreatedMessageEventPostParent"];

export type ApiBotWebhookCreatedPostEvent =
    ApiSpecification.components["schemas"]["BotWebhookCreatedPostEvent"];

export type ApiBotWebhookUpdatedMessageStreamExperimentalApprovalsPartEvent =
    ApiSpecification.components["schemas"]["BotWebhookUpdatedMessageStreamExperimentalApprovalsPartEvent"];

export type ApiMessageContentPayloadParentContentSnippet =
    ApiSpecification.components["schemas"]["MessageContentPayloadParentContentSnippet"];

export type ApiMessageContentPayloadParentContentSnippetTextInlineElement =
    ApiSpecification.components["schemas"]["MessageContentPayloadParentContentSnippetTextInlineElement"];

export type ApiMessageContentPayloadParentContentSnippetInlineElementMark =
    ApiSpecification.components["schemas"]["MessageContentPayloadParentContentSnippetInlineElementMark"];

export type ApiSearchResult = ApiSpecification.components["schemas"]["SearchResult"];

export type ApiSearchAccountResult = ApiSpecification.components["schemas"]["SearchAccountResult"];

export type ApiSearchChannelResult = ApiSpecification.components["schemas"]["SearchChannelResult"];

export type ApiSearchChatResult = ApiSpecification.components["schemas"]["SearchChatResult"];

export type ApiSearchChatMessageResult =
    ApiSpecification.components["schemas"]["SearchChatMessageResult"];

export type ApiSearchDocumentResult =
    ApiSpecification.components["schemas"]["SearchDocumentResult"];

export type ApiSearchDocumentMessageResult =
    ApiSpecification.components["schemas"]["SearchDocumentMessageResult"];

export type ApiSearchPostResult = ApiSpecification.components["schemas"]["SearchPostResult"];

export type ApiSearchPostMessageResult =
    ApiSpecification.components["schemas"]["SearchPostMessageResult"];

export type ApiSearchSiteResult = ApiSpecification.components["schemas"]["SearchSiteResult"];

export type ApiSearchTaskResult = ApiSpecification.components["schemas"]["SearchTaskResult"];

export type ApiSearchTaskMessageResult =
    ApiSpecification.components["schemas"]["SearchTaskMessageResult"];

export type ApiSearchTaskCollectionResult =
    ApiSpecification.components["schemas"]["SearchTaskCollectionResult"];

export type ApiSearchResultMatch = ApiSpecification.components["schemas"]["SearchResultMatch"];

export type ApiSearchResultTitleMatch =
    ApiSpecification.components["schemas"]["SearchResultTitleMatch"];

export type ApiSearchResultBodySnippetMatch =
    ApiSpecification.components["schemas"]["SearchResultBodySnippetMatch"];

export type ApiSearchResultParsedFilter =
    ApiSpecification.components["schemas"]["SearchResultParsedFilter"];

export type ApiActorRequest = ApiSpecification.components["schemas"]["Actor_Request"];

export type ApiActor = ApiSpecification.components["schemas"]["Actor"];

export type ApiActorBotFrom = ApiSpecification.components["schemas"]["ActorBotFrom"];

export type ApiMessageContentPayloadParentRequest =
    ApiSpecification.components["schemas"]["MessageContentPayloadParent_Request"];

export type ApiMessageExperimentalApprovalDecisionValueRequest =
    ApiSpecification.components["schemas"]["MessageExperimentalApprovalDecisionValue_Request"];

export type ApiPreviewReferenceRequest =
    ApiSpecification.components["schemas"]["PreviewReference_Request"];

export type ApiTaskCollectionItemRequest =
    ApiSpecification.components["schemas"]["TaskCollectionItem_Request"];

export type ApiMessageRoomReferenceRequest =
    ApiSpecification.components["schemas"]["MessageRoomReference_Request"];

export type ApiMentionReferenceRequest =
    ApiSpecification.components["schemas"]["MentionReference_Request"];

export type ApiContentBlockElementRequest =
    ApiSpecification.components["schemas"]["ContentBlockElement_Request"];

export type ApiTaskSetAssigneePatchRequest =
    ApiSpecification.components["schemas"]["TaskSetAssigneePatch_Request"];

export type ApiTaskSetParentPatchRequest =
    ApiSpecification.components["schemas"]["TaskSetParentPatch_Request"];

export type ApiContentBlockElementWithoutKeys =
    ApiSpecification.components["schemas"]["ContentBlockElement_WithoutKeys"];

export type ApiDocumentThreadReferenceRequest =
    ApiSpecification.components["schemas"]["DocumentThreadReference_Request"];

export type ApiContentCodeBlockElementRequest =
    ApiSpecification.components["schemas"]["ContentCodeBlockElement_Request"];

export type ApiContentFileFloatBlockElementRequest =
    ApiSpecification.components["schemas"]["ContentFileFloatBlockElement_Request"];

export type ApiContentCodeBlockElementWithoutKeys =
    ApiSpecification.components["schemas"]["ContentCodeBlockElement_WithoutKeys"];

export type ApiContentFileFloatBlockElementWithoutKeys =
    ApiSpecification.components["schemas"]["ContentFileFloatBlockElement_WithoutKeys"];

export type ApiContentListBlockElementItemRequest =
    ApiSpecification.components["schemas"]["ContentListBlockElementItem_Request"];

export type ApiContentCheckListBlockElementItemRequest =
    ApiSpecification.components["schemas"]["ContentCheckListBlockElementItem_Request"];

export type ApiContentQuoteBlockElementBlockElementRequest =
    ApiSpecification.components["schemas"]["ContentQuoteBlockElementBlockElement_Request"];

export type ApiContentFileGalleryBlockElementRowRequest =
    ApiSpecification.components["schemas"]["ContentFileGalleryBlockElementRow_Request"];

export type ApiTaskQueryCollectionsFilterIncludesOneOfOperationRequest =
    ApiSpecification.components["schemas"]["TaskQueryCollectionsFilterIncludesOneOfOperation_Request"];

export type ApiTaskQueryCollectionsFilterIncludesAllOfOperationRequest =
    ApiSpecification.components["schemas"]["TaskQueryCollectionsFilterIncludesAllOfOperation_Request"];

export type ApiTaskQueryCollectionsFilterExcludesAllOfOperationRequest =
    ApiSpecification.components["schemas"]["TaskQueryCollectionsFilterExcludesAllOfOperation_Request"];

export type ApiContentListBlockElementItemWithoutKeys =
    ApiSpecification.components["schemas"]["ContentListBlockElementItem_WithoutKeys"];

export type ApiContentCheckListBlockElementItemWithoutKeys =
    ApiSpecification.components["schemas"]["ContentCheckListBlockElementItem_WithoutKeys"];

export type ApiContentQuoteBlockElementBlockElementWithoutKeys =
    ApiSpecification.components["schemas"]["ContentQuoteBlockElementBlockElement_WithoutKeys"];

export type ApiContentFileGalleryBlockElementRowItemWithoutKeys =
    ApiSpecification.components["schemas"]["ContentFileGalleryBlockElementRowItem_WithoutKeys"];

export type ApiContentTableBlockElementCellBlockElementRequest =
    ApiSpecification.components["schemas"]["ContentTableBlockElementCellBlockElement_Request"];

export type ApiTaskQueryAccountFilterOperationAccountItemRequest =
    ApiSpecification.components["schemas"]["TaskQueryAccountFilterOperationAccountItem_Request"];

export type ApiContentTableBlockElementCellBlockElementWithoutKeys =
    ApiSpecification.components["schemas"]["ContentTableBlockElementCellBlockElement_WithoutKeys"];

export type ApiContentRequest = ApiSpecification.components["schemas"]["Content_Request"];

export type ApiTaskPatchRequest = ApiSpecification.components["schemas"]["TaskPatch_Request"];

export type ApiContentWithoutKeys = ApiSpecification.components["schemas"]["Content_WithoutKeys"];

export type ApiTaskAddCollectionPatchRequest =
    ApiSpecification.components["schemas"]["TaskAddCollectionPatch_Request"];

export type ApiMessageExperimentalApprovalDecisionRequest =
    ApiSpecification.components["schemas"]["MessageExperimentalApprovalDecision_Request"];

export type ApiContentMentionInlineElementRequest =
    ApiSpecification.components["schemas"]["ContentMentionInlineElement_Request"];

export type ApiContentUnorderedListBlockElementRequest =
    ApiSpecification.components["schemas"]["ContentUnorderedListBlockElement_Request"];

export type ApiContentOrderedListBlockElementRequest =
    ApiSpecification.components["schemas"]["ContentOrderedListBlockElement_Request"];

export type ApiContentCheckListBlockElementRequest =
    ApiSpecification.components["schemas"]["ContentCheckListBlockElement_Request"];

export type ApiContentQuoteBlockElementRequest =
    ApiSpecification.components["schemas"]["ContentQuoteBlockElement_Request"];

export type ApiContentFileGalleryBlockElementRequest =
    ApiSpecification.components["schemas"]["ContentFileGalleryBlockElement_Request"];

export type ApiTaskQueryCollectionsFilterOperationRequest =
    ApiSpecification.components["schemas"]["TaskQueryCollectionsFilterOperation_Request"];

export type ApiContentUnorderedListBlockElementWithoutKeys =
    ApiSpecification.components["schemas"]["ContentUnorderedListBlockElement_WithoutKeys"];

export type ApiContentOrderedListBlockElementWithoutKeys =
    ApiSpecification.components["schemas"]["ContentOrderedListBlockElement_WithoutKeys"];

export type ApiContentCheckListBlockElementWithoutKeys =
    ApiSpecification.components["schemas"]["ContentCheckListBlockElement_WithoutKeys"];

export type ApiContentQuoteBlockElementWithoutKeys =
    ApiSpecification.components["schemas"]["ContentQuoteBlockElement_WithoutKeys"];

export type ApiLabelContentMentionInlineElementRequest =
    ApiSpecification.components["schemas"]["LabelContentMentionInlineElement_Request"];

export type ApiContentFileGalleryBlockElementRowWithoutKeys =
    ApiSpecification.components["schemas"]["ContentFileGalleryBlockElementRow_WithoutKeys"];

export type ApiContentTableBlockElementCellRequest =
    ApiSpecification.components["schemas"]["ContentTableBlockElementCell_Request"];

export type ApiTaskQueryAccountFilterOperationAccountRequest =
    ApiSpecification.components["schemas"]["TaskQueryAccountFilterOperationAccount_Request"];

export type ApiTaskQueryCreatorFilterOperationAccountRequest =
    ApiSpecification.components["schemas"]["TaskQueryCreatorFilterOperationAccount_Request"];

export type ApiContentTableBlockElementCellWithoutKeys =
    ApiSpecification.components["schemas"]["ContentTableBlockElementCell_WithoutKeys"];

export type ApiMessageExperimentalApprovalRequest =
    ApiSpecification.components["schemas"]["MessageExperimentalApproval_Request"];

export type ApiContentInlineElementRequest =
    ApiSpecification.components["schemas"]["ContentInlineElement_Request"];

export type ApiDocumentSetContentPatchRequest =
    ApiSpecification.components["schemas"]["DocumentSetContentPatch_Request"];

export type ApiChannelSetDescriptionPatchRequest =
    ApiSpecification.components["schemas"]["ChannelSetDescriptionPatch_Request"];

export type ApiTaskBatchCreatePatchRequest =
    ApiSpecification.components["schemas"]["TaskBatchCreatePatch_Request"];

export type ApiTaskBatchUpdatePatchRequest =
    ApiSpecification.components["schemas"]["TaskBatchUpdatePatch_Request"];

export type ApiTaskQueryCollectionsFilterRequest =
    ApiSpecification.components["schemas"]["TaskQueryCollectionsFilter_Request"];

export type ApiTaskNotesSetContentPatchRequest =
    ApiSpecification.components["schemas"]["TaskNotesSetContentPatch_Request"];

export type ApiMessageStreamContentPartPayloadRequest =
    ApiSpecification.components["schemas"]["MessageStreamContentPartPayload_Request"];

export type ApiMessageStreamReasoningPartPayloadRequest =
    ApiSpecification.components["schemas"]["MessageStreamReasoningPartPayload_Request"];

export type ApiLabelContentInlineElementRequest =
    ApiSpecification.components["schemas"]["LabelContentInlineElement_Request"];

export type ApiContentFileGalleryBlockElementWithoutKeys =
    ApiSpecification.components["schemas"]["ContentFileGalleryBlockElement_WithoutKeys"];

export type ApiContentTableBlockElementRowRequest =
    ApiSpecification.components["schemas"]["ContentTableBlockElementRow_Request"];

export type ApiTaskQueryAccountFilterOneOfOperationRequest =
    ApiSpecification.components["schemas"]["TaskQueryAccountFilterOneOfOperation_Request"];

export type ApiTaskQueryAccountFilterNoneOfOperationRequest =
    ApiSpecification.components["schemas"]["TaskQueryAccountFilterNoneOfOperation_Request"];

export type ApiTaskQueryCreatorFilterOneOfOperationRequest =
    ApiSpecification.components["schemas"]["TaskQueryCreatorFilterOneOfOperation_Request"];

export type ApiTaskQueryCreatorFilterNoneOfOperationRequest =
    ApiSpecification.components["schemas"]["TaskQueryCreatorFilterNoneOfOperation_Request"];

export type ApiContentTableBlockElementRowWithoutKeys =
    ApiSpecification.components["schemas"]["ContentTableBlockElementRow_WithoutKeys"];

export type ApiContentListBlockElementRequest =
    ApiSpecification.components["schemas"]["ContentListBlockElement_Request"];

export type ApiContentListBlockElementWithoutKeys =
    ApiSpecification.components["schemas"]["ContentListBlockElement_WithoutKeys"];

export type ApiDocumentPatchRequest =
    ApiSpecification.components["schemas"]["DocumentPatch_Request"];

export type ApiChannelPatchRequest = ApiSpecification.components["schemas"]["ChannelPatch_Request"];

export type ApiTaskBatchPatchRequest =
    ApiSpecification.components["schemas"]["TaskBatchPatch_Request"];

export type ApiTaskQueryFilterRequest =
    ApiSpecification.components["schemas"]["TaskQueryFilter_Request"];

export type ApiTaskNotesPatchRequest =
    ApiSpecification.components["schemas"]["TaskNotesPatch_Request"];

export type ApiMessageStreamPartPayloadRequest =
    ApiSpecification.components["schemas"]["MessageStreamPartPayload_Request"];

export type ApiMessageStreamExperimentalApprovalsPartPayloadRequest =
    ApiSpecification.components["schemas"]["MessageStreamExperimentalApprovalsPartPayload_Request"];

export type ApiLabelContentRequest = ApiSpecification.components["schemas"]["LabelContent_Request"];

export type ApiContentTableBlockElementRequest =
    ApiSpecification.components["schemas"]["ContentTableBlockElement_Request"];

export type ApiTaskQueryAccountFilterOperationRequest =
    ApiSpecification.components["schemas"]["TaskQueryAccountFilterOperation_Request"];

export type ApiTaskQueryCreatorFilterOperationRequest =
    ApiSpecification.components["schemas"]["TaskQueryCreatorFilterOperation_Request"];

export type ApiContentTableBlockElementWithoutKeys =
    ApiSpecification.components["schemas"]["ContentTableBlockElement_WithoutKeys"];

export type ApiTaskQueryAssigneeFilterRequest =
    ApiSpecification.components["schemas"]["TaskQueryAssigneeFilter_Request"];

export type ApiTaskQueryCreatorFilterRequest =
    ApiSpecification.components["schemas"]["TaskQueryCreatorFilter_Request"];

export type ApiTaskQueryAssignerFilterRequest =
    ApiSpecification.components["schemas"]["TaskQueryAssignerFilter_Request"];

export type ApiMessageStreamToolCallPartPayloadCallRequest =
    ApiSpecification.components["schemas"]["MessageStreamToolCallPartPayloadCall_Request"];

export type ApiMessageExperimentalApprovalDecisionApprovedForSessionOptionRequest =
    ApiSpecification.components["schemas"]["MessageExperimentalApprovalDecisionApprovedForSessionOption_Request"];

export type ApiMessageStreamToolCallPartPayloadRequest =
    ApiSpecification.components["schemas"]["MessageStreamToolCallPartPayload_Request"];

export type ApiMessageExperimentalApprovalDecisionOptionRequest =
    ApiSpecification.components["schemas"]["MessageExperimentalApprovalDecisionOption_Request"];

export type ApiMessageExperimentalApprovalDecisionSchemaRequest =
    ApiSpecification.components["schemas"]["MessageExperimentalApprovalDecisionSchema_Request"];

export type ApiErrorResponse =
    ApiSpecification.components["responses"]["Error"]["content"]["application/json"];

export type ApiGetChannelResponse =
    ApiSpecification.components["responses"]["GetChannel"]["content"]["application/json"];

export type ApiGetChatResponse =
    ApiSpecification.components["responses"]["GetChat"]["content"]["application/json"];

export type ApiGetDocumentResponse =
    ApiSpecification.components["responses"]["GetDocument"]["content"]["application/json"];

export type ApiGetTaskResponse =
    ApiSpecification.components["responses"]["GetTask"]["content"]["application/json"];

export type ApiGetTaskWithNotesResponse =
    ApiSpecification.components["responses"]["GetTaskWithNotes"]["content"]["application/json"];

export type ApiPatchTaskResponse =
    ApiSpecification.components["responses"]["PatchTask"]["content"]["application/json"];

export type ApiPatchTasksResponse =
    ApiSpecification.components["responses"]["PatchTasks"]["content"]["application/json"];

export type ApiGetTaskNotesResponse =
    ApiSpecification.components["responses"]["GetTaskNotes"]["content"]["application/json"];

export type ApiGetTasksResponse =
    ApiSpecification.components["responses"]["GetTasks"]["content"]["application/json"];

export type ApiGetTaskCollectionTasksResponse =
    ApiSpecification.components["responses"]["GetTaskCollectionTasks"]["content"]["application/json"];

export type ApiGetMessageResponse =
    ApiSpecification.components["responses"]["GetMessage"]["content"]["application/json"];

export type ApiGetMessagesResponse =
    ApiSpecification.components["responses"]["GetMessages"]["content"]["application/json"];

export type ApiGetMessageExperimentalApprovalsResponse =
    ApiSpecification.components["responses"]["GetMessageExperimentalApprovals"]["content"]["application/json"];

export type ApiGetMessageStreamCompletionResponse =
    ApiSpecification.components["responses"]["GetMessageStreamCompletion"]["content"]["application/json"];

export type ApiGetMessageStreamPingResponse =
    ApiSpecification.components["responses"]["GetMessageStreamPing"]["content"]["application/json"];

export type ApiGetMessageStreamPartResponse =
    ApiSpecification.components["responses"]["GetMessageStreamPart"]["content"]["application/json"];

export type ApiGetPostResponse =
    ApiSpecification.components["responses"]["GetPost"]["content"]["application/json"];

export type ApiCreateMessageRequestBody =
    ApiSpecification.components["requestBodies"]["CreateMessage"]["content"]["application/json"];

export type ApiPutMessageExperimentalApprovalsPendingDecisionRequestBody =
    ApiSpecification.components["requestBodies"]["PutMessageExperimentalApprovalsPendingDecision"]["content"]["application/json"];

export type ApiPatchMessageExperimentalApprovalsRequestBody =
    ApiSpecification.components["requestBodies"]["PatchMessageExperimentalApprovals"]["content"]["application/json"];

export type ApiPutMessageStreamPartRequestBody =
    ApiSpecification.components["requestBodies"]["PutMessageStreamPart"]["content"]["application/json"];

export type ApiBotWebhookRequestBody =
    ApiSpecification.webhooks["bot"]["post"]["requestBody"]["content"]["application/json"];
