// @generated by //shared/api/specification:write_specification

import {ApiSpecification} from "~/shared/api/specification/types/api_specification_types.js";

export type ApiTaskCollectionColor = ApiSpecification.components["schemas"]["TaskCollectionColor"];

export type ApiAccountReference = ApiSpecification.components["schemas"]["AccountReference"];

export type ApiAccountReferenceResponse =
    ApiSpecification.components["schemas"]["AccountReference_Response"];

export type ApiChannelReference = ApiSpecification.components["schemas"]["ChannelReference"];

export type ApiChannelReferenceResponse =
    ApiSpecification.components["schemas"]["ChannelReference_Response"];

export type ApiChatReference = ApiSpecification.components["schemas"]["ChatReference"];

export type ApiChatReferenceResponse =
    ApiSpecification.components["schemas"]["ChatReference_Response"];

export type ApiDocumentReference = ApiSpecification.components["schemas"]["DocumentReference"];

export type ApiDocumentReferenceResponse =
    ApiSpecification.components["schemas"]["DocumentReference_Response"];

export type ApiPostReference = ApiSpecification.components["schemas"]["PostReference"];

export type ApiPostReferenceResponse =
    ApiSpecification.components["schemas"]["PostReference_Response"];

export type ApiTaskReference = ApiSpecification.components["schemas"]["TaskReference"];

export type ApiTaskReferenceResponse =
    ApiSpecification.components["schemas"]["TaskReference_Response"];

export type ApiTaskCollectionReference =
    ApiSpecification.components["schemas"]["TaskCollectionReference"];

export type ApiTaskCollectionReferenceResponse =
    ApiSpecification.components["schemas"]["TaskCollectionReference_Response"];

export type ApiSiteReference = ApiSpecification.components["schemas"]["SiteReference"];

export type ApiSiteReferenceResponse =
    ApiSpecification.components["schemas"]["SiteReference_Response"];

export type ApiMentionReference = ApiSpecification.components["schemas"]["MentionReference"];

export type ApiPreviewReference = ApiSpecification.components["schemas"]["PreviewReference"];

export type ApiContent = ApiSpecification.components["schemas"]["Content"];

export type ApiContentBlockElement = ApiSpecification.components["schemas"]["ContentBlockElement"];

export type ApiContentParagraphBlockElement =
    ApiSpecification.components["schemas"]["ContentParagraphBlockElement"];

export type ApiContentParagraphBlockElementResponse =
    ApiSpecification.components["schemas"]["ContentParagraphBlockElement_Response"];

export type ApiContentParagraphBlockElementResponseWithoutKeys =
    ApiSpecification.components["schemas"]["ContentParagraphBlockElement_Response_WithoutKeys"];

export type ApiContentListBlockElement =
    ApiSpecification.components["schemas"]["ContentListBlockElement"];

export type ApiContentUnorderedListBlockElement =
    ApiSpecification.components["schemas"]["ContentUnorderedListBlockElement"];

export type ApiContentOrderedListBlockElement =
    ApiSpecification.components["schemas"]["ContentOrderedListBlockElement"];

export type ApiContentCheckListBlockElement =
    ApiSpecification.components["schemas"]["ContentCheckListBlockElement"];

export type ApiContentListBlockElementItem =
    ApiSpecification.components["schemas"]["ContentListBlockElementItem"];

export type ApiContentCheckListBlockElementItem =
    ApiSpecification.components["schemas"]["ContentCheckListBlockElementItem"];

export type ApiContentQuoteBlockElement =
    ApiSpecification.components["schemas"]["ContentQuoteBlockElement"];

export type ApiContentQuoteBlockElementBlockElement =
    ApiSpecification.components["schemas"]["ContentQuoteBlockElementBlockElement"];

export type ApiContentHeadingBlockElement =
    ApiSpecification.components["schemas"]["ContentHeadingBlockElement"];

export type ApiContentHeadingBlockElementResponse =
    ApiSpecification.components["schemas"]["ContentHeadingBlockElement_Response"];

export type ApiContentHeadingBlockElementResponseWithoutKeys =
    ApiSpecification.components["schemas"]["ContentHeadingBlockElement_Response_WithoutKeys"];

export type ApiContentDividerBlockElement =
    ApiSpecification.components["schemas"]["ContentDividerBlockElement"];

export type ApiContentDividerBlockElementResponse =
    ApiSpecification.components["schemas"]["ContentDividerBlockElement_Response"];

export type ApiContentDividerBlockElementResponseWithoutKeys =
    ApiSpecification.components["schemas"]["ContentDividerBlockElement_Response_WithoutKeys"];

export type ApiContentTableBlockElement =
    ApiSpecification.components["schemas"]["ContentTableBlockElement"];

export type ApiContentTableBlockElementRow =
    ApiSpecification.components["schemas"]["ContentTableBlockElementRow"];

export type ApiContentTableBlockElementCell =
    ApiSpecification.components["schemas"]["ContentTableBlockElementCell"];

export type ApiContentTableBlockElementCellBlockElement =
    ApiSpecification.components["schemas"]["ContentTableBlockElementCellBlockElement"];

export type ApiContentCodeBlockElement =
    ApiSpecification.components["schemas"]["ContentCodeBlockElement"];

export type ApiContentCodeBlockElementLine =
    ApiSpecification.components["schemas"]["ContentCodeBlockElementLine"];

export type ApiContentCodeBlockElementLineResponse =
    ApiSpecification.components["schemas"]["ContentCodeBlockElementLine_Response"];

export type ApiContentCodeBlockElementLineResponseWithoutKeys =
    ApiSpecification.components["schemas"]["ContentCodeBlockElementLine_Response_WithoutKeys"];

export type ApiContentFileBlockElement =
    ApiSpecification.components["schemas"]["ContentFileBlockElement"];

export type ApiContentFileBlockElementResponse =
    ApiSpecification.components["schemas"]["ContentFileBlockElement_Response"];

export type ApiContentFileBlockElementResponseWithoutKeys =
    ApiSpecification.components["schemas"]["ContentFileBlockElement_Response_WithoutKeys"];

export type ApiContentFileBlockElementFile =
    ApiSpecification.components["schemas"]["ContentFileBlockElementFile"];

export type ApiContentFileBlockElementFileResponse =
    ApiSpecification.components["schemas"]["ContentFileBlockElementFile_Response"];

export type ApiContentPreviewBlockElement =
    ApiSpecification.components["schemas"]["ContentPreviewBlockElement"];

export type ApiContentPreviewBlockElementResponse =
    ApiSpecification.components["schemas"]["ContentPreviewBlockElement_Response"];

export type ApiContentPreviewBlockElementResponseWithoutKeys =
    ApiSpecification.components["schemas"]["ContentPreviewBlockElement_Response_WithoutKeys"];

export type ApiContentFileGalleryBlockElement =
    ApiSpecification.components["schemas"]["ContentFileGalleryBlockElement"];

export type ApiContentFileGalleryBlockElementRow =
    ApiSpecification.components["schemas"]["ContentFileGalleryBlockElementRow"];

export type ApiContentFileGalleryBlockElementRowItem =
    ApiSpecification.components["schemas"]["ContentFileGalleryBlockElementRowItem"];

export type ApiContentFileGalleryBlockElementRowItemResponse =
    ApiSpecification.components["schemas"]["ContentFileGalleryBlockElementRowItem_Response"];

export type ApiContentFileFloatBlockElement =
    ApiSpecification.components["schemas"]["ContentFileFloatBlockElement"];

export type ApiContentInlineElement =
    ApiSpecification.components["schemas"]["ContentInlineElement"];

export type ApiContentTextInlineElement =
    ApiSpecification.components["schemas"]["ContentTextInlineElement"];

export type ApiContentBreakInlineElement =
    ApiSpecification.components["schemas"]["ContentBreakInlineElement"];

export type ApiContentMentionInlineElement =
    ApiSpecification.components["schemas"]["ContentMentionInlineElement"];

export type ApiContentInlineElementMark =
    ApiSpecification.components["schemas"]["ContentInlineElementMark"];

export type ApiContentBoldMark = ApiSpecification.components["schemas"]["ContentBoldMark"];

export type ApiContentItalicMark = ApiSpecification.components["schemas"]["ContentItalicMark"];

export type ApiContentStrikeMark = ApiSpecification.components["schemas"]["ContentStrikeMark"];

export type ApiContentLinkMark = ApiSpecification.components["schemas"]["ContentLinkMark"];

export type ApiContentCodeMark = ApiSpecification.components["schemas"]["ContentCodeMark"];

export type ApiContentHighlightMark =
    ApiSpecification.components["schemas"]["ContentHighlightMark"];

export type ApiContentHighlightMarkColor =
    ApiSpecification.components["schemas"]["ContentHighlightMarkColor"];

export type ApiContentCommentMark = ApiSpecification.components["schemas"]["ContentCommentMark"];

export type ApiContentCodeBlockElementTextInlineElement =
    ApiSpecification.components["schemas"]["ContentCodeBlockElementTextInlineElement"];

export type ApiContentCodeBlockElementTextInlineElementMark =
    ApiSpecification.components["schemas"]["ContentCodeBlockElementTextInlineElementMark"];

export type ApiAccountWithoutSpace = ApiSpecification.components["schemas"]["AccountWithoutSpace"];

export type ApiAccountWithoutSpaceResponse =
    ApiSpecification.components["schemas"]["AccountWithoutSpace_Response"];

export type ApiSpace = ApiSpecification.components["schemas"]["Space"];

export type ApiAccount = ApiSpecification.components["schemas"]["Account"];

export type ApiAccountResponse = ApiSpecification.components["schemas"]["Account_Response"];

export type ApiAccountSpace = ApiSpecification.components["schemas"]["AccountSpace"];

export type ApiAccountSpaceInactive =
    ApiSpecification.components["schemas"]["AccountSpaceInactive"];

export type ApiAccountSpaceRemovedInactive =
    ApiSpecification.components["schemas"]["AccountSpaceRemovedInactive"];

export type ApiAccountSpaceInvitePendingInactive =
    ApiSpecification.components["schemas"]["AccountSpaceInvitePendingInactive"];

export type ApiInbox = ApiSpecification.components["schemas"]["Inbox"];

export type ApiInboxEntryShared = ApiSpecification.components["schemas"]["InboxEntryShared"];

export type ApiInboxEntryTitleItem = ApiSpecification.components["schemas"]["InboxEntryTitleItem"];

export type ApiInboxEntryTitleTextItem =
    ApiSpecification.components["schemas"]["InboxEntryTitleTextItem"];

export type ApiInboxEntryTitleAccountItem =
    ApiSpecification.components["schemas"]["InboxEntryTitleAccountItem"];

export type ApiInboxEntryAccountFeatured =
    ApiSpecification.components["schemas"]["InboxEntryAccountFeatured"];

export type ApiInboxEntry = ApiSpecification.components["schemas"]["InboxEntry"];

export type ApiInboxChatEntry = ApiSpecification.components["schemas"]["InboxChatEntry"];

export type ApiInboxCreatedChannelPostsEntry =
    ApiSpecification.components["schemas"]["InboxCreatedChannelPostsEntry"];

export type ApiInboxPostEntry = ApiSpecification.components["schemas"]["InboxPostEntry"];

export type ApiInboxCreatedDocumentThreadsEntry =
    ApiSpecification.components["schemas"]["InboxCreatedDocumentThreadsEntry"];

export type ApiInboxDocumentThreadEntry =
    ApiSpecification.components["schemas"]["InboxDocumentThreadEntry"];

export type ApiInboxTaskMessagesEntry =
    ApiSpecification.components["schemas"]["InboxTaskMessagesEntry"];

export type ApiChat = ApiSpecification.components["schemas"]["Chat"];

export type ApiDirectChat = ApiSpecification.components["schemas"]["DirectChat"];

export type ApiRoomChat = ApiSpecification.components["schemas"]["RoomChat"];

export type ApiCreateChatRequestBodyChat =
    ApiSpecification.components["schemas"]["CreateChatRequestBodyChat"];

export type ApiCreateChatRequestBodyDirectChat =
    ApiSpecification.components["schemas"]["CreateChatRequestBodyDirectChat"];

export type ApiCreateChatRequestBodyRoomChat =
    ApiSpecification.components["schemas"]["CreateChatRequestBodyRoomChat"];

export type ApiDocument = ApiSpecification.components["schemas"]["Document"];

export type ApiDocumentPreview = ApiSpecification.components["schemas"]["DocumentPreview"];

export type ApiDocumentThreadPreview =
    ApiSpecification.components["schemas"]["DocumentThreadPreview"];

export type ApiDocumentThread = ApiSpecification.components["schemas"]["DocumentThread"];

export type ApiChannelPreview = ApiSpecification.components["schemas"]["ChannelPreview"];

export type ApiChannel = ApiSpecification.components["schemas"]["Channel"];

export type ApiPost = ApiSpecification.components["schemas"]["Post"];

export type ApiPostPreview = ApiSpecification.components["schemas"]["PostPreview"];

export type ApiTaskQueryItem = ApiSpecification.components["schemas"]["TaskQueryItem"];

export type ApiTask = ApiSpecification.components["schemas"]["Task"];

export type ApiTaskWithoutNotes = ApiSpecification.components["schemas"]["TaskWithoutNotes"];

export type ApiTaskSubtasks = ApiSpecification.components["schemas"]["TaskSubtasks"];

export type ApiTaskPreview = ApiSpecification.components["schemas"]["TaskPreview"];

export type ApiTaskDue = ApiSpecification.components["schemas"]["TaskDue"];

export type ApiTaskPriority = ApiSpecification.components["schemas"]["TaskPriority"];

export type ApiTaskLowPriority = ApiSpecification.components["schemas"]["TaskLowPriority"];

export type ApiTaskMediumPriority = ApiSpecification.components["schemas"]["TaskMediumPriority"];

export type ApiTaskHighPriority = ApiSpecification.components["schemas"]["TaskHighPriority"];

export type ApiTaskUrgentPriority = ApiSpecification.components["schemas"]["TaskUrgentPriority"];

export type ApiTaskNotes = ApiSpecification.components["schemas"]["TaskNotes"];

export type ApiTaskLayout = ApiSpecification.components["schemas"]["TaskLayout"];

export type ApiTaskParent = ApiSpecification.components["schemas"]["TaskParent"];

export type ApiTaskParentResponse = ApiSpecification.components["schemas"]["TaskParent_Response"];

export type ApiTaskCollectionItem = ApiSpecification.components["schemas"]["TaskCollectionItem"];

export type ApiPatchTaskResponseCollection =
    ApiSpecification.components["schemas"]["PatchTaskResponseCollection"];

export type ApiTaskPatch = ApiSpecification.components["schemas"]["TaskPatch"];

export type ApiTaskSetTitlePatch = ApiSpecification.components["schemas"]["TaskSetTitlePatch"];

export type ApiTaskSetAssigneePatch =
    ApiSpecification.components["schemas"]["TaskSetAssigneePatch"];

export type ApiTaskSetStatusPatch = ApiSpecification.components["schemas"]["TaskSetStatusPatch"];

export type ApiTaskSetDuePatch = ApiSpecification.components["schemas"]["TaskSetDuePatch"];

export type ApiTaskSetPriorityPatch =
    ApiSpecification.components["schemas"]["TaskSetPriorityPatch"];

export type ApiTaskSetLayoutPatch = ApiSpecification.components["schemas"]["TaskSetLayoutPatch"];

export type ApiTaskSetParentPatch = ApiSpecification.components["schemas"]["TaskSetParentPatch"];

export type ApiTaskMoveInParentPatch =
    ApiSpecification.components["schemas"]["TaskMoveInParentPatch"];

export type ApiTaskAddCollectionPatch =
    ApiSpecification.components["schemas"]["TaskAddCollectionPatch"];

export type ApiTaskRemoveCollectionPatch =
    ApiSpecification.components["schemas"]["TaskRemoveCollectionPatch"];

export type ApiTaskMoveInCollectionPatch =
    ApiSpecification.components["schemas"]["TaskMoveInCollectionPatch"];

export type ApiTaskMoveInQueryPatchPosition =
    ApiSpecification.components["schemas"]["TaskMoveInQueryPatchPosition"];

export type ApiTaskMoveInQueryPatchStartPosition =
    ApiSpecification.components["schemas"]["TaskMoveInQueryPatchStartPosition"];

export type ApiTaskMoveInQueryPatchEndPosition =
    ApiSpecification.components["schemas"]["TaskMoveInQueryPatchEndPosition"];

export type ApiTaskMoveInQueryPatchBetweenPosition =
    ApiSpecification.components["schemas"]["TaskMoveInQueryPatchBetweenPosition"];

export type ApiTaskCollectionPatch = ApiSpecification.components["schemas"]["TaskCollectionPatch"];

export type ApiTaskCollectionSetNamePatch =
    ApiSpecification.components["schemas"]["TaskCollectionSetNamePatch"];

export type ApiTaskCollectionSetColorPatch =
    ApiSpecification.components["schemas"]["TaskCollectionSetColorPatch"];

export type ApiTaskStatus = ApiSpecification.components["schemas"]["TaskStatus"];

export type ApiTaskOpenStatus = ApiSpecification.components["schemas"]["TaskOpenStatus"];

export type ApiTaskClosedStatus = ApiSpecification.components["schemas"]["TaskClosedStatus"];

export type ApiTaskCollection = ApiSpecification.components["schemas"]["TaskCollection"];

export type ApiTaskCollectionResponse =
    ApiSpecification.components["schemas"]["TaskCollection_Response"];

export type ApiTaskCollectionPreview =
    ApiSpecification.components["schemas"]["TaskCollectionPreview"];

export type ApiTaskCollectionPreviewResponse =
    ApiSpecification.components["schemas"]["TaskCollectionPreview_Response"];

export type ApiTaskQueryDefaults = ApiSpecification.components["schemas"]["TaskQueryDefaults"];

export type ApiTaskQueryDefaultsResponse =
    ApiSpecification.components["schemas"]["TaskQueryDefaults_Response"];

export type ApiTaskQueryFilter = ApiSpecification.components["schemas"]["TaskQueryFilter"];

export type ApiTaskQueryStatusFilter =
    ApiSpecification.components["schemas"]["TaskQueryStatusFilter"];

export type ApiTaskQueryStatusFilterOperation =
    ApiSpecification.components["schemas"]["TaskQueryStatusFilterOperation"];

export type ApiTaskQueryStatusFilterOneOfOperation =
    ApiSpecification.components["schemas"]["TaskQueryStatusFilterOneOfOperation"];

export type ApiTaskQueryStatusFilterNoneOfOperation =
    ApiSpecification.components["schemas"]["TaskQueryStatusFilterNoneOfOperation"];

export type ApiTaskQueryCollectionsFilter =
    ApiSpecification.components["schemas"]["TaskQueryCollectionsFilter"];

export type ApiTaskQueryCollectionsFilterOperation =
    ApiSpecification.components["schemas"]["TaskQueryCollectionsFilterOperation"];

export type ApiTaskQueryCollectionsFilterIncludesOneOfOperation =
    ApiSpecification.components["schemas"]["TaskQueryCollectionsFilterIncludesOneOfOperation"];

export type ApiTaskQueryCollectionsFilterIncludesAllOfOperation =
    ApiSpecification.components["schemas"]["TaskQueryCollectionsFilterIncludesAllOfOperation"];

export type ApiTaskQueryCollectionsFilterExcludesAllOfOperation =
    ApiSpecification.components["schemas"]["TaskQueryCollectionsFilterExcludesAllOfOperation"];

export type ApiTaskQueryCollectionsFilterIsEmptyOperation =
    ApiSpecification.components["schemas"]["TaskQueryCollectionsFilterIsEmptyOperation"];

export type ApiTaskQueryPriorityFilter =
    ApiSpecification.components["schemas"]["TaskQueryPriorityFilter"];

export type ApiTaskQueryPriorityFilterOperation =
    ApiSpecification.components["schemas"]["TaskQueryPriorityFilterOperation"];

export type ApiTaskQueryPriorityFilterOneOfOperation =
    ApiSpecification.components["schemas"]["TaskQueryPriorityFilterOneOfOperation"];

export type ApiTaskQueryPriorityFilterNoneOfOperation =
    ApiSpecification.components["schemas"]["TaskQueryPriorityFilterNoneOfOperation"];

export type ApiTaskQueryLayoutFilter =
    ApiSpecification.components["schemas"]["TaskQueryLayoutFilter"];

export type ApiTaskQueryLayoutFilterOperation =
    ApiSpecification.components["schemas"]["TaskQueryLayoutFilterOperation"];

export type ApiTaskQueryLayoutFilterOneOfOperation =
    ApiSpecification.components["schemas"]["TaskQueryLayoutFilterOneOfOperation"];

export type ApiTaskQueryLayoutFilterNoneOfOperation =
    ApiSpecification.components["schemas"]["TaskQueryLayoutFilterNoneOfOperation"];

export type ApiTaskQueryTitleFilter =
    ApiSpecification.components["schemas"]["TaskQueryTitleFilter"];

export type ApiTaskQueryTitleFilterOperation =
    ApiSpecification.components["schemas"]["TaskQueryTitleFilterOperation"];

export type ApiTaskQueryTitleFilterIncludesOperation =
    ApiSpecification.components["schemas"]["TaskQueryTitleFilterIncludesOperation"];

export type ApiTaskQueryTitleFilterExcludesOperation =
    ApiSpecification.components["schemas"]["TaskQueryTitleFilterExcludesOperation"];

export type ApiTaskQueryAssigneeFilter =
    ApiSpecification.components["schemas"]["TaskQueryAssigneeFilter"];

export type ApiTaskQueryCreatorFilter =
    ApiSpecification.components["schemas"]["TaskQueryCreatorFilter"];

export type ApiTaskQueryAssignerFilter =
    ApiSpecification.components["schemas"]["TaskQueryAssignerFilter"];

export type ApiTaskQueryAccountFilterOperation =
    ApiSpecification.components["schemas"]["TaskQueryAccountFilterOperation"];

export type ApiTaskQueryAccountFilterOneOfOperation =
    ApiSpecification.components["schemas"]["TaskQueryAccountFilterOneOfOperation"];

export type ApiTaskQueryAccountFilterNoneOfOperation =
    ApiSpecification.components["schemas"]["TaskQueryAccountFilterNoneOfOperation"];

export type ApiTaskQueryAccountFilterOperationAccount =
    ApiSpecification.components["schemas"]["TaskQueryAccountFilterOperationAccount"];

export type ApiTaskQueryAccountFilterOperationAccountItem =
    ApiSpecification.components["schemas"]["TaskQueryAccountFilterOperationAccountItem"];

export type ApiTaskQueryAccountFilterOperationCurrentAccount =
    ApiSpecification.components["schemas"]["TaskQueryAccountFilterOperationCurrentAccount"];

export type ApiTaskQueryAccountFilterOperationMissingAccount =
    ApiSpecification.components["schemas"]["TaskQueryAccountFilterOperationMissingAccount"];

export type ApiTaskQueryCreatorFilterOperation =
    ApiSpecification.components["schemas"]["TaskQueryCreatorFilterOperation"];

export type ApiTaskQueryCreatorFilterOneOfOperation =
    ApiSpecification.components["schemas"]["TaskQueryCreatorFilterOneOfOperation"];

export type ApiTaskQueryCreatorFilterNoneOfOperation =
    ApiSpecification.components["schemas"]["TaskQueryCreatorFilterNoneOfOperation"];

export type ApiTaskQueryCreatorFilterOperationAccount =
    ApiSpecification.components["schemas"]["TaskQueryCreatorFilterOperationAccount"];

export type ApiTaskQueryDueFilter = ApiSpecification.components["schemas"]["TaskQueryDueFilter"];

export type ApiTaskQueryDueFilterOperation =
    ApiSpecification.components["schemas"]["TaskQueryDueFilterOperation"];

export type ApiTaskQueryDueFilterOverdueOperation =
    ApiSpecification.components["schemas"]["TaskQueryDueFilterOverdueOperation"];

export type ApiTaskQueryDueFilterIsEmptyOperation =
    ApiSpecification.components["schemas"]["TaskQueryDueFilterIsEmptyOperation"];

export type ApiTaskQueryCreatedTimeFilter =
    ApiSpecification.components["schemas"]["TaskQueryCreatedTimeFilter"];

export type ApiTaskQueryAssignedTimeFilter =
    ApiSpecification.components["schemas"]["TaskQueryAssignedTimeFilter"];

export type ApiTaskQueryClosedTimeFilter =
    ApiSpecification.components["schemas"]["TaskQueryClosedTimeFilter"];

export type ApiTaskQueryActivatedTimeFilter =
    ApiSpecification.components["schemas"]["TaskQueryActivatedTimeFilter"];

export type ApiTaskQueryTimeFilterOperation =
    ApiSpecification.components["schemas"]["TaskQueryTimeFilterOperation"];

export type ApiTaskQueryTimeFilterLessThanOperation =
    ApiSpecification.components["schemas"]["TaskQueryTimeFilterLessThanOperation"];

export type ApiTaskQueryTimeFilterGreaterThanOperation =
    ApiSpecification.components["schemas"]["TaskQueryTimeFilterGreaterThanOperation"];

export type ApiTaskQueryTimeFilterOperationTime =
    ApiSpecification.components["schemas"]["TaskQueryTimeFilterOperationTime"];

export type ApiTaskQueryTimeFilterOperationAbsoluteDateTime =
    ApiSpecification.components["schemas"]["TaskQueryTimeFilterOperationAbsoluteDateTime"];

export type ApiTaskQueryTimeFilterOperationRelativeTodayTime =
    ApiSpecification.components["schemas"]["TaskQueryTimeFilterOperationRelativeTodayTime"];

export type ApiTaskQueryTimeFilterOperationRelativeAfterTodayTime =
    ApiSpecification.components["schemas"]["TaskQueryTimeFilterOperationRelativeAfterTodayTime"];

export type ApiTaskQueryTimeFilterOperationRelativeBeforeTodayTime =
    ApiSpecification.components["schemas"]["TaskQueryTimeFilterOperationRelativeBeforeTodayTime"];

export type ApiTaskQueryTimeFilterOperationDuration =
    ApiSpecification.components["schemas"]["TaskQueryTimeFilterOperationDuration"];

export type ApiTaskQueryTimeFilterOperationDaysDuration =
    ApiSpecification.components["schemas"]["TaskQueryTimeFilterOperationDaysDuration"];

export type ApiTaskQueryTimeFilterOperationWeeksDuration =
    ApiSpecification.components["schemas"]["TaskQueryTimeFilterOperationWeeksDuration"];

export type ApiTaskQueryTimeFilterOperationMonthsDuration =
    ApiSpecification.components["schemas"]["TaskQueryTimeFilterOperationMonthsDuration"];

export type ApiTaskQueryTimeFilterOperationYearsDuration =
    ApiSpecification.components["schemas"]["TaskQueryTimeFilterOperationYearsDuration"];

export type ApiTaskQuerySort = ApiSpecification.components["schemas"]["TaskQuerySort"];

export type ApiTaskQuerySortDirection =
    ApiSpecification.components["schemas"]["TaskQuerySortDirection"];

export type ApiTaskQuerySortMissing =
    ApiSpecification.components["schemas"]["TaskQuerySortMissing"];

export type ApiTaskQueryStatusSort = ApiSpecification.components["schemas"]["TaskQueryStatusSort"];

export type ApiTaskQueryPrioritySort =
    ApiSpecification.components["schemas"]["TaskQueryPrioritySort"];

export type ApiTaskQueryLayoutSort = ApiSpecification.components["schemas"]["TaskQueryLayoutSort"];

export type ApiTaskQueryAssigneeSort =
    ApiSpecification.components["schemas"]["TaskQueryAssigneeSort"];

export type ApiTaskQueryCreatorSort =
    ApiSpecification.components["schemas"]["TaskQueryCreatorSort"];

export type ApiTaskQueryAssignerSort =
    ApiSpecification.components["schemas"]["TaskQueryAssignerSort"];

export type ApiTaskQueryDueSort = ApiSpecification.components["schemas"]["TaskQueryDueSort"];

export type ApiTaskQueryCreatedTimeSort =
    ApiSpecification.components["schemas"]["TaskQueryCreatedTimeSort"];

export type ApiTaskQueryAssignedTimeSort =
    ApiSpecification.components["schemas"]["TaskQueryAssignedTimeSort"];

export type ApiTaskQueryClosedTimeSort =
    ApiSpecification.components["schemas"]["TaskQueryClosedTimeSort"];

export type ApiTaskQueryActivatedTimeSort =
    ApiSpecification.components["schemas"]["TaskQueryActivatedTimeSort"];

export type ApiMessage = ApiSpecification.components["schemas"]["Message"];

export type ApiMessagePayload = ApiSpecification.components["schemas"]["MessagePayload"];

export type ApiMessageContentPayload =
    ApiSpecification.components["schemas"]["MessageContentPayload"];

export type ApiMessageContentPayloadResponse =
    ApiSpecification.components["schemas"]["MessageContentPayload_Response"];

export type ApiMessageContentPayloadFile =
    ApiSpecification.components["schemas"]["MessageContentPayloadFile"];

export type ApiMessageContentPayloadFileResponse =
    ApiSpecification.components["schemas"]["MessageContentPayloadFile_Response"];

export type ApiMessageContentPayloadPreviewElement =
    ApiSpecification.components["schemas"]["MessageContentPayloadPreviewElement"];

export type ApiMessageContentPayloadPreviewElementResponse =
    ApiSpecification.components["schemas"]["MessageContentPayloadPreviewElement_Response"];

export type ApiMessageContentPayloadParent =
    ApiSpecification.components["schemas"]["MessageContentPayloadParent"];

export type ApiMessageContentPayloadMessageParent =
    ApiSpecification.components["schemas"]["MessageContentPayloadMessageParent"];

export type ApiMessageContentPayloadMessageParentResponse =
    ApiSpecification.components["schemas"]["MessageContentPayloadMessageParent_Response"];

export type ApiMessageContentPayloadPostParent =
    ApiSpecification.components["schemas"]["MessageContentPayloadPostParent"];

export type ApiMessageContentPayloadPostParentResponse =
    ApiSpecification.components["schemas"]["MessageContentPayloadPostParent_Response"];

export type ApiMessageDeletedPayload =
    ApiSpecification.components["schemas"]["MessageDeletedPayload"];

export type ApiMessageStreamPart = ApiSpecification.components["schemas"]["MessageStreamPart"];

export type ApiMessageStreamPartPayload =
    ApiSpecification.components["schemas"]["MessageStreamPartPayload"];

export type ApiMessageStreamContentPartPayload =
    ApiSpecification.components["schemas"]["MessageStreamContentPartPayload"];

export type ApiMessageStreamReasoningPartPayload =
    ApiSpecification.components["schemas"]["MessageStreamReasoningPartPayload"];

export type ApiMessageStreamToolCallPartPayload =
    ApiSpecification.components["schemas"]["MessageStreamToolCallPartPayload"];

export type ApiMessageStreamToolCallPartPayloadCall =
    ApiSpecification.components["schemas"]["MessageStreamToolCallPartPayloadCall"];

export type ApiMessageStreamToolCallPartPayloadReadCall =
    ApiSpecification.components["schemas"]["MessageStreamToolCallPartPayloadReadCall"];

export type ApiMessageStreamToolCallPartPayloadSearchCall =
    ApiSpecification.components["schemas"]["MessageStreamToolCallPartPayloadSearchCall"];

export type ApiMessageStreamToolCallPartPayloadCreateCall =
    ApiSpecification.components["schemas"]["MessageStreamToolCallPartPayloadCreateCall"];

export type ApiMessageStreamToolCallPartCreateCallReference =
    ApiSpecification.components["schemas"]["MessageStreamToolCallPartCreateCallReference"];

export type ApiBotWebhookEvent = ApiSpecification.components["schemas"]["BotWebhookEvent"];

export type ApiBotWebhookCreatedMessageEvent =
    ApiSpecification.components["schemas"]["BotWebhookCreatedMessageEvent"];

export type ApiBotWebhookCreatedMessageEventParent =
    ApiSpecification.components["schemas"]["BotWebhookCreatedMessageEventParent"];

export type ApiBotWebhookCreatedMessageEventMessageParent =
    ApiSpecification.components["schemas"]["BotWebhookCreatedMessageEventMessageParent"];

export type ApiBotWebhookCreatedMessageEventPostParent =
    ApiSpecification.components["schemas"]["BotWebhookCreatedMessageEventPostParent"];

export type ApiBotWebhookCreatedPostEvent =
    ApiSpecification.components["schemas"]["BotWebhookCreatedPostEvent"];

export type ApiMessageContentPayloadParentContentSnippet =
    ApiSpecification.components["schemas"]["MessageContentPayloadParentContentSnippet"];

export type ApiMessageContentPayloadParentContentSnippetTextInlineElement =
    ApiSpecification.components["schemas"]["MessageContentPayloadParentContentSnippetTextInlineElement"];

export type ApiMessageContentPayloadParentContentSnippetInlineElementMark =
    ApiSpecification.components["schemas"]["MessageContentPayloadParentContentSnippetInlineElementMark"];

export type ApiMessageRoomReference =
    ApiSpecification.components["schemas"]["MessageRoomReference"];

export type ApiChatMessageRoomReference =
    ApiSpecification.components["schemas"]["ChatMessageRoomReference"];

export type ApiDocumentThreadMessageRoomReference =
    ApiSpecification.components["schemas"]["DocumentThreadMessageRoomReference"];

export type ApiPostMessageRoomReference =
    ApiSpecification.components["schemas"]["PostMessageRoomReference"];

export type ApiTaskMessageRoomReference =
    ApiSpecification.components["schemas"]["TaskMessageRoomReference"];

export type ApiSearchResult = ApiSpecification.components["schemas"]["SearchResult"];

export type ApiSearchAccountResult = ApiSpecification.components["schemas"]["SearchAccountResult"];

export type ApiSearchChannelResult = ApiSpecification.components["schemas"]["SearchChannelResult"];

export type ApiSearchChatResult = ApiSpecification.components["schemas"]["SearchChatResult"];

export type ApiSearchChatMessageResult =
    ApiSpecification.components["schemas"]["SearchChatMessageResult"];

export type ApiSearchDocumentResult =
    ApiSpecification.components["schemas"]["SearchDocumentResult"];

export type ApiSearchDocumentMessageResult =
    ApiSpecification.components["schemas"]["SearchDocumentMessageResult"];

export type ApiSearchPostResult = ApiSpecification.components["schemas"]["SearchPostResult"];

export type ApiSearchPostMessageResult =
    ApiSpecification.components["schemas"]["SearchPostMessageResult"];

export type ApiSearchSiteResult = ApiSpecification.components["schemas"]["SearchSiteResult"];

export type ApiSearchTaskResult = ApiSpecification.components["schemas"]["SearchTaskResult"];

export type ApiSearchTaskMessageResult =
    ApiSpecification.components["schemas"]["SearchTaskMessageResult"];

export type ApiSearchTaskCollectionResult =
    ApiSpecification.components["schemas"]["SearchTaskCollectionResult"];

export type ApiSearchResultBodyMatch =
    ApiSpecification.components["schemas"]["SearchResultBodyMatch"];

export type ApiSearchResultParsedFilter =
    ApiSpecification.components["schemas"]["SearchResultParsedFilter"];

export type ApiDocumentThreadResponse =
    ApiSpecification.components["schemas"]["DocumentThread_Response"];

export type ApiDocumentThreadPreviewResponse =
    ApiSpecification.components["schemas"]["DocumentThreadPreview_Response"];

export type ApiPostPreviewResponse = ApiSpecification.components["schemas"]["PostPreview_Response"];

export type ApiTaskCollectionItemResponse =
    ApiSpecification.components["schemas"]["TaskCollectionItem_Response"];

export type ApiTaskResponse = ApiSpecification.components["schemas"]["Task_Response"];

export type ApiMessageContentPayloadParentResponse =
    ApiSpecification.components["schemas"]["MessageContentPayloadParent_Response"];

export type ApiMessageResponse = ApiSpecification.components["schemas"]["Message_Response"];

export type ApiPostResponse = ApiSpecification.components["schemas"]["Post_Response"];

export type ApiPreviewReferenceResponse =
    ApiSpecification.components["schemas"]["PreviewReference_Response"];

export type ApiInboxChatEntryResponse =
    ApiSpecification.components["schemas"]["InboxChatEntry_Response"];

export type ApiInboxCreatedChannelPostsEntryResponse =
    ApiSpecification.components["schemas"]["InboxCreatedChannelPostsEntry_Response"];

export type ApiInboxPostEntryResponse =
    ApiSpecification.components["schemas"]["InboxPostEntry_Response"];

export type ApiInboxCreatedDocumentThreadsEntryResponse =
    ApiSpecification.components["schemas"]["InboxCreatedDocumentThreadsEntry_Response"];

export type ApiInboxDocumentThreadEntryResponse =
    ApiSpecification.components["schemas"]["InboxDocumentThreadEntry_Response"];

export type ApiInboxTaskMessagesEntryResponse =
    ApiSpecification.components["schemas"]["InboxTaskMessagesEntry_Response"];

export type ApiCreateChatRequestBodyDirectChatResponse =
    ApiSpecification.components["schemas"]["CreateChatRequestBodyDirectChat_Response"];

export type ApiContentBlockElementResponse =
    ApiSpecification.components["schemas"]["ContentBlockElement_Response"];

export type ApiSearchChatMessageResultResponse =
    ApiSpecification.components["schemas"]["SearchChatMessageResult_Response"];

export type ApiSearchDocumentMessageResultResponse =
    ApiSpecification.components["schemas"]["SearchDocumentMessageResult_Response"];

export type ApiSearchPostResultResponse =
    ApiSpecification.components["schemas"]["SearchPostResult_Response"];

export type ApiSearchPostMessageResultResponse =
    ApiSpecification.components["schemas"]["SearchPostMessageResult_Response"];

export type ApiSearchTaskMessageResultResponse =
    ApiSpecification.components["schemas"]["SearchTaskMessageResult_Response"];

export type ApiTaskSetAssigneePatchResponse =
    ApiSpecification.components["schemas"]["TaskSetAssigneePatch_Response"];

export type ApiTaskSetParentPatchResponse =
    ApiSpecification.components["schemas"]["TaskSetParentPatch_Response"];

export type ApiTaskWithoutNotesResponse =
    ApiSpecification.components["schemas"]["TaskWithoutNotes_Response"];

export type ApiDirectChatResponse = ApiSpecification.components["schemas"]["DirectChat_Response"];

export type ApiMessagePayloadResponse =
    ApiSpecification.components["schemas"]["MessagePayload_Response"];

export type ApiInboxEntryAccountFeaturedResponse =
    ApiSpecification.components["schemas"]["InboxEntryAccountFeatured_Response"];

export type ApiContentCodeBlockElementResponse =
    ApiSpecification.components["schemas"]["ContentCodeBlockElement_Response"];

export type ApiContentFileFloatBlockElementResponse =
    ApiSpecification.components["schemas"]["ContentFileFloatBlockElement_Response"];

export type ApiMentionReferenceResponse =
    ApiSpecification.components["schemas"]["MentionReference_Response"];

export type ApiInboxEntryTitleAccountItemResponse =
    ApiSpecification.components["schemas"]["InboxEntryTitleAccountItem_Response"];

export type ApiContentListBlockElementItemResponse =
    ApiSpecification.components["schemas"]["ContentListBlockElementItem_Response"];

export type ApiContentCheckListBlockElementItemResponse =
    ApiSpecification.components["schemas"]["ContentCheckListBlockElementItem_Response"];

export type ApiContentQuoteBlockElementBlockElementResponse =
    ApiSpecification.components["schemas"]["ContentQuoteBlockElementBlockElement_Response"];

export type ApiContentFileGalleryBlockElementRowResponse =
    ApiSpecification.components["schemas"]["ContentFileGalleryBlockElementRow_Response"];

export type ApiTaskQueryCollectionsFilterIncludesOneOfOperationResponse =
    ApiSpecification.components["schemas"]["TaskQueryCollectionsFilterIncludesOneOfOperation_Response"];

export type ApiTaskQueryCollectionsFilterIncludesAllOfOperationResponse =
    ApiSpecification.components["schemas"]["TaskQueryCollectionsFilterIncludesAllOfOperation_Response"];

export type ApiTaskQueryCollectionsFilterExcludesAllOfOperationResponse =
    ApiSpecification.components["schemas"]["TaskQueryCollectionsFilterExcludesAllOfOperation_Response"];

export type ApiMessageStreamToolCallPartCreateCallReferenceResponse =
    ApiSpecification.components["schemas"]["MessageStreamToolCallPartCreateCallReference_Response"];

export type ApiContentTableBlockElementCellBlockElementResponse =
    ApiSpecification.components["schemas"]["ContentTableBlockElementCellBlockElement_Response"];

export type ApiTaskQueryAccountFilterOperationAccountItemResponse =
    ApiSpecification.components["schemas"]["TaskQueryAccountFilterOperationAccountItem_Response"];

export type ApiContentBlockElementResponseWithoutKeys =
    ApiSpecification.components["schemas"]["ContentBlockElement_Response_WithoutKeys"];

export type ApiContentCodeBlockElementResponseWithoutKeys =
    ApiSpecification.components["schemas"]["ContentCodeBlockElement_Response_WithoutKeys"];

export type ApiContentFileFloatBlockElementResponseWithoutKeys =
    ApiSpecification.components["schemas"]["ContentFileFloatBlockElement_Response_WithoutKeys"];

export type ApiContentListBlockElementItemResponseWithoutKeys =
    ApiSpecification.components["schemas"]["ContentListBlockElementItem_Response_WithoutKeys"];

export type ApiContentCheckListBlockElementItemResponseWithoutKeys =
    ApiSpecification.components["schemas"]["ContentCheckListBlockElementItem_Response_WithoutKeys"];

export type ApiContentQuoteBlockElementBlockElementResponseWithoutKeys =
    ApiSpecification.components["schemas"]["ContentQuoteBlockElementBlockElement_Response_WithoutKeys"];

export type ApiContentFileGalleryBlockElementRowItemResponseWithoutKeys =
    ApiSpecification.components["schemas"]["ContentFileGalleryBlockElementRowItem_Response_WithoutKeys"];

export type ApiContentTableBlockElementCellBlockElementResponseWithoutKeys =
    ApiSpecification.components["schemas"]["ContentTableBlockElementCellBlockElement_Response_WithoutKeys"];

export type ApiInboxEntryResponse = ApiSpecification.components["schemas"]["InboxEntry_Response"];

export type ApiCreateChatRequestBodyChatResponse =
    ApiSpecification.components["schemas"]["CreateChatRequestBodyChat_Response"];

export type ApiContentResponse = ApiSpecification.components["schemas"]["Content_Response"];

export type ApiSearchResultResponse =
    ApiSpecification.components["schemas"]["SearchResult_Response"];

export type ApiTaskPatchResponse = ApiSpecification.components["schemas"]["TaskPatch_Response"];

export type ApiTaskQueryItemResponse =
    ApiSpecification.components["schemas"]["TaskQueryItem_Response"];

export type ApiChatResponse = ApiSpecification.components["schemas"]["Chat_Response"];

export type ApiTaskAddCollectionPatchResponse =
    ApiSpecification.components["schemas"]["TaskAddCollectionPatch_Response"];

export type ApiBotWebhookCreatedMessageEventResponse =
    ApiSpecification.components["schemas"]["BotWebhookCreatedMessageEvent_Response"];

export type ApiContentMentionInlineElementResponse =
    ApiSpecification.components["schemas"]["ContentMentionInlineElement_Response"];

export type ApiInboxEntryTitleItemResponse =
    ApiSpecification.components["schemas"]["InboxEntryTitleItem_Response"];

export type ApiContentUnorderedListBlockElementResponse =
    ApiSpecification.components["schemas"]["ContentUnorderedListBlockElement_Response"];

export type ApiContentOrderedListBlockElementResponse =
    ApiSpecification.components["schemas"]["ContentOrderedListBlockElement_Response"];

export type ApiContentCheckListBlockElementResponse =
    ApiSpecification.components["schemas"]["ContentCheckListBlockElement_Response"];

export type ApiContentQuoteBlockElementResponse =
    ApiSpecification.components["schemas"]["ContentQuoteBlockElement_Response"];

export type ApiContentFileGalleryBlockElementResponse =
    ApiSpecification.components["schemas"]["ContentFileGalleryBlockElement_Response"];

export type ApiTaskQueryCollectionsFilterOperationResponse =
    ApiSpecification.components["schemas"]["TaskQueryCollectionsFilterOperation_Response"];

export type ApiMessageStreamToolCallPartPayloadReadCallResponse =
    ApiSpecification.components["schemas"]["MessageStreamToolCallPartPayloadReadCall_Response"];

export type ApiMessageStreamToolCallPartPayloadCreateCallResponse =
    ApiSpecification.components["schemas"]["MessageStreamToolCallPartPayloadCreateCall_Response"];

export type ApiContentTableBlockElementCellResponse =
    ApiSpecification.components["schemas"]["ContentTableBlockElementCell_Response"];

export type ApiTaskQueryAccountFilterOperationAccountResponse =
    ApiSpecification.components["schemas"]["TaskQueryAccountFilterOperationAccount_Response"];

export type ApiTaskQueryCreatorFilterOperationAccountResponse =
    ApiSpecification.components["schemas"]["TaskQueryCreatorFilterOperationAccount_Response"];

export type ApiContentResponseWithoutKeys =
    ApiSpecification.components["schemas"]["Content_Response_WithoutKeys"];

export type ApiContentUnorderedListBlockElementResponseWithoutKeys =
    ApiSpecification.components["schemas"]["ContentUnorderedListBlockElement_Response_WithoutKeys"];

export type ApiContentOrderedListBlockElementResponseWithoutKeys =
    ApiSpecification.components["schemas"]["ContentOrderedListBlockElement_Response_WithoutKeys"];

export type ApiContentCheckListBlockElementResponseWithoutKeys =
    ApiSpecification.components["schemas"]["ContentCheckListBlockElement_Response_WithoutKeys"];

export type ApiContentQuoteBlockElementResponseWithoutKeys =
    ApiSpecification.components["schemas"]["ContentQuoteBlockElement_Response_WithoutKeys"];

export type ApiContentFileGalleryBlockElementRowResponseWithoutKeys =
    ApiSpecification.components["schemas"]["ContentFileGalleryBlockElementRow_Response_WithoutKeys"];

export type ApiContentTableBlockElementCellResponseWithoutKeys =
    ApiSpecification.components["schemas"]["ContentTableBlockElementCell_Response_WithoutKeys"];

export type ApiDocumentResponse = ApiSpecification.components["schemas"]["Document_Response"];

export type ApiChannelResponse = ApiSpecification.components["schemas"]["Channel_Response"];

export type ApiBotWebhookEventResponse =
    ApiSpecification.components["schemas"]["BotWebhookEvent_Response"];

export type ApiTaskNotesResponse = ApiSpecification.components["schemas"]["TaskNotes_Response"];

export type ApiContentInlineElementResponse =
    ApiSpecification.components["schemas"]["ContentInlineElement_Response"];

export type ApiTaskQueryCollectionsFilterResponse =
    ApiSpecification.components["schemas"]["TaskQueryCollectionsFilter_Response"];

export type ApiMessageStreamContentPartPayloadResponse =
    ApiSpecification.components["schemas"]["MessageStreamContentPartPayload_Response"];

export type ApiMessageStreamReasoningPartPayloadResponse =
    ApiSpecification.components["schemas"]["MessageStreamReasoningPartPayload_Response"];

export type ApiMessageStreamToolCallPartPayloadCallResponse =
    ApiSpecification.components["schemas"]["MessageStreamToolCallPartPayloadCall_Response"];

export type ApiContentTableBlockElementRowResponse =
    ApiSpecification.components["schemas"]["ContentTableBlockElementRow_Response"];

export type ApiTaskQueryAccountFilterOneOfOperationResponse =
    ApiSpecification.components["schemas"]["TaskQueryAccountFilterOneOfOperation_Response"];

export type ApiTaskQueryAccountFilterNoneOfOperationResponse =
    ApiSpecification.components["schemas"]["TaskQueryAccountFilterNoneOfOperation_Response"];

export type ApiTaskQueryCreatorFilterOneOfOperationResponse =
    ApiSpecification.components["schemas"]["TaskQueryCreatorFilterOneOfOperation_Response"];

export type ApiTaskQueryCreatorFilterNoneOfOperationResponse =
    ApiSpecification.components["schemas"]["TaskQueryCreatorFilterNoneOfOperation_Response"];

export type ApiContentListBlockElementResponse =
    ApiSpecification.components["schemas"]["ContentListBlockElement_Response"];

export type ApiContentFileGalleryBlockElementResponseWithoutKeys =
    ApiSpecification.components["schemas"]["ContentFileGalleryBlockElement_Response_WithoutKeys"];

export type ApiContentTableBlockElementRowResponseWithoutKeys =
    ApiSpecification.components["schemas"]["ContentTableBlockElementRow_Response_WithoutKeys"];

export type ApiContentListBlockElementResponseWithoutKeys =
    ApiSpecification.components["schemas"]["ContentListBlockElement_Response_WithoutKeys"];

export type ApiTaskQueryFilterResponse =
    ApiSpecification.components["schemas"]["TaskQueryFilter_Response"];

export type ApiMessageStreamPartPayloadResponse =
    ApiSpecification.components["schemas"]["MessageStreamPartPayload_Response"];

export type ApiMessageStreamToolCallPartPayloadResponse =
    ApiSpecification.components["schemas"]["MessageStreamToolCallPartPayload_Response"];

export type ApiContentTableBlockElementResponse =
    ApiSpecification.components["schemas"]["ContentTableBlockElement_Response"];

export type ApiTaskQueryAccountFilterOperationResponse =
    ApiSpecification.components["schemas"]["TaskQueryAccountFilterOperation_Response"];

export type ApiTaskQueryCreatorFilterOperationResponse =
    ApiSpecification.components["schemas"]["TaskQueryCreatorFilterOperation_Response"];

export type ApiContentTableBlockElementResponseWithoutKeys =
    ApiSpecification.components["schemas"]["ContentTableBlockElement_Response_WithoutKeys"];

export type ApiTaskQueryAssigneeFilterResponse =
    ApiSpecification.components["schemas"]["TaskQueryAssigneeFilter_Response"];

export type ApiTaskQueryCreatorFilterResponse =
    ApiSpecification.components["schemas"]["TaskQueryCreatorFilter_Response"];

export type ApiTaskQueryAssignerFilterResponse =
    ApiSpecification.components["schemas"]["TaskQueryAssignerFilter_Response"];

export type ApiErrorResponse = ApiSpecification.components["responses"]["Error"];

export type ApiGetChatResponse = ApiSpecification.components["responses"]["GetChat"];

export type ApiGetDocumentResponse = ApiSpecification.components["responses"]["GetDocument"];

export type ApiGetTaskResponse = ApiSpecification.components["responses"]["GetTask"];

export type ApiPatchTaskResponse = ApiSpecification.components["responses"]["PatchTask"];

export type ApiPatchTasksResponse = ApiSpecification.components["responses"]["PatchTasks"];

export type ApiGetTaskNotesResponse = ApiSpecification.components["responses"]["GetTaskNotes"];

export type ApiGetTaskCollectionTasksResponse =
    ApiSpecification.components["responses"]["GetTaskCollectionTasks"];

export type ApiGetMessageResponse = ApiSpecification.components["responses"]["GetMessage"];

export type ApiGetMessagesResponse = ApiSpecification.components["responses"]["GetMessages"];

export type ApiGetMessageStreamCompletionResponse =
    ApiSpecification.components["responses"]["GetMessageStreamCompletion"];

export type ApiGetMessageStreamPingResponse =
    ApiSpecification.components["responses"]["GetMessageStreamPing"];

export type ApiGetMessageStreamPartResponse =
    ApiSpecification.components["responses"]["GetMessageStreamPart"];

export type ApiGetPostResponse = ApiSpecification.components["responses"]["GetPost"];

export type ApiCreateMessageRequestBody =
    ApiSpecification.components["requestBodies"]["CreateMessage"];

export type ApiPutMessageStreamPartRequestBody =
    ApiSpecification.components["requestBodies"]["PutMessageStreamPart"];
