load("//admin/typescript:typescript.bzl", "ts_project")

ts_project(
    name = "spaces",
    visibility = ["//visibility:public"],
    deps = [
        "//shared/accounts",
        "//shared/api",
        "//shared/avatar",
        "//shared/design",
        "//shared/error",
        "//shared/helpers",
        "//shared/id",
        "//shared/schema",
    ],
)
