load("//admin/typescript:typescript.bzl", "ts_project")

ts_project(
    name = "spaces",
    test_deps = ["//shared/spaces/test_helpers"],
    visibility = ["//visibility:public"],
    deps = [
        "//shared/accounts",
        "//shared/api/specification",
        "//shared/avatar",
        "//shared/bots/owners",
        "//shared/design",
        "//shared/error",
        "//shared/helpers",
        "//shared/id",
        "//shared/schema",
    ],
)
