load("//admin/typescript:typescript.bzl", "ts_project")

ts_project(
    name = "documentation_meta_tests",
    testonly = True,
    deps = [
        "//:node_modules/@types/node",
        "//app:app_lib",
        "//shared/helpers",
    ],
)
