import {useEffect, useState} from "react";
import {ShouldRevalidateFunction, useSearchParams} from "react-router-dom";
import {PostCreator} from "~/client/web/forum/post_creator.js";
import {createMetaFunction} from "~/client/web/remix/create_meta_function.js";
import {useLoaderDataWithSchema} from "~/client/web/remix/use_loader_data_with_schema.js";
import {getContentReferencesForNode} from "~/server/content/get_content_references.js";
import {FilePostAuthorizer} from "~/server/forum/data/file_post_authorizer.js";
import {getChannelPreview} from "~/server/forum/data/get_channel_preview.js";
import {getPostDraftIfExists} from "~/server/forum/data/get_post_draft_if_exists.js";
import {jsonWithSchema} from "~/server/remix/json_with_schema.js";
import {LoaderArgs} from "~/server/remix/loader_context.js";
import {InvalidArgumentError} from "~/shared/error/error.js";
import {FileEntityIdSchema} from "~/shared/files/file_entity_id.js";
import {ChannelPreviewModel} from "~/shared/forum/channel_model.js";
import {
    PostContentProsemirrorSchema,
    PostContentWithReferencesSchema,
    assertPostContent,
    emptyPostContentWithReferences,
} from "~/shared/forum/post_content_schema.js";
import {runAllPromises} from "~/shared/helpers/async/run_all_promises.js";
import {getChronologicalIdTime} from "~/shared/id/chronological_id.js";
import {isId} from "~/shared/id/id.js";
import {ChannelId, PostDraftId, SpaceId} from "~/shared/id/types/id_types.js";
import {Schema} from "~/shared/schema/schema.js";

const LoaderSchema = Schema.object({
    draftId: Schema.id<PostDraftId>(),
    channel: ChannelPreviewModel.schema().nullable(),
    content: PostContentWithReferencesSchema,
});

export const meta = createMetaFunction(LoaderSchema, () => [{title: "New post"}]);

export async function loader({context: unauthenticatedContext, params, request}: LoaderArgs) {
    const context = (await unauthenticatedContext.actor.authenticate()).actor.authorizeSession();

    const {spaceId, draftId} = params;
    if (!spaceId || !isId<SpaceId>(spaceId)) {
        throw new InvalidArgumentError("Space path segment must be a `SpaceId`");
    }
    if (!draftId || !isId<PostDraftId>(draftId)) {
        throw new InvalidArgumentError("Draft path segment must be an `PostDraftId`");
    }

    // Make sure `draftId` was generated by `generateChronologicalId()` by checking if
    // the time is after some constant time on 2024-10-30 (before we shipped this code
    // to production so there should be no chronological `PostDraftId`s before this
    // time) and before the time 1 year from now. Any `draftId`s outside this range are
    // unlikely to have been generated by `generateChronologicalId()` and may instead
    // be completely random IDs generated by `generateId()`.
    //
    // `draftId`s need to be `ChronologicalId`s so we sort them in the database roughly
    // by creation time.
    const time = getChronologicalIdTime(draftId);
    if (!(1730312192598 < time && time < Date.now() + 1000 * 60 * 60 * 24 * 365)) {
        throw new InvalidArgumentError(
            "Draft `Id` time is suspicious, did you generate the `Id` with `generateId()` instead of `generateChronologicalId()`?",
        );
    }

    const url = new URL(request.url);
    const channelId = Schema.id<ChannelId>()
        .nullable()
        .deserialize(url.searchParams.get("channel"));

    const [draft, channelOverride] = await runAllPromises([
        getPostDraftIfExists(context, spaceId, context.actor.getAccountId(), draftId),
        channelId ? await getChannelPreview(context, channelId) : null,
    ]);

    let content = draft?.content;

    // If there is no draft content, then check the `share` search parameter and use it
    // to compute initial content that includes the shared `FileEntityId`.
    if (!content) {
        const shareSearchParamString = url.searchParams.get("share");

        if (!shareSearchParamString) {
            content = emptyPostContentWithReferences;
        } else {
            const fileEntityId = FileEntityIdSchema.deserialize(shareSearchParamString);

            const doc = assertPostContent(
                PostContentProsemirrorSchema.node("doc", null, [
                    PostContentProsemirrorSchema.node("paragraph", null, []),
                    PostContentProsemirrorSchema.node("fileRow", null, [
                        PostContentProsemirrorSchema.node("file", {fileId: fileEntityId}),
                    ]),
                ]),
            );

            content = {
                doc,
                references: await getContentReferencesForNode(
                    context,
                    spaceId,
                    FilePostAuthorizer.bind({
                        type: "PostDraft",
                        spaceId,
                        accountId: context.actor.getAccountId(),
                        draftId,
                    }),
                    doc,
                ),
            };
        }
    }

    return jsonWithSchema(LoaderSchema, {
        draftId,
        channel: channelOverride ?? draft?.channel ?? null,
        content,
    });
}

// We don't need to reload when certain search params change.
export const shouldRevalidate: ShouldRevalidateFunction = ({
    currentUrl: immutableCurrentUrl,
    nextUrl: immutableNextUrl,
}) => {
    const currentUrl = new URL(immutableCurrentUrl);
    const nextUrl = new URL(immutableNextUrl);

    // Used to initially focus the chat:
    nextUrl.searchParams.delete("focus");
    currentUrl.searchParams.delete("focus");

    return nextUrl.toString() !== currentUrl.toString();
};

export default function PostCreateRoute() {
    const [searchParams, setSearchParams] = useSearchParams();
    const {
        draftId,
        channel: initialChannel,
        content: initialContent,
    } = useLoaderDataWithSchema(LoaderSchema);

    const shouldReturnBack = searchParams.get("return") === "back";

    const focusSearchParam = searchParams.get("focus");
    const [initiallyFocus] = useState(
        focusSearchParam === "content"
            ? ("ContentEditor" as const)
            : focusSearchParam === "channel"
              ? ("ChannelSelector" as const)
              : null,
    );

    useEffect(() => {
        if (searchParams.has("focus")) {
            const newSearchParams = new URLSearchParams(searchParams);
            newSearchParams.delete("focus");
            setSearchParams(newSearchParams, {replace: true});
        }
    }, [searchParams, setSearchParams]);

    return (
        <PostCreator
            draftId={draftId}
            initialChannel={initialChannel}
            initialContent={initialContent}
            shouldReturnBack={shouldReturnBack}
            initiallyFocus={initiallyFocus}
        />
    );
}
