import {appSitemapEntries} from "~/app/sitemap/app_sitemap_entries.js";
import {loadGeneratedDocumentationSitemapEntries} from "~/app/sitemap/load_generated_documentation_sitemap_entries.js";

export type SitemapEntry = {
    pathname: string;
    lastModified: string | null;
    imageUrls: Array<string>;
};

/** Canonical origin used for every production sitemap URL. */
export const alpineSitemapOrigin = "https://alpine.inc";

/** Repository-only marker added to the committed sitemap artifact. */
export const alpineSitemapGeneratedComment = "<!-- @generated by //app/sitemap:write_sitemap -->";

/** Build Alpine's sitemap from app paths and enabled generated content. */
export async function buildSitemap(): Promise<string> {
    // TODO(#public-api): Enable documentation and blog entries once those surfaces are
    // ready to be indexed.
    const isDocumentationSitemapEnabled = false;
    const documentationSitemapEntries = isDocumentationSitemapEnabled
        ? await loadGeneratedDocumentationSitemapEntries()
        : [];

    return serializeSitemap({
        origin: alpineSitemapOrigin,
        entries: [...appSitemapEntries, ...documentationSitemapEntries],
    });
}

/** Serialize canonical URLs using the standard sitemap protocol. */
export function serializeSitemap({
    origin,
    entries,
}: {
    origin: string;
    entries: Array<SitemapEntry>;
}): string {
    // Declare the image extension only when an entry uses it, keeping the plain-URL
    // sitemap valid without an unused namespace.
    const hasImages = entries.some(entry => entry.imageUrls.length > 0);
    const imageNamespace = hasImages
        ? ' xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"'
        : "";
    const urls = entries
        .map(entry => {
            const location = escapeSitemapXml(new URL(entry.pathname, origin).href);
            const lastModified =
                entry.lastModified === null
                    ? ""
                    : `\n    <lastmod>${escapeSitemapXml(entry.lastModified)}</lastmod>`;
            const images = entry.imageUrls
                .map(
                    imageUrl =>
                        `\n    <image:image><image:loc>${escapeSitemapXml(
                            new URL(imageUrl, origin).href,
                        )}</image:loc></image:image>`,
                )
                .join("");
            return `  <url>\n    <loc>${location}</loc>${lastModified}${images}\n  </url>`;
        })
        .join("\n");
    const urlSetBody = urls.length === 0 ? "" : `\n${urls}`;

    return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"${imageNamespace}>${urlSetBody}\n</urlset>\n`;
}

/** Escape text for safe inclusion in XML element content. */
function escapeSitemapXml(value: string): string {
    /* eslint-disable cyberworlds/string-quotes */
    return value
        .replaceAll("&", "&amp;")
        .replaceAll('"', "&quot;")
        .replaceAll("'", "&apos;")
        .replaceAll("<", "&lt;")
        .replaceAll(">", "&gt;");
    /* eslint-enable cyberworlds/string-quotes */
}
