// @generated by //shared/design:write_font_metrics

export const interFontAscender: number = 1984;
export const interFontDescender: number = 494;
export const interFontUnitsPerEm: number = 2048;
export const interFontXHeight: number = 1118;
export const interFontCapHeight: number = 1490;

export const commitMonoFontAscender: number = 958;
export const commitMonoFontDescender: number = 239;
export const commitMonoFontUnitsPerEm: number = 1000;
export const commitMonoFontXHeight: number = 540;
export const commitMonoFontCapHeight: number = 700;

export const commitMonoFontSizeAdjust: number = 1.0109230324074074;
