load("//admin/typescript:typescript.bzl", "ts_project")

ts_project(
    name = "test_helpers",
    visibility = ["//server:__subpackages__"],
    deps = [
        "//server/spaces",
        "//server/spaces/test_helpers",
        "//shared/access",
        "//shared/context",
        "//shared/helpers",
        "//shared/id",
    ],
)
