load("//admin/typescript:typescript.bzl", "ts_project")

ts_project(
    name = "protocol",
    visibility = ["//visibility:public"],
    deps = [
        "//shared/accounts",
        "//shared/avatar",
        "//shared/bots",
        "//shared/error",
        "//shared/files",
        "//shared/id",
        "//shared/schema",
        "//shared/spaces",
    ],
)
