import {CanUseTool, PermissionResult} from "@anthropic-ai/claude-agent-sdk";
import {buildClaudeAgentApprovalDecisionOptions} from "~/server/agents/bots_v2/sandbox/build_claude_agent_approval_decision_options.js";
import {ClaudeAgentApprovalRequest} from "~/server/agents/bots_v2/sandbox/claude_agent_approvals_state.js";
import {ClaudeAgentStateStore} from "~/server/agents/bots_v2/sandbox/claude_agent_state_store.js";
import {
    ClaudeAgentGatedToolName,
    getClaudeAgentGatedToolScope,
    isClaudeAgentGatedToolName,
    isClaudeAgentWebToolName,
} from "~/server/agents/bots_v2/sandbox/claude_agent_tool_names.js";
import {getClaudeAgentApprovalSummaryContent} from "~/server/agents/bots_v2/sandbox/get_claude_agent_approval_summary_content.js";
import {ClaudeAgentWebApprovalDecision} from "~/server/agents/bots_v2/sandbox/merge_claude_agent_approval_decisions.js";
import {AgentWebSessionStorage} from "~/server/agents/web/agent_web_session_storage.open_source.js";
import {exhaustive} from "~/shared/helpers/control/exhaustive.open_source.js";
import {isDeepEqualForUnknownValues} from "~/shared/helpers/control/is_deep_equal.open_source.js";

/**
 * Session-local approvals bookkeeping shared between the `canUseTool` gate, the
 * event loop, and the end-of-turn approvals card push in `run_claude_agent.ts`.
 */
export type ClaudeAgentApprovalsRuntime = {
    /**
     * Decided web tool (`WebFetch`/`WebSearch`) approvals from the batch we resumed
     * for. On resume the model sees dangling tool calls for pending web tool calls
     * (its `tool_use` was left dangling by the approval surgery) and re-issues those
     * calls by creating a new `tool_use` message with (hopefully) the same input. The
     * gate matches the re-issued call to its decision and allows the approved input /
     * denies a rejected one.
     */
    readonly webDecisions: Array<ClaudeAgentWebApprovalDecision>;

    /**
     * Actions the user rejected in the batch we resumed for, as `(toolName, input)`
     * pairs. On resume the gate denies an exact re-issue of any of these outright —
     * without parking a fresh card — so the user isn't re-asked to approve something
     * they just declined.
     *
     * We do also write a rejection into the transcript during the surgery ("The user
     * rejected this action. Do not retry it."), but that alone isn't enough, because
     * it's attached to the _original_ `tool_use_id`. A model that re-plans doesn't
     * "retry" that call, it issues a brand new one with a fresh id — which the gate
     * reads as a novel request and parks into another card. We watched exactly that: a
     * rejected `create` came back as a second approval card because an approved web
     * search re-drove alongside it and rewound the plan. So the transcript message is
     * the hint, and this list is the enforcement.
     *
     * Seeded by `run_claude_agent.ts`; cleared when a new message supersedes the
     * batch.
     */
    rejectedRequests: Array<{
        readonly toolName: ClaudeAgentGatedToolName;
        readonly input: unknown;
    }>;

    /**
     * Approval requests parked during the current turn. Pushed as an approvals stream
     * part when the turn ends, or replaced with a fresh array when a new message
     * supersedes the turn before the card was posted.
     */
    newRequests: Array<ClaudeAgentApprovalRequest>;
};

/**
 * The production approval gate, implemented as the SDK's `canUseTool` callback. It
 * runs before every tool call the runtime doesn't auto-allow (i.e. every gated
 * tool — the read-only Alpine tools are in `allowedTools` and never reach here):
 *
 * 1. An ungated tool (shouldn't reach here) is allowed.
 * 2. A gated tool with an unexpired `ApprovedForSession` scope grant is allowed.
 * 3. On a resumed turn:
 *     - approved _web_ tool calls are re-generated by the model (we erase the tool
 *       output from the transcript, so the model thinks there's something wrong
 *       and re-issues the tool call). We approve these re-issued calls if they
 *       exactly match a decided approval.
 *     - _Alpine write_ that were approved in the turn never hit this code. We run
 *       the tools manually on approval event receipt and then inject the results
 *       into the transcript before we officially resume (see
 *       `resolve_claude_agent_approval_decisions.ts`).
 * 4. A call that exactly re-issues something the user rejected in the resumed
 *    batch is denied outright (never parked), so the user isn't re-asked about an
 *    action they already declined. See the sticky-rejection note in the body.
 * 5. A stale-read `update`/`delete` is denied with a "read it first" message. This
 *    is an ordinary deny (no interrupt): the model keeps going and re-reads.
 * 6. Anything else needs a fresh approval, so we **park the turn**: record the
 *    request and, once the wave of parallel calls settles, interrupt the turn. The
 *    card is posted when the turn ends (`run_claude_agent.ts`). The agent resumes
 *    once the user decides.
 *
 * ## Why parking hangs the call instead of denying it
 *
 * The obvious way to stop a gated tool is to deny it. But a denial hands the model
 * a `tool_result` it then _reacts to_ — it narrates something like "I'll wait for
 * your approval" and burns a turn saying so, which leaks our internal plumbing to
 * the user. So instead we return a promise we never resolve, and interrupt the
 * turn out from under it.
 *
 * The call still ends up with a `tool_result` — the SDK writes its own aborted,
 * `is_error: true` one — so the transcript is never left holding a bare
 * `tool_use`. What the model never gets is the chance to _react_ to it, because
 * the turn is already aborted. Nothing is generated after the tool call, so the
 * user sees only what streamed before it, followed by the approval card. That
 * aborted result is exactly what the approval surgery rewrites on resume (see
 * `claude_agent_approval_transcript_surgery.ts`).
 *
 * Hanging on its own isn't enough, either — without the interrupt the SDK resolves
 * the call itself and the model reacts anyway.
 *
 * ## End-user behavior: parallel vs. sequential gated calls
 *
 * The distinction matters because a turn can request work in two shapes.
 *
 * **Parallel (one wave).** The model emits several gated calls at once — multiple
 * `tool_use` blocks in a single assistant message (or a rapid burst). The SDK
 * fires `canUseTool` for all of them concurrently; each hangs and arms the
 * debounce. When the wave settles we interrupt **once**. The user sees a single
 * card listing every gated action in the wave, and deciding on all cards resumes
 * the agent.
 *
 * **Sequential (result-dependent steps).** The model calls one gated tool, intends
 * to wait for its result, then call the next. We park on the _first_ call, so the
 * model never gets that result and never emits the later calls — only the first
 * appears on the card. After the user decides, the agent resumes and re-derives
 * whatever work still remains, requesting approval again for the next step. So in
 * other words, result-dependent steps are approved one at a time, each on its own
 * card, which mirrors how the model reasoned about them.
 */
export function createClaudeAgentCanUseTool({
    stateStore,
    approvalsRuntime,
    storage,
    interruptTurn,
}: {
    stateStore: ClaudeAgentStateStore;
    approvalsRuntime: ClaudeAgentApprovalsRuntime;
    storage: AgentWebSessionStorage;
    /**
     * Asks for the running turn to be interrupted so the parked call (and any parallel
     * siblings) can be turned into an approvals card. Called once per parked call —
     * the SDK fires `canUseTool` concurrently across a parallel batch — so the
     * implementation coalesces a burst into a single interrupt. Wired to the `query()`
     * handle in `run_claude_agent.ts`.
     */
    interruptTurn: () => void;
}): CanUseTool {
    return async (toolName, input, {signal, toolUseID}): Promise<PermissionResult> => {
        if (!isClaudeAgentGatedToolName(toolName)) {
            return {behavior: "allow"};
        }

        // TODO(#agent-web-deletion): Prior to approvals, we returned an UnimplementedError
        // when an agent tried to use the `delete` tool. We shouldn't ask for approval to
        // delete a piece of Alpine content only to reject the call when an actor approves
        // it – that's silly.
        if (toolName === "mcp__alpine__delete") {
            return {
                behavior: "deny",
                message: `The \`delete\` tool hasn\u2019t been implemented yet. Before allowing bots to delete stuff from Alpine, the Alpine team wants to build a trash feature so humans can recover anything that was accidentally deleted. Tell your human they need to manually delete things from Alpine, for now. For more information, contact [support@alpine.inc](mailto:support@alpine.inc).`,
            };
        }

        // NOTE(ifitzsimmons, 2026-08-14): This is an attempt at "sticky rejections". Deny
        // an exact re-issue of anything the user rejected so the user isn't asked twice
        // about the same declined action.
        //
        // When a batch mixes an APPROVED web tool with a REJECTED write, resolving the web
        // tool leaves its call dangling so the CLI re-drives it on resume. That re-drive
        // effectively rewinds the model to before the tool calls, so it re-plans the task
        // and re-emits the write the user just rejected with a fresh tool_use_id, so the
        // injected "you rejected this" result (which sits on the ORIGINAL call) doesn't
        // stop it. Without this guard the gate would park the re-emit into a brand-new
        // approval card for something the user already declined.
        //
        // Example:
        //
        // 1. approval request: WebSearch("nyc weather") + create(doc "Why the sky is
        //    blue")
        // 2. decision receipt: approve WebSearch reject create
        // 3. resume: We truncate the transcript and leave the dangling WebSearch call with
        //    the denied Write call. The model keeps going and re-emits identical calls for
        //    WebSearch("nyc weather") and create(doc "Why the sky is blue"). CanUseTool
        //    approves the web search call since there's an approved WebSearch call in the
        //    batch with the exact input. The model then asks for approval for the create
        //    call, but with this guard the re-emit is denied here instead, and the model
        //    moves on.
        //
        // This runs BEFORE the scope grant below, which is important!! Picture a card with
        // `WebFetch(evil.com)` and `WebSearch("weather")`: the user rejects the fetch and
        // grants "allow all web access" on the search. Both decisions land in the same
        // batch, so the grant is written to `allowedScopes.Web` and the fetch goes into
        // `rejectedRequests`. If the scope check ran first it would allow the re-issued
        // fetch to evil.com on the strength of a grant the user made about a different
        // call An action someone declined outright is more specific than a blanket grant,
        // so it wins.
        const isRejectedRequest = approvalsRuntime.rejectedRequests.some(
            rejected =>
                rejected.toolName === toolName &&
                isDeepEqualForUnknownValues(rejected.input, input),
        );

        if (isRejectedRequest) {
            return {
                behavior: "deny",
                message:
                    "You already requested this and the user rejected it. Do not attempt this action again; reply to the user directly without it.",
            };
        }

        const scope = getClaudeAgentGatedToolScope(toolName);
        const scopeGrant = stateStore.get().approvals.allowedScopes[scope];

        if (
            scopeGrant !== undefined &&
            // Clock should be the close enough, since we generated the scope grant on this
            // server
            (scopeGrant.expiresTime === null || Date.parse(scopeGrant.expiresTime) > Date.now())
        ) {
            // We should only ever hit this code in two cases:
            //
            // 1. An actor approved this scope in a previous turn.
            // 2. It's a **Web** scope and the actor approved it in **this turn**. Same-turn
            //    "Write" approvals never make it here: they are run outside of the agent loop
            //    and manually added to the transcript.
            return {behavior: "allow"};
        }

        // NOTE(ifitzsimmons, 2026-08-14): There's no stable ID linking a re-driven web
        // call back to its decision — the SDK mints a fresh `tool_use_id` for every call
        // and the built-in web tools' schemas have no field of ours to carry one. So Match
        // only the exact input that was approved. A new or changed request must fall
        // through and request its own approval rather than consuming a decision for a
        // different call and associating that result with the wrong tool use.
        let decision: ClaudeAgentWebApprovalDecision | null = null;

        if (isClaudeAgentWebToolName(toolName)) {
            const decisionIndex = approvalsRuntime.webDecisions.findIndex(
                candidate =>
                    candidate.approval.toolName === toolName &&
                    isDeepEqualForUnknownValues(candidate.approval.input, input),
            );

            if (decisionIndex !== -1) {
                decision = approvalsRuntime.webDecisions.splice(decisionIndex, 1)[0] ?? null;
            }
        }

        if (decision !== null) {
            switch (decision.value.type) {
                case "Approved":
                case "ApprovedForSession":
                    // A decision is only matched when the re-issued input is deeply equal to the
                    // approved one. A changed call should fall through and ask for its own approval.
                    return {behavior: "allow"};
                case "Rejected":
                    return {
                        behavior: "deny",
                        message: "The user rejected this action. Do not retry it.",
                    };
                default:
                    throw exhaustive(decision.value);
            }
        }

        // NOTE(ifitzsimmons, 2026-08-14): NOTHING BELOW THIS POINT SHOULD BE APPROVED. At
        // this point, we know that the tool is still gated.

        const approvalSummaryResult = await getClaudeAgentApprovalSummaryContent(storage, {
            toolName,
            input,
        });

        if (!approvalSummaryResult.ok) {
            return {
                behavior: "deny",
                message:
                    "This tool can only be called with the path of a page you\u2019ve read recently. Call the `read` tool with this path first, then try this tool again.",
            };
        }

        // A model retrying the same call within a turn mints a new `tool_use_id` each
        // time, so requests are deduplicated by their input — one card for the action
        // rather than one per attempt. Parallel calls with distinct inputs each get their
        // own entry (and their own card).
        //
        // The duplicate's id still has to be recorded. The SDK writes an aborted
        // `tool_result` for every `tool_use` block it parked, so an id we drop here is one
        // the resume surgery never resolves, leaving the model a stale "the user doesn't
        // want to proceed with this tool use" for something the user approved.
        const alreadyRequestedIndex = approvalsRuntime.newRequests.findIndex(
            request =>
                request.toolName === toolName && isDeepEqualForUnknownValues(request.input, input),
        );

        const alreadyRequested = approvalsRuntime.newRequests[alreadyRequestedIndex];

        if (alreadyRequested !== undefined) {
            approvalsRuntime.newRequests[alreadyRequestedIndex] = {
                ...alreadyRequested,
                toolUseIds: [...alreadyRequested.toolUseIds, toolUseID],
            };
        } else {
            approvalsRuntime.newRequests.push({
                toolUseIds: [toolUseID],
                toolName,
                scope,
                input,
                summaryContent: approvalSummaryResult.summaryContent,
                decisionOptions: buildClaudeAgentApprovalDecisionOptions(scope),
            });
        }

        // Ask for the turn to be interrupted, then hang until it is. We never resolve on
        // our own — the abort signal fires when the interrupt lands, and once every hung
        // call resolves the turn ends and the card is posted. The returned value is moot
        // (the abort supersedes it with the SDK's own aborted `tool_result`), but we
        // return a deny for type-correctness and in case a path exists where the abort
        // doesn't preempt it.
        interruptTurn();

        // NOTE(ifitzsimmons, 2026-08-13): I tried just returning a never promise but the
        // agent still writes items to the session in a weird order, and rejects the tool
        // anyway.
        //
        // ```
        // {
        //   "message": {
        //     "role": "user",
        //     "content": [
        //       {
        //         "type": "tool_result",
        //         "content": "Tool permission request failed: AbortError: Tool permission stream closed before response received",
        //         "is_error": true,
        //         "tool_use_id": "<id>"
        //       }
        //     ]
        //   }
        // }
        // ```
        //
        // So we return a promise that resolves with a deny message when the abort signal
        // is received. We get a nicer error message than the one the SDK returns by
        // default.
        //
        // ```
        // {
        //   "message": {
        //       "role": "user",
        //       "content": [
        //         {
        //           "type": "tool_result",
        //           "content": "The user doesn't want to proceed with this tool use. The tool use was rejected (eg. if it was a file edit, the new_string was NOT written to the file). STOP what you are doing and wait for the user to tell you how to proceed.",
        //           "is_error": true,
        //           "tool_use_id": "<id>"
        //         }
        //       ]
        //  }
        // ```
        return await new Promise<PermissionResult>(resolve => {
            signal.addEventListener("abort", () =>
                resolve({
                    behavior: "deny",
                    message: "This action is awaiting the user\u2019s approval.",
                }),
            );
        });
    };
}
