load("//admin/typescript:typescript.bzl", "ts_project")

ts_project(
    name = "documents",
    visibility = ["//visibility:public"],
    deps = [
        "//shared/access",
        "//shared/access/model",
        "//shared/accounts",
        "//shared/content",
        "//shared/error",
        "//shared/files",
        "//shared/helpers",
        "//shared/id",
        "//shared/messaging",
        "//shared/schema",
        "//shared/sites",
        "//shared/spell_check",
        "//shared/web_socket",
    ],
)
