load("//admin/typescript:typescript.bzl", "ts_project")

ts_project(
    name = "lezer",
    visibility = ["//visibility:public"],
    deps = [
        "//:node_modules/@lezer/highlight",
        "//shared/error",
        "//shared/helpers",
    ],
)
