load("//admin/typescript:typescript.bzl", "ts_project")

ts_project(
    name = "blob_factory",
    visibility = [
        "//app:__subpackages__",
        "//client:__subpackages__",
    ],
    deps = [
        "//:node_modules/@types/color",
        "//:node_modules/@types/d3-interpolate",
        "//:node_modules/@types/react",
        "//:node_modules/color",
        "//:node_modules/d3-interpolate",
        "//:node_modules/phosphor-react",
        "//:node_modules/react",
        "//client/content",
        "//client/design",
        "//client/dev",
        "//client/helpers",
        "//client/styles",
        "//shared/design",
        "//shared/documents",
        "//shared/error",
        "//shared/helpers",
        "//shared/id",
    ],
)
