name = "worker"
compatibility_date = "2022-10-21"
main = "./bundled/worker.js"

[durable_objects]
bindings = [
    { name = "DocumentCollaborationDurableObject", class_name = "DocumentCollaborationDurableObject" }
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["DocumentCollaborationDurableObject"]
