import fs from "fs-extra";
import {extname} from "path";
// @ts-expect-error: After upgrading Prettier, we need to directly import
// `prettier/index.mjs` to make sure we don't get the standalone build.
// However, there's no blessed way from Prettier to import the full version
// with types.
import * as prettier from "prettier/index.mjs";
import Yaml from "yaml";
import {runAllPromises} from "~/shared/helpers/async/run_all_promises.js";
import {escapeRegExp} from "~/shared/helpers/string/escape_reg_exp.js";

async function main() {
    await runAllPromises(
        process.argv.slice(2).map(async templatePath => {
            const templateJsonContents = JSON.parse(await fs.readFile(templatePath, "utf8"));

            const templateYamlContents = new Yaml.Document();
            templateYamlContents.contents = templateJsonContents;

            const unformattedTemplateYamlString = templateYamlContents.toString({
                lineWidth: 100,
                indent: 4,
            });

            let templateYamlString = await prettier.format(unformattedTemplateYamlString, {
                parser: "yaml",
                printWidth: 100,
                tabWidth: 4,
            });

            // The container hash added to this string is different on MacOS compared to our
            // Linux CI GitHub runner. So replace with a placeholder tag, `latest`.
            templateYamlString = templateYamlString
                .replaceAll(
                    new RegExp(
                        `(${escapeRegExp(
                            // eslint-disable-next-line no-template-curly-in-string
                            "${AWS::AccountId}.dkr.ecr.us-east-1.${AWS::URLSuffix}/cdk-hnb659fds-container-assets-${AWS::AccountId}-us-east-1:",
                        )})[0-9a-fA-F]+`,
                        "g",
                    ),
                    "$1latest",
                )
                .replaceAll(
                    // i.e. separated on multiple lines.
                    //
                    // - Fn::Sub: cdk-hnb659fds-container-assets-${AWS::AccountId}-us-east-1
                    // - :<hash>
                    new RegExp(
                        `(${escapeRegExp(
                            // eslint-disable-next-line no-template-curly-in-string
                            "Fn::Sub: cdk-hnb659fds-container-assets-${AWS::AccountId}-us-east-1",
                        )}\\n\\s+${escapeRegExp("- :")})[0-9a-fA-F]+`,
                        "g",
                    ),
                    "$1latest",
                )
                .replaceAll(/([A-Za-z]+FunctionCurrentVersion)[0-9a-fA-F]+/g, "$1Latest")
                .replace(
                    /^ {12}Analytics: v2:deflate64:.*/m,
                    "            # Removed `Analytics` property",
                );

            await fs.writeFile(
                `${templatePath.slice(0, -extname(templatePath).length)}.yaml`,
                `# @generated by //admin/aws:write_aws_app_templates\n\n${templateYamlString}`,
            );
        }),
    );
}

main().then(
    () => {
        process.exitCode = 0;
    },
    error => {
        // eslint-disable-next-line no-console
        console.error(error);
        process.exitCode = 1;
    },
);
