load("//admin/typescript:typescript.bzl", "ts_project")

ts_project(
    name = "icons",
    visibility = ["//visibility:public"],
    deps = [
        "//:node_modules/@types/react",
        "//:node_modules/phosphor-react",
        "//:node_modules/react",
        "//shared/design",
        "//shared/helpers",
        "//shared/styles",
    ],
)
