load("//admin/typescript:typescript.bzl", "ts_project")

ts_project(
    name = "helpers",
    visibility = [
        "//app:__subpackages__",
        "//client:__subpackages__",
    ],
    deps = [
        "//:node_modules/@internationalized/date",
        "//:node_modules/@react-aria/ssr",
        "//:node_modules/@react-types/shared",
        "//:node_modules/@types/color",
        "//:node_modules/@types/dedent",
        "//:node_modules/@types/jest",
        "//:node_modules/@types/react",
        "//:node_modules/@types/react-dom",
        "//:node_modules/@types/scheduler",
        "//:node_modules/classnames",
        "//:node_modules/color",
        "//:node_modules/dedent",
        "//:node_modules/functional-red-black-tree",
        "//:node_modules/react",
        "//:node_modules/react-dom",
        "//:node_modules/react-router-dom",
        "//:node_modules/scheduler",
        "//client/web/styles",
        "//shared/error",
        "//shared/helpers",
        "//shared/schema",
        "//shared/store",
    ],
)
