import {assert} from "~/shared/helpers/control/assert.js";
import {assertExists} from "~/shared/helpers/control/assert_exists.js";
import {assertId, decodeId, encodeId, idLength, isId} from "~/shared/id/id.js";

export type ApiKey = string & {readonly _ApiKey: never};

/**
 * Generated by making a 6 character word out of all the combinations of the
 * following:
 *
 * - "s", "S", "5"
 * - "e", "E", "3"
 * - "c", "C"
 * - "r", "R"
 * - "e", "E", "3"
 * - "t", "T", "7"
 *
 * This gives 324 possible prefixes when we only need 256. We remove strings that
 * obviously look like a word ("secret", "Secret", "SECRET"), remove strings that
 * have 3 or more numbers, and then removed some strings I just didn't vibe with.
 */
const apiKeyPrefixByByte: Array<string> = [
    "secRet",
    "secReT",
    "secRe7",
    "secREt",
    "secRET",
    "secRE7",
    "secR3t",
    "secR3T",
    "secR37",
    "seCret",
    "seCreT",
    "seCre7",
    "seCrEt",
    "seCrET",
    "seCrE7",
    "seCr3t",
    "seCr3T",
    "seCr37",
    "seCRet",
    "seCReT",
    "seCRe7",
    "seCREt",
    "seCRET",
    "seCRE7",
    "seCR3t",
    "seCR3T",
    "seCR37",
    "sEcret",
    "sEcreT",
    "sEcre7",
    "sEcrEt",
    "sEcrET",
    "sEcrE7",
    "sEcr3t",
    "sEcr3T",
    "sEcr37",
    "sEcRet",
    "sEcReT",
    "sEcRe7",
    "sEcREt",
    "sEcRET",
    "sEcRE7",
    "sEcR3t",
    "sEcR3T",
    "sEcR37",
    "sECret",
    "sECreT",
    "sECre7",
    "sECrEt",
    "sECrET",
    "sECrE7",
    "sECr3t",
    "sECr3T",
    "sECr37",
    "sECRet",
    "sECReT",
    "sECRe7",
    "sECREt",
    "sECRET",
    "sECRE7",
    "sECR3t",
    "sECR3T",
    "sECR37",
    "s3cret",
    "s3creT",
    "s3cre7",
    "s3crEt",
    "s3crET",
    "s3crE7",
    "s3cr3t",
    "s3cr3T",
    "s3cRet",
    "s3cReT",
    "s3cRe7",
    "s3cREt",
    "s3cRET",
    "s3cRE7",
    "s3cR3t",
    "s3cR3T",
    "s3Cret",
    "s3CreT",
    "s3Cre7",
    "s3CrEt",
    "s3CrET",
    "s3CrE7",
    "s3Cr3t",
    "s3Cr3T",
    "s3CRet",
    "s3CReT",
    "s3CRe7",
    "s3CREt",
    "s3CRET",
    "s3CRE7",
    "s3CR3t",
    "s3CR3T",
    "SecreT",
    "Secre7",
    "SecrEt",
    "SecrET",
    "SecrE7",
    "Secr3t",
    "Secr3T",
    "SecRet",
    "SecReT",
    "SecRe7",
    "SecREt",
    "SecRET",
    "SecRE7",
    "SecR3t",
    "SecR3T",
    "SeCret",
    "SeCreT",
    "SeCre7",
    "SeCrEt",
    "SeCrET",
    "SeCrE7",
    "SeCr3t",
    "SeCr3T",
    "SeCRet",
    "SeCReT",
    "SeCRe7",
    "SeCREt",
    "SeCRET",
    "SeCRE7",
    "SeCR3t",
    "SeCR3T",
    "SEcret",
    "SEcreT",
    "SEcre7",
    "SEcrEt",
    "SEcrET",
    "SEcrE7",
    "SEcr3t",
    "SEcr3T",
    "SEcRet",
    "SEcReT",
    "SEcRe7",
    "SEcREt",
    "SEcRET",
    "SEcRE7",
    "SEcR3t",
    "SEcR3T",
    "SEcR37",
    "SECret",
    "SECreT",
    "SECre7",
    "SECrEt",
    "SECrET",
    "SECrE7",
    "SECr3t",
    "SECr3T",
    "SECr37",
    "SECRet",
    "SECReT",
    "SECRe7",
    "SECREt",
    "SECRE7",
    "SECR3t",
    "SECR3T",
    "SECR37",
    "S3cret",
    "S3creT",
    "S3cre7",
    "S3crEt",
    "S3crET",
    "S3crE7",
    "S3cr3t",
    "S3cr3T",
    "S3cRet",
    "S3cReT",
    "S3cRe7",
    "S3cREt",
    "S3cRET",
    "S3cRE7",
    "S3cR3t",
    "S3cR3T",
    "S3Cret",
    "S3CreT",
    "S3Cre7",
    "S3CrEt",
    "S3CrET",
    "S3CrE7",
    "S3Cr3t",
    "S3Cr3T",
    "S3CRet",
    "S3CReT",
    "S3CRe7",
    "S3CREt",
    "S3CRET",
    "S3CRE7",
    "S3CR3t",
    "S3CR3T",
    "5ecret",
    "5ecreT",
    "5ecrEt",
    "5ecrET",
    "5ecr3t",
    "5ecr3T",
    "5ecRet",
    "5ecReT",
    "5ecREt",
    "5ecRET",
    "5ecR3t",
    "5ecR3T",
    "5eCret",
    "5eCreT",
    "5eCrEt",
    "5eCrET",
    "5eCr3t",
    "5eCr3T",
    "5eCRet",
    "5eCReT",
    "5eCREt",
    "5eCRET",
    "5eCR3t",
    "5eCR3T",
    "5Ecret",
    "5EcreT",
    "5EcrEt",
    "5EcrET",
    "5Ecr3t",
    "5Ecr3T",
    "5EcRet",
    "5EcReT",
    "5EcREt",
    "5EcRET",
    "5EcR3t",
    "5EcR3T",
    "5ECret",
    "5ECreT",
    "5ECrEt",
    "5ECrET",
    "5ECr3t",
    "5ECr3T",
    "5ECRet",
    "5ECReT",
    "5ECREt",
    "5ECRET",
    "5ECR3t",
    "5ECR3T",
    "53cret",
    "53creT",
    "53crEt",
    "53crET",
    "53cRet",
    "53cReT",
    "53cREt",
    "53cRET",
    "53Cret",
    "53CreT",
    "53CrEt",
    "53CrET",
    "53CRet",
    "53CReT",
    "53CREt",
    "53CRET",
];

// Make sure we have 256 API key prefixes. The first byte will always be
// represented by one of these prefixes.
assert(apiKeyPrefixByByte.length === 256);

const byteByApiPrefix = new Map<string, number>();

for (let byte = 0; byte < apiKeyPrefixByByte.length; byte++) {
    const prefix = apiKeyPrefixByByte[byte]!;
    assert(!byteByApiPrefix.has(prefix));
    byteByApiPrefix.set(prefix, byte);
}

/**
 * Generate a new random API key. An API key is 128 bits of randomness encoded in
 * 26 base-32 characters with a prefix that's some variant of the word "secret".
 *
 * We prepend a variant of the word "secret" as a cute way to remind developers
 * (and ourselves) that API keys are sensitive. They grant access to our system so
 * they should be carefully protected. A developer shouldn't hard code their API
 * key anywhere and we shouldn't log API keys. By using one of 256 variants of the
 * word "secret" it's impossible to remove the prefix from the API key. The API key
 * is incomplete without it.
 */
export function generateApiKey(): ApiKey {
    const bytes = new Uint8Array(16);
    crypto.getRandomValues(bytes);
    return encodeApiKeyWithMutation(bytes);
}

/**
 * Is this string an API key?
 */
export function isApiKey(string: string): string is ApiKey {
    if (string.length !== 31) return false;
    const [prefix = "", suffix = ""] = string.split("-", 2);
    if (!byteByApiPrefix.has(prefix)) return false;
    if (!isId(suffix + "00")) return false;
    return true;
}

/**
 * Assert the provided string is an API key.
 */
export function assertApiKey(string: string): ApiKey {
    assert(isApiKey(string));
    return string;
}

/**
 * Encode 128 bits into an API key string.
 */
export function encodeApiKey(bytes: Uint8Array): ApiKey {
    const newBytes = new Uint8Array(bytes.byteLength);
    newBytes.set(bytes);
    return encodeApiKeyWithMutation(newBytes);
}

function encodeApiKeyWithMutation(bytes: Uint8Array): ApiKey {
    const lastByte = bytes[bytes.length - 1]!;
    bytes[bytes.length - 1] = 0;

    const prefix = apiKeyPrefixByByte[lastByte]!;

    // The suffix always ends with 00 since we're taking the last byte and using it as
    // the prefix.
    let suffix: string = encodeId(bytes);
    assert(suffix.endsWith("00"));
    suffix = suffix.slice(0, -2);

    return `${prefix}-${suffix}` as ApiKey;
}

/**
 * Decode an API key into its underlying 128 bits.
 */
export function decodeApiKey(apiKey: ApiKey): Uint8Array {
    const [prefix = "", suffix = ""] = apiKey.split("-");
    assert(prefix.length === 6);
    assert(suffix.length === idLength - 2);

    const bytes = decodeId(assertId(suffix + "00"));
    bytes[bytes.length - 1] = assertExists(byteByApiPrefix.get(prefix));

    return bytes;
}
