import {InternalError} from "~/shared/error/error.open_source.js";
import {assert} from "~/shared/helpers/control/assert.open_source.js";
import {StableRandom} from "~/shared/helpers/number/stable_random.open_source.js";
import {Id, decodeId, encodeId} from "~/shared/id/id.open_source.js";

/**
 * Chronological `Id`s are lexicographically orderable by generation time and they
 * increase monotonically within the process where they're generated.
 *
 * To fill the 128 `Id` bits a `ChronologicalId` has:
 *
 * - 48 bits of time stamp
 * - 80 bits of randomness
 *
 * The 48 bit timestamp is Unix-time in milliseconds. 48 bits won't run out of
 * space until the year 10889 AD. The randomness makes sure even if two processes
 * generate a `ChronologicalId` with the same time (happens rarely) they'll still
 * be unique thanks to the randomness.
 *
 * `ChronologicalId`s are useful when you have time series data you'd like to sort
 * by the primary key. Generally prefer using `RandomId` unless you have a
 * compelling use case.
 *
 * `ChronologicalId`s have approximately the same format as [ULIDs][1]. Except
 * ULIDs are divided into time stamp part and random part by characters in its
 * string representation whereas `ChronologicalId`s are divided into time stamp
 * part and random part by bits in its binary representation.
 * `ChronologicalId.toUpperCase()` may give you a valid ULID but that's purely
 * coincidental and not a design goal for this type.
 *
 * [1]: https://github.com/ulid/spec
 */
export type ChronologicalId = Id & {readonly _ChronologicalId: never};

/**
 * The maximum timestamp that can fit in a `ChronologicalId`. Given we only allow
 * 48 bits for the timestamp in a `ChronologicalId`.
 */
export const maxChronologicalIdTime = 2 ** 48 - 1;

let lastChronologicalIdTime = 0;
let lastChronologicalIdBytes: Uint8Array | null = null;

/**
 * Generate a `ChronologicalId` with the current time. Generates monotonically
 * increasing `ChronologicalId`s within the same process.
 */
export function generateChronologicalId<Value extends ChronologicalId>(): Value {
    const time = Math.round(Date.now());

    if (time <= lastChronologicalIdTime) {
        const bytes = new Uint8Array(lastChronologicalIdBytes!);
        let wasIncremented = false;

        for (let i = bytes.length - 1; i >= 2; i--) {
            if (bytes[i]! < 255) {
                wasIncremented = true;
                bytes[i]!++;
                break;
            }
        }

        if (!wasIncremented) {
            throw new InternalError("Chronological ID overflow");
        }

        lastChronologicalIdBytes = bytes;

        return encodeId(bytes, 2);
    }

    const bytes = generateDecodedChronologicalIdWithTime(time);

    lastChronologicalIdTime = time;
    lastChronologicalIdBytes = bytes;

    return encodeId(bytes, 2);
}

/**
 * Generate a `ChronologicalId` with the provided time. Adds some random bytes to
 * the end of the `ChronologicalId`. Subsequent calls to this function will not
 * generate monotonically increasing `ChronologicalId`s. Generally, it's
 * recommended you use `generateChronologicalId()` instead of this function.
 */
export function generateChronologicalIdWithTime<Value extends ChronologicalId>(
    time: number,
): Value {
    const bytes = generateDecodedChronologicalIdWithTime(time);
    return encodeId(bytes, 2);
}

function generateDecodedChronologicalIdWithTime(time: number): Uint8Array {
    assert(Number.isInteger(time));
    assert(time >= 0);
    assert(time <= maxChronologicalIdTime);

    const bytes = new Uint8Array(18);

    const view = new DataView(bytes.buffer);
    view.setBigUint64(0, BigInt(time), false);

    const randomBytes = new Uint8Array(10);
    crypto.getRandomValues(randomBytes);
    bytes.set(randomBytes, 8);

    return bytes;
}

/**
 * Generate a new `ChronologicalId` using a `StableRandom` instance so you can
 * predictably produce the same `ChronologicalId` value. You must also provide the
 * `time` encoded into the `ChronologicalId`.
 *
 * Unsafe since if you actually need to guarantee uniqueness you need a
 * cryptographically secure source of randomness. `Id`s generated by `StableRandom`
 * are trivial to predict.
 */
export function unsafelyGenerateStableChronologicalId<Value extends ChronologicalId>(
    stableRandom: StableRandom,
    keyString: string,
    time: number,
): Value {
    const randomBytes = new Uint8Array(10);
    for (let i = 0; i < randomBytes.length; i++) {
        randomBytes[i] = stableRandom.randomInteger(keyString, i, 0, 255);
    }

    return unsafelyConstructChronologicalId(time, randomBytes);
}

/**
 * Construct a new `ChronologicalId` from the time and some random bytes.
 *
 * Unsafe since if you actually need to guarantee uniqueness you need a
 * cryptographically secure source of randomness. `Id`s generated by `StableRandom`
 * are trivial to predict.
 */
export function unsafelyConstructChronologicalId<Value extends ChronologicalId>(
    time: number,
    randomBytes: Uint8Array,
): Value {
    assert(Number.isInteger(time));
    assert(time >= 0);
    assert(time <= maxChronologicalIdTime);

    const bytes = new Uint8Array(18);

    const view = new DataView(bytes.buffer);
    view.setBigUint64(0, BigInt(time), false);

    bytes.set(randomBytes.slice(0, 10), 8);

    return encodeId(bytes, 2);
}

/**
 * Parse the timestamp from `ChronologicalId`.
 */
export function getChronologicalIdTime(id: ChronologicalId): number {
    return getDecodedChronologicalIdTime(decodeId(id));
}

/**
 * Parse the timestamp from a decoded `ChronologicalId`.
 */
export function getDecodedChronologicalIdTime(bytes: Uint8Array, byteOffset: number = 0): number {
    const view = new DataView(bytes.buffer, bytes.byteOffset + byteOffset);

    const time1 = BigInt(view.getUint16(0, false));
    const time2 = BigInt(view.getUint32(2, false));

    return Number((time1 << 32n) + time2);
}
