import {InvalidArgumentError} from "~/shared/error/error.open_source.js";
import {assert} from "~/shared/helpers/control/assert.open_source.js";
import {StableRandom} from "~/shared/helpers/number/stable_random.open_source.js";

/**
 * `Id`s in our system are 128 bits encoded in 26 base-32 characters.
 *
 * The 128 bits of an `Id` are usually random but may carry some other information.
 * For example, `ChronologicalId` includes the time it was generated so `Id`s can
 * be sorted by time. Unless you have a good reason, it's recommended to use
 * `RandomId`s which are generated completely randomly.
 *
 * They carry the same information as a [UUID][1] but with a more compact encoding.
 *
 * [1]: https://en.wikipedia.org/wiki/Universally_unique_identifier
 */
export type Id = string & {readonly _Id: never};

/**
 * An `Id` that is generated completely randomly. 128 bits of randomness.
 *
 * As opposed to `ChronologicalId` which has a time component in addition to a
 * random component. Random `Id`s are generally the preferred `Id` type. Only use
 * `ChronologicalId` if you have a specific use case where it's needed.
 */
export type RandomId = Id & {readonly _RandomId: never};

/**
 * [Crockford's Base32 alphabet][1].
 *
 * [1]: https://www.crockford.com/base32.html
 */
const alphabet = "0123456789abcdefghjkmnpqrstvwxyz";

let alphabetSet: Set<string>;
let alphabetReverseMap: Map<string, number>;

/**
 * The length of an `Id`.
 */
export const idLength = 26;

/**
 * The number of bytes in an `Id`'s binary representation.
 */
export const idByteLength = 16;

/**
 * The minimum `Id` string we can generate.
 */
const minId = "00000000000000000000000000" as Id;

/**
 * Gets the minimum `Id` string we can generate.
 *
 * Generic so it can be used with any type in `id_type.ts`.
 */
export function getMinId<Value extends Id>(): Value {
    return minId as Value;
}

/**
 * The maximum `Id` string we can generate. The 26 characters that make up an ID
 * can store 130 bits of information but we want to limit ourselves to 128 bits.
 * That way we can represent the `Id` as an integer.
 */
const maxId = "zzzzzzzzzzzzzzzzzzzzzzzzzw" as Id;

/**
 * Gets the maximum `Id` string we can generate.
 *
 * Generic so it can be used with any type in `id_type.ts`.
 */
export function getMaxId<Value extends Id>(): Value {
    return maxId as Value;
}

/**
 * Is the provided string a valid `Id`?
 */
export function isId<Value extends Id>(string: string): string is Value {
    if (string.length !== idLength) return false;

    // Lazily initialize the alphabet set.
    if (!alphabetSet) alphabetSet = new Set(alphabet);

    for (let index = 0; index < string.length; index++) {
        const char = string[index]!;
        if (!alphabetSet.has(char)) return false;
    }

    if (string > maxId) return false;

    return true;
}

/**
 * Asserts that the provided string is a valid `Id`.
 */
export function assertId<Value extends Id>(string: string): Value {
    assert(isId(string));
    return string as any;
}

/**
 * Generate a new random `Id` using a cryptographically secure source of
 * randomness.
 */
export function generateId<Value extends RandomId>(): Value {
    const bytes = new Uint8Array(16);
    crypto.getRandomValues(bytes);
    return encodeId(bytes);
}

/**
 * Generate a new random `Id` using a `StableRandom` instance so you can
 * predictably produce the same `Id` value.
 *
 * Unsafe since if you actually need to guarantee uniqueness you need a
 * cryptographically secure source of randomness. `Id`s generated by `StableRandom`
 * are trivial to predict.
 */
export function unsafelyGenerateStableId<Value extends RandomId>(
    stableRandom: StableRandom,
    keyString: string,
): Value {
    const bytes = new Uint8Array(16);

    for (let i = 0; i < bytes.length; i++) {
        bytes[i] = stableRandom.randomInteger(keyString, i, 0, 255);
    }

    return encodeId(bytes);
}

/**
 * Encodes 128 bits (16 bytes) into an `Id`.
 */
export function encodeId<Value extends Id>(bytes: Uint8Array, byteOffset: number = 0): Value {
    if (bytes.length - byteOffset < idByteLength)
        throw new InvalidArgumentError("Not enough bytes");

    let bits = 0;
    let value = 0;
    let id = "";

    for (let byteIndex = byteOffset; byteIndex < byteOffset + idByteLength; byteIndex++) {
        value = (value << 8) | bytes[byteIndex]!;
        bits += 8;

        while (bits >= 5) {
            id += alphabet[(value >>> (bits - 5)) & 31];
            bits -= 5;
        }
    }

    if (bits > 0) {
        id += alphabet[(value << (5 - bits)) & 31];
    }

    return id as Value;
}

/**
 * Decodes an `Id` into 128 bits (16 bytes).
 */
export function decodeId(id: Id): Uint8Array {
    const bytes = new Uint8Array(idByteLength);
    decodeIdInto(id, bytes);
    return bytes;
}

/**
 * Decodes an `Id` into 128 bits (16 bytes) by mutating an existing typed array.
 * Useful if you want to decode an `Id` into an existing buffer.
 */
export function decodeIdInto(id: Id, bytes: Uint8Array, byteOffset: number = 0): void {
    assert(bytes.length - byteOffset >= idByteLength);

    // Lazily initialize the alphabet reverse map.
    if (!alphabetReverseMap) {
        alphabetReverseMap = new Map();
        for (let i = 0; i < alphabet.length; i++) {
            alphabetReverseMap.set(alphabet[i]!, i);
        }
    }

    let idIndex = 0;
    let byteIndex = byteOffset;

    const iterations = (idLength >> 3) << 3;
    while (idIndex < iterations) {
        const v1 = alphabetReverseMap.get(id.charAt(idIndex++))!;
        const v2 = alphabetReverseMap.get(id.charAt(idIndex++))!;
        const v3 = alphabetReverseMap.get(id.charAt(idIndex++))!;
        const v4 = alphabetReverseMap.get(id.charAt(idIndex++))!;
        const v5 = alphabetReverseMap.get(id.charAt(idIndex++))!;
        const v6 = alphabetReverseMap.get(id.charAt(idIndex++))!;
        const v7 = alphabetReverseMap.get(id.charAt(idIndex++))!;
        const v8 = alphabetReverseMap.get(id.charAt(idIndex++))!;
        bytes[byteIndex++] = ((v1 << 3) | (v2 >>> 2)) & 255;
        bytes[byteIndex++] = ((v2 << 6) | (v3 << 1) | (v4 >>> 4)) & 255;
        bytes[byteIndex++] = ((v4 << 4) | (v5 >>> 1)) & 255;
        bytes[byteIndex++] = ((v5 << 7) | (v6 << 2) | (v7 >>> 3)) & 255;
        bytes[byteIndex++] = ((v7 << 5) | v8) & 255;
    }

    {
        const v1 = alphabetReverseMap.get(id.charAt(idIndex++))!;
        const v2 = alphabetReverseMap.get(id.charAt(idIndex++))!;
        bytes[byteIndex++] = ((v1 << 3) | (v2 >>> 2)) & 255;
    }
}
