// @generated by //server/api/specification:write_specification

import * as IdTypes from "~/shared/id/types/id_types.js";

export namespace ApiSpecification {
    export interface paths {
        readonly "/ping": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly get: {
                readonly parameters: {
                    readonly query?: never;
                    readonly header?: never;
                    readonly path?: never;
                    readonly cookie?: never;
                };
                readonly requestBody?: never;
                readonly responses: {
                    readonly 200: {
                        headers: {
                            readonly [name: string]: unknown;
                        };
                        content: {
                            readonly "application/json": {
                                /** @enum {boolean} */
                                readonly pong: true;
                            };
                        };
                    };
                    readonly default: components["responses"]["Error"];
                };
            };
            readonly put?: never;
            readonly post?: never;
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
        readonly "/hello/{name}": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly name: string;
                };
                readonly cookie?: never;
            };
            readonly get: {
                readonly parameters: {
                    readonly query?: never;
                    readonly header?: never;
                    readonly path: {
                        readonly name: string;
                    };
                    readonly cookie?: never;
                };
                readonly requestBody?: never;
                readonly responses: {
                    readonly 200: {
                        headers: {
                            readonly [name: string]: unknown;
                        };
                        content: {
                            readonly "application/json": {
                                readonly message: string;
                            };
                        };
                    };
                    readonly default: components["responses"]["Error"];
                };
            };
            readonly put?: never;
            readonly post?: never;
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
        readonly "/documents/{id}": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: components["schemas"]["DocumentId"];
                };
                readonly cookie?: never;
            };
            readonly get: {
                readonly parameters: {
                    readonly query?: never;
                    readonly header?: never;
                    readonly path: {
                        readonly id: components["schemas"]["DocumentId"];
                    };
                    readonly cookie?: never;
                };
                readonly requestBody?: never;
                readonly responses: {
                    readonly 200: {
                        headers: {
                            readonly [name: string]: unknown;
                        };
                        content: {
                            readonly "application/json": {
                                readonly title?: string;
                            };
                        };
                    };
                    readonly default: components["responses"]["Error"];
                };
            };
            readonly put?: never;
            readonly post?: never;
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
    }
    export type webhooks = Record<string, never>;
    export interface components {
        schemas: {
            readonly DocumentId: IdTypes.DocumentId;
        };
        responses: {
            readonly Error: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly error: {
                            /** @description A human-readable message providing more details about the error. */
                            readonly message: string;
                        };
                    };
                };
            };
        };
        parameters: never;
        requestBodies: never;
        headers: never;
        pathItems: never;
    }
    export type $defs = Record<string, never>;
    export type operations = Record<string, never>;
}
