// @generated by //server/api/specification:write_specification
/* eslint-disable @typescript-eslint/array-type */

import type {DateString} from "~/shared/helpers/date/date_string.js";
import type * as IdTypes from "~/shared/id/types/id_types.js";

export namespace ApiSpecification {
    export interface paths {
        readonly "/chats/{id}/messages/{index}": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: components["schemas"]["ChatId"];
                    readonly index: number;
                };
                readonly cookie?: never;
            };
            readonly get: {
                readonly parameters: {
                    readonly query?: never;
                    readonly header?: never;
                    readonly path: {
                        readonly id: components["schemas"]["ChatId"];
                        readonly index: number;
                    };
                    readonly cookie?: never;
                };
                readonly requestBody?: never;
                readonly responses: {
                    readonly 200: {
                        headers: {
                            readonly [name: string]: unknown;
                        };
                        content: {
                            readonly "application/json": components["schemas"]["Message"];
                        };
                    };
                    readonly default: components["responses"]["Error"];
                };
            };
            readonly put?: never;
            readonly post?: never;
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
        readonly "/documents/{id}/threads/{threadId}/messages/{index}": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: components["schemas"]["DocumentId"];
                    readonly threadId: components["schemas"]["DocumentThreadId"];
                    readonly index: number;
                };
                readonly cookie?: never;
            };
            readonly get: {
                readonly parameters: {
                    readonly query?: never;
                    readonly header?: never;
                    readonly path: {
                        readonly id: components["schemas"]["DocumentId"];
                        readonly threadId: components["schemas"]["DocumentThreadId"];
                        readonly index: number;
                    };
                    readonly cookie?: never;
                };
                readonly requestBody?: never;
                readonly responses: {
                    readonly 200: {
                        headers: {
                            readonly [name: string]: unknown;
                        };
                        content: {
                            readonly "application/json": components["schemas"]["Message"];
                        };
                    };
                    readonly default: components["responses"]["Error"];
                };
            };
            readonly put?: never;
            readonly post?: never;
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
        readonly "/posts/{id}/messages/{index}": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: components["schemas"]["PostId"];
                    readonly index: number;
                };
                readonly cookie?: never;
            };
            readonly get: {
                readonly parameters: {
                    readonly query?: never;
                    readonly header?: never;
                    readonly path: {
                        readonly id: components["schemas"]["PostId"];
                        readonly index: number;
                    };
                    readonly cookie?: never;
                };
                readonly requestBody?: never;
                readonly responses: {
                    readonly 200: {
                        headers: {
                            readonly [name: string]: unknown;
                        };
                        content: {
                            readonly "application/json": components["schemas"]["Message"];
                        };
                    };
                    readonly default: components["responses"]["Error"];
                };
            };
            readonly put?: never;
            readonly post?: never;
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
        readonly "/tasks/{id}/messages/{index}": {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: components["schemas"]["TaskId"];
                    readonly index: number;
                };
                readonly cookie?: never;
            };
            readonly get: {
                readonly parameters: {
                    readonly query?: never;
                    readonly header?: never;
                    readonly path: {
                        readonly id: components["schemas"]["TaskId"];
                        readonly index: number;
                    };
                    readonly cookie?: never;
                };
                readonly requestBody?: never;
                readonly responses: {
                    readonly 200: {
                        headers: {
                            readonly [name: string]: unknown;
                        };
                        content: {
                            readonly "application/json": components["schemas"]["Message"];
                        };
                    };
                    readonly default: components["responses"]["Error"];
                };
            };
            readonly put?: never;
            readonly post?: never;
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
    }
    export interface webhooks {
        readonly bot: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly get?: never;
            readonly put?: never;
            readonly post: {
                readonly parameters: {
                    readonly query?: never;
                    readonly header?: never;
                    readonly path?: never;
                    readonly cookie?: never;
                };
                readonly requestBody: {
                    readonly content: {
                        readonly "application/json": {
                            readonly spaceId: components["schemas"]["SpaceId"];
                            readonly accountId: components["schemas"]["AccountId"];
                            readonly accessToken: string;
                            readonly eventId: components["schemas"]["BotWebhookEventId"];
                            readonly event: components["schemas"]["BotWebhookEvent"];
                        };
                    };
                };
                readonly responses: {
                    /** @description Return a 200 status to indicate that the data was received successfully */
                    readonly 200: {
                        headers: {
                            readonly [name: string]: unknown;
                        };
                        content?: never;
                    };
                };
            };
            readonly delete?: never;
            readonly options?: never;
            readonly head?: never;
            readonly patch?: never;
            readonly trace?: never;
        };
    }
    export interface components {
        schemas: {
            readonly AccountId: IdTypes.AccountId;
            readonly BotWebhookEventId: IdTypes.BotWebhookEventId;
            readonly ChatId: IdTypes.ChatId;
            readonly DocumentId: IdTypes.DocumentId;
            readonly DocumentThreadId: IdTypes.DocumentCommentThreadId;
            readonly PostId: IdTypes.PostId;
            readonly SpaceId: IdTypes.SpaceId;
            readonly TaskId: IdTypes.TaskId;
            readonly AccountPath: `/accounts/${IdTypes.AccountId}`;
            readonly ChannelPath: `/channels/${IdTypes.ChannelId}`;
            readonly ChatPath: `/chats/${IdTypes.ChatId}`;
            readonly DocumentPath: `/documents/${IdTypes.DocumentId}`;
            readonly DocumentThreadPath: `/documents/${IdTypes.DocumentId}/threads/${IdTypes.DocumentCommentThreadId}`;
            readonly PostPath: `/posts/${IdTypes.PostId}`;
            readonly TaskPath: `/tasks/${IdTypes.TaskId}`;
            readonly TaskCollectionPath: `/task-collections/${IdTypes.TaskCollectionId}`;
            readonly MessageRoomPath:
                | components["schemas"]["ChatPath"]
                | components["schemas"]["DocumentThreadPath"]
                | components["schemas"]["PostPath"]
                | components["schemas"]["TaskPath"];
            readonly ContentMentionInlineElementTargetPath:
                | components["schemas"]["AccountPath"]
                | components["schemas"]["ChannelPath"]
                | components["schemas"]["DocumentPath"]
                | components["schemas"]["PostPath"]
                | components["schemas"]["TaskPath"]
                | components["schemas"]["TaskCollectionPath"];
            readonly Content: {
                readonly elements: readonly components["schemas"]["ContentBlockElement"][];
            };
            readonly ContentBlockElement:
                | components["schemas"]["ContentParagraphBlockElement"]
                | components["schemas"]["ContentUnorderedListBlockElement"]
                | components["schemas"]["ContentOrderedListBlockElement"]
                | components["schemas"]["ContentQuoteBlockElement"]
                | components["schemas"]["ContentTableBlockElement"]
                | components["schemas"]["ContentCodeBlockElement"];
            readonly ContentParagraphBlockElement: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Paragraph";
                readonly elements: readonly components["schemas"]["ContentInlineElement"][];
            };
            readonly ContentListBlockElement:
                | components["schemas"]["ContentUnorderedListBlockElement"]
                | components["schemas"]["ContentOrderedListBlockElement"];
            readonly ContentUnorderedListBlockElement: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "UnorderedList";
                readonly items: readonly components["schemas"]["ContentListBlockElementItem"][];
            };
            readonly ContentOrderedListBlockElement: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "OrderedList";
                readonly items: readonly components["schemas"]["ContentListBlockElementItem"][];
            };
            readonly ContentListBlockElementItem: {
                readonly elements: readonly components["schemas"]["ContentParagraphBlockElement"][];
                readonly nestedListElements?: readonly components["schemas"]["ContentListBlockElement"][];
            };
            readonly ContentQuoteBlockElement: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Quote";
                readonly elements: readonly components["schemas"]["ContentQuoteBlockElementBlockElement"][];
            };
            readonly ContentQuoteBlockElementBlockElement:
                | components["schemas"]["ContentParagraphBlockElement"]
                | components["schemas"]["ContentUnorderedListBlockElement"]
                | components["schemas"]["ContentOrderedListBlockElement"];
            readonly ContentTableBlockElement: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Table";
                readonly width: number;
                readonly hasHeaderRow?: boolean;
                readonly hasHeaderColumn?: boolean;
                readonly columns: readonly {
                    readonly width: number;
                }[];
                readonly rows: readonly components["schemas"]["ContentTableBlockElementRow"][];
            };
            readonly ContentTableBlockElementRow: {
                readonly cells: readonly components["schemas"]["ContentTableBlockElementCell"][];
            };
            readonly ContentTableBlockElementCell: {
                readonly elements: readonly components["schemas"]["ContentTableBlockElementCellBlockElement"][];
            };
            readonly ContentTableBlockElementCellBlockElement:
                | components["schemas"]["ContentParagraphBlockElement"]
                | components["schemas"]["ContentUnorderedListBlockElement"]
                | components["schemas"]["ContentOrderedListBlockElement"]
                | components["schemas"]["ContentQuoteBlockElement"]
                | components["schemas"]["ContentCodeBlockElement"];
            readonly ContentCodeBlockElement: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Code";
                /** @enum {string} */
                readonly language:
                    | "text"
                    | "javascript"
                    | "html"
                    | "css"
                    | "sql"
                    | "python"
                    | "typescript"
                    | "shell"
                    | "java"
                    | "json"
                    | "markdown"
                    | "csharp"
                    | "cpp"
                    | "c"
                    | "php"
                    | "go"
                    | "yaml"
                    | "powershell"
                    | "rust"
                    | "kotlin"
                    | "ruby"
                    | "lua"
                    | "xml"
                    | "dart"
                    | "swift"
                    | "assembly"
                    | "webassembly"
                    | "scala"
                    | "r"
                    | "elixir"
                    | "objectivec"
                    | "perl"
                    | "haskell"
                    | "solidity"
                    | "clojure"
                    | "erlang"
                    | "ocaml";
                readonly lines: readonly components["schemas"]["ContentCodeBlockElementLine"][];
            };
            readonly ContentCodeBlockElementLine: {
                readonly elements: readonly components["schemas"]["ContentCodeBlockElementTextInlineElement"][];
            };
            readonly ContentInlineElement:
                | components["schemas"]["ContentTextInlineElement"]
                | components["schemas"]["ContentBreakInlineElement"]
                | components["schemas"]["ContentMentionInlineElement"];
            readonly ContentTextInlineElement: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Text";
                readonly text: string;
                readonly marks?: readonly components["schemas"]["ContentInlineElementMark"][];
            };
            readonly ContentBreakInlineElement: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Break";
                readonly marks?: readonly components["schemas"]["ContentInlineElementMark"][];
            };
            readonly ContentMentionInlineElement: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Mention";
                readonly targetPath: components["schemas"]["ContentMentionInlineElementTargetPath"];
                readonly title?: string;
                readonly isAccountShortName?: boolean;
                readonly marks?: readonly components["schemas"]["ContentInlineElementMark"][];
            };
            readonly ContentInlineElementMark:
                | components["schemas"]["ContentInlineElementBoldMark"]
                | components["schemas"]["ContentInlineElementItalicMark"]
                | components["schemas"]["ContentInlineElementStrikeMark"]
                | components["schemas"]["ContentInlineElementLinkMark"]
                | components["schemas"]["ContentInlineElementCodeMark"];
            readonly ContentInlineElementBoldMark: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Bold";
            };
            readonly ContentInlineElementItalicMark: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Italic";
            };
            readonly ContentInlineElementStrikeMark: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Strike";
            };
            readonly ContentInlineElementLinkMark: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Link";
                readonly url: string;
            };
            readonly ContentInlineElementCodeMark: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Code";
            };
            readonly ContentCodeBlockElementTextInlineElement: {
                /** @constant */
                readonly type: "Text";
                readonly text: string;
                readonly marks?: readonly components["schemas"]["ContentCodeBlockElementTextInlineElementMark"][];
            };
            readonly ContentCodeBlockElementTextInlineElementMark:
                | components["schemas"]["ContentInlineElementBoldMark"]
                | components["schemas"]["ContentInlineElementItalicMark"]
                | components["schemas"]["ContentInlineElementStrikeMark"]
                | components["schemas"]["ContentInlineElementLinkMark"];
            readonly Message: {
                readonly roomPath: components["schemas"]["MessageRoomPath"];
                readonly index: number;
                /** Format: date-time */
                readonly createdTime: DateString;
                readonly payload: components["schemas"]["MessagePayload"];
            };
            readonly MessagePayload:
                | components["schemas"]["MessageContentPayload"]
                | components["schemas"]["MessageDeletedPayload"];
            readonly MessageContentPayload: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Content";
                readonly parent?: components["schemas"]["MessageContentPayloadMessageParent"];
                readonly content: components["schemas"]["Content"];
            };
            readonly MessageContentPayloadMessageParent: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Message";
                readonly index: number;
            };
            readonly MessageDeletedPayload: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "Deleted";
            };
            readonly BotWebhookEvent: components["schemas"]["BotWebhookNewMessageEvent"];
            readonly BotWebhookNewMessageEvent: {
                /**
                 * @description discriminator enum property added by openapi-typescript
                 * @enum {string}
                 */
                readonly type: "NewMessage";
                readonly roomPath: components["schemas"]["MessageRoomPath"];
                readonly index: number;
                readonly wasMentioned?: boolean;
            };
        };
        responses: {
            readonly Error: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly error: {
                            /** @description A human-readable message providing more details about the error. */
                            readonly message: string;
                        };
                    };
                };
            };
        };
        parameters: never;
        requestBodies: never;
        headers: never;
        pathItems: never;
    }
    export type $defs = Record<string, never>;
    export type operations = Record<string, never>;
}
