name: Deploy
on:
    workflow_dispatch:
        inputs:
            # Unfortunately we can only dispatch a workflow with a git branch or tag
            # ([commit sha's don't work][1]). So we dispatch with the `main` branch and
            # pass the specific commit as an input.
            #
            # [1]: https://github.com/orgs/community/discussions/75513
            commitSha:
                required: true
                type: string

concurrency: deploy

jobs:
    test:
        name: Deploy
        runs-on: [self-hosted, aws-deploy]
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
              with:
                  ref: ${{ inputs.commitSha }}

            # NOTE(imjoshin): There are differences in caching, fetching dependencies, and saving
            # (in fact, we don't save to the cache at all here) in production vs development.
            # We are explicitly NOT using init-bazel-cache to avoid any behavior from the shared
            # job impacting our production deploy.

            # We cache Bazel external repositories with [GitHub's cache action][1]. We
            # cache individual build rule results with [Bazel remote caching][2].
            #
            # The following restores the previously saved Bazel repository cache. The Bazel
            # repository's cache key includes a hash of all files that contribute to the
            # external repositories we download. All external repositories are defined in
            # `WORKSPACE` or a file referenced by `WORKSPACE` (e.g. `pnpm-lock.yaml` which
            # is used by the `npm_translate_lock()` call in `WORKSPACE`).
            #
            # We also include the Bazel binary installed by Bazelisk in this cache so we
            # include a hash of `.bazelversion`.
            #
            # [1]: https://github.com/actions/cache
            # [2]: https://bazel.build/remote/caching
            - id: cache
              name: Restore Bazel repositories cache
              uses: actions/cache/restore@v3
              with:
                  path: |
                      ~/.cache/bazelisk
                      ~/.cache/bazel
                  # IMPORTANT: Should have the same `hashFiles()` as `test.yaml`. We want to
                  # share our cache between the two workflows.
                  key: |
                      bazel-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('.bazelversion', 'WORKSPACE', 'pnpm-lock.yaml', 'requirements_lock.txt', 'admin/patches/bazel/*.patch', 'admin/bazel/third_party/*.bazel') }}
                  restore-keys: |
                      bazel-${{ runner.os }}-${{ runner.arch }}-

            # If we don't have an exact cache entry match then we need to fetch
            # repositories we'll need for our build. We also build `//:node_modules` which
            # will make sure all `package.json` dependencies are extracted, their lifecycle
            # methods have run, and they're in the right place in `bazel-bin`.
            #
            # From the [`actions/cache` documentation][1]:
            #
            # > Note: `cache-hit` will be set to `true` only when cache hit occurs for the
            # > exact `key` match. For a partial key match via `restore-keys` or a cache
            # > miss, it will be set to `false`.
            #
            # [1]: https://github.com/actions/cache/blob/main/restore/README.md
            - if: steps.cache.outputs.cache-hit != 'true'
              name: Fetch Bazel repositories
              shell: bash
              run: |
                  admin/bin/bazel --bazelrc=admin/bazel/aspect_bazelrc/ci.bazelrc fetch //server/deploy/script/... --config=github-runner --config=production --remote_cache=
                  admin/bin/bazel --bazelrc=admin/bazel/aspect_bazelrc/ci.bazelrc build //:node_modules --config=github-runner --config=production --remote_cache=

            # IMPORTANT: Never save fetched Bazel repositories in the deploy job! Because
            # we fetch a subset of external repositories during deploy
            # (`bazel fetch //server/deploy/script/...` vs `bazel fetch //...` in
            # `test.yaml`) so if a test CI job uses the deploy cache artifact it will fail
            # because external repositories like `opensearch_local` weren't fetched!

            # This starts the [Bazel remote cache][1] proxy server. For more information
            # see `test.yaml`.
            #
            # [1]: https://bazel.build/remote/caching
            - name: Start Bazel remote cache
              shell: bash
              run: |
                  admin/aws/internal/aws_github_runners_bazel_remote_cache.sh

            # We build `//server/deploy/script` in a separate step so our tracing code can
            # log a separate span for the time it takes to build containers.
            - name: Build artifacts
              shell: bash
              run: |
                  admin/bin/bazel --bazelrc=admin/bazel/aspect_bazelrc/ci.bazelrc build //server/deploy/script --config=github-runner --config=production --nofetch

            - name: Deploy
              shell: bash
              env:
                  BAZEL_BINDIR: .
              run: |
                  bazel-bin/server/deploy/script/script.sh \
                      --commitSha=${{ inputs.commitSha }} \
                      --workflowRunId=${{ github.run_id }} \
                      --workflowRunNumber=${{ github.run_number }} \
                      --workflowRunAttempt=${{ github.run_attempt }} \
                      --edgeServiceUrl=https://alpine.inc \
                      --resourceServiceUrl=https://resources.alpine.inc \
                      --honeycombApiKey=${{ secrets.DEPLOY_HONEYCOMB_API_KEY }} \
                      --tracerEventStreamName=tracer-events \
                      --cloudflareR2AccessKeyId=${{ secrets.DEPLOY_CLOUDFLARE_R2_ACCESS_KEY_ID }} \
                      --cloudflareR2SecretAccessKey=${{ secrets.DEPLOY_CLOUDFLARE_R2_SECRET_ACCESS_KEY }} \
                      --cloudflareWorkersToken=${{ secrets.DEPLOY_CLOUDFLARE_WORKERS_TOKEN }} \
                      "--cloudflareAccountId=$(node -e "process.stdout.write(JSON.parse(process.env.USER_DATA_EXTRA).cloudflareAccountId)")" \
                      "--jobQueueUrl=$(node -e "process.stdout.write(JSON.parse(process.env.USER_DATA_EXTRA).jobQueueUrl)")" \
                      "--fileProcessorJobQueueUrl=$(node -e "process.stdout.write(JSON.parse(process.env.USER_DATA_EXTRA).fileProcessorJobQueueUrl)")" \
                      "--fileProcessorHeavyJobQueueUrl=$(node -e "process.stdout.write(JSON.parse(process.env.USER_DATA_EXTRA).fileProcessorJobQueueUrl)")" \
                      "--fileProcessorLightJobQueueUrl=$(node -e "process.stdout.write(JSON.parse(process.env.USER_DATA_EXTRA).fileProcessorJobQueueUrl)")"
