name: Test
on: push

jobs:
    unit-tests:
        name: Unit tests
        runs-on: [self-hosted, aws-test]
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Initialize Bazel cache
              uses: ./.github/actions/initialize-bazel-cache

            # Run TypeScript, ESLint, Prettier, and unit tests. These tests are fast and
            # easily cacheable. Running these tests first gives the developer fast feedback
            # and leads to a lower total cost for CI since we can stop executing tests early
            # on failures.
            - name: Unit tests
              run: |
                  admin/bin/bazel --bazelrc=admin/bazel/aspect_bazelrc/ci.bazelrc test //... --config=github-runner --test_tag_filters=-playwright,-macos --nofetch

    integration-tests:
        name: Integration tests
        runs-on: [self-hosted, aws-test]
        strategy:
            matrix:
                test_category:
                    - { name: "Tasks", tag_filter: "playwright_tasks" }
                    - { name: "Documents", tag_filter: "playwright_documents" }
                    - { name: "Forum", tag_filter: "playwright_forum" }
                    - { name: "Miscellaneous", tag_filter: "playwright,-playwright_forum,-playwright_documents,-playwright_tasks" }
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Initialize Bazel cache
              uses: ./.github/actions/initialize-bazel-cache

            # Run integration tests with Playwright. These tests are expensive to run and
            # are flaky. We run them after all other tests have passed and break them into
            # categories to run in parallel.
            #
            # We set `--notest_keep_going`. If any integration test fails we immediately
            # fail the build and exit to speed up test result turnaround time for
            # developers.
            - name: Integration tests
              run: |
                  admin/bin/bazel --bazelrc=admin/bazel/aspect_bazelrc/ci.bazelrc test //... --config=github-runner --test_tag_filters=${{ matrix.test_category.tag_filter }},-macos --nofetch --nokeep_going --notest_keep_going

            # Prepare the `bazel-testlogs` folder for uploading. This script removes the logs
            # and outputs for all tests that passed leaving only the logs and outputs for
            # tests that failed.
            - if: failure()
              name: Prepare Bazel test logs
              run: admin/bazel/prepare_bazel_testlogs_failure_artifact.sh

            - if: failure()
              name: Upload Bazel test logs
              uses: actions/upload-artifact@v4
              with:
                  name: bazel_testlogs
                  path: bazel-testlogs
                  retention-days: 7

    # Single job to check all required commit checks
    # This is used for GitHub's required job status checks
    commit-test-results:
      if: ${{ always() }}
      runs-on: ubuntu-latest
      name: Commit test results
      needs: [unit-tests, integration-tests]
      steps:
        - run: |
            integration_tests_result="${{ needs.integration-tests.result }}"
            if [[ $integration_tests_result == "success" || $integration_tests_result == "skipped" ]]; then
              unit_tests_result="${{ needs.unit-tests.result }}"
              if [[ $unit_tests_result == "success" || $unit_tests_result == "skipped" ]]; then
                exit 0
              else
                exit 1
              fi
            else
              exit 1
            fi

    schedule-deploy:
        name: Schedule deploy
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.SCHEDULE_DEPLOY_AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.SCHEDULE_DEPLOY_AWS_SECRET_ACCESS_KEY }}
        # If tests pass and we're on the main branch then schedule a deploy by sending
        # a message to our job queue via lambda. This will make sure our commit is eventually
        # deployed.
        if: github.ref == 'refs/heads/main'
        needs: [commit-test-results]
        steps:
            - name: Schedule deploy
              run: |
                aws lambda invoke \
                  --function-name ${{ secrets.SCHEDULE_DEPLOY_AWS_LAMBDA_FUNCTION_NAME }} \
                  --payload "{ \"commitSha\": \"${{ github.sha }}\" }" \
                  --cli-binary-format raw-in-base64-out \
                  --region us-east-1 \
                  response.json

