name: Test
on: push

jobs:
    test:
        name: Test
        runs-on: [self-hosted, aws-test]
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Initialize Bazel cache
              uses: ./.github/actions/initialize-bazel-cache

            # Run TypeScript, ESLint, and Prettier first. These tests are fast and easily
            # cacheable. If TypeScript fails it's also very likely unit tests or
            # integration tests will fail since some code is not structured properly.
            #
            # Running these tests first gives the developer fast feedback. It also leads to
            # a lower total cost for CI since we can stop executing tests early on a type
            # system failure.
            - name: Test (tier 1)
              run: |
                  admin/bin/bazel --bazelrc=admin/bazel/aspect_bazelrc/ci.bazelrc test //... --config=github-runner --test_tag_filters=dev-check,-playwright,-macos --nofetch

            # After our tier 1 tests pass run all other tests except integration tests
            # written for Playwright. Playwright integration tests are expensive so we only
            # run them once all other tests have passed.
            - name: Test (tier 2)
              run: |
                  admin/bin/bazel --bazelrc=admin/bazel/aspect_bazelrc/ci.bazelrc test //... --config=github-runner --test_tag_filters=-dev-check,-playwright,-macos --nofetch

            # Run integration tests with Plawright after all other tests have passed. These
            # tests are expensive to run and are flaky. We run them last since if any other
            # test fails there's a good chance integration tests will also fail. So we
            # save resources by not running integration tests.
            #
            # We set `--notest_keep_going`. If any integration test fails we immediately
            # fail the build and exit to speed up test result turnaround time for
            # developers.
            - name: Test (tier 3)
              run: |
                  admin/bin/bazel --bazelrc=admin/bazel/aspect_bazelrc/ci.bazelrc test //... --config=github-runner --test_tag_filters=playwright,-dev-check,-macos --nofetch --nokeep_going --notest_keep_going

            # Prepare the `bazel-testlogs` folder for uploading. This script removes the logs
            # and outputs for all tests that passed leaving only the logs and outputs for
            # tests that failed.
            - if: failure()
              name: Prepare Bazel test logs
              run: admin/bazel/prepare_bazel_testlogs_failure_artifact.sh

            - if: failure()
              name: Upload Bazel test logs
              uses: actions/upload-artifact@v4
              with:
                  name: bazel_testlogs
                  path: bazel-testlogs
                  retention-days: 7

    schedule-deploy:
        name: Schedule deploy
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.SCHEDULE_DEPLOY_AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.SCHEDULE_DEPLOY_AWS_SECRET_ACCESS_KEY }}
        # If tests pass and we're on the main branch then schedule a deploy by sending
        # a message to our job queue via lambda. This will make sure our commit is eventually
        # deployed.
        if: github.ref == 'refs/heads/main'
        needs: [test]
        steps:
            - name: Schedule deploy
              run: |
                aws lambda invoke \
                  --function-name ${{ secrets.SCHEDULE_DEPLOY_AWS_LAMBDA_FUNCTION_NAME }} \
                  --payload "{ \"commitSha\": \"${{ github.sha }}\" }" \
                  --cli-binary-format raw-in-base64-out \
                  --region us-east-1 \
                  response.json

