load("//admin/typescript:typescript.bzl", "ts_project")

ts_project(
    name = "design",
    visibility = [
        "//app:__subpackages__",
        "//client:__subpackages__",
    ],
    deps = [
        "//:node_modules/@popperjs/core",
        "//:node_modules/@react-aria/focus",
        "//:node_modules/@react-aria/interactions",
        "//:node_modules/@react-types/shared",
        "//:node_modules/@remix-run/router",
        "//:node_modules/@types/react",
        "//:node_modules/@types/react-dom",
        "//:node_modules/classnames",
        "//:node_modules/motion",
        "//:node_modules/phosphor-react",
        "//:node_modules/react",
        "//:node_modules/react-aria",
        "//:node_modules/react-dom",
        "//:node_modules/unicode-default-word-boundary",
        "//client/web/context",
        "//client/web/dev",
        "//client/web/helpers",
        "//client/web/icons",
        "//client/web/remix",
        "//client/web/styles",
        "//shared/design",
        "//shared/error",
        "//shared/helpers",
    ],
)
